### PR TITLE
Fix Headless Chrome termination (closes #1826)

### LINKED ISSUE #1826: Headless Chrome processes hang after test run
### How would you reproduce the current behavior (if this is a bug)?

Run tests in headless Chrome: `testcafe chrome:headless test.js -c 5`.
When test run is finished several new chrome processes hang.
Additionally, after test run during browser closing the nodejs process takes too much memory (up to 800MB on my machine).

### Specify your

* operating system: Win 10
* testcafe version: 0.18.0-alpha1
* node.js version: 8.1.4

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @AlexanderMoskovkin @kirovboris

### CODE REVIEW

File: src/browser/provider/utils/kill-browser-process.js [hunk 1]
```diff
@@ -1,17 +1,34 @@
...
 
 
 const BROWSER_CLOSING_TIMEOUT = 5;
 
+async function findProcessWin (processOptions) {
+    var cmd         = `wmic process where "commandline like '%${processOptions.arguments}%' and name <> 'cmd.exe' and name <> 'wmic.exe'" get processid`;
+    var wmicOutput  = await exec(cmd);
+    var processList = wmicOutput.split(/\s*\n/);
+
+    // NOTE: remote list's header and empty last element, caused by trailing newline
```
Comment (kirovboris) [inline src/browser/provider/utils/kill-browser-process.js]: remove list's header?

File: src/browser/provider/utils/kill-browser-process.js [hunk 2]
```diff
@@ -1,17 +1,34 @@
...
+    processList.shift();
```
Comment (kirovboris) [inline src/browser/provider/utils/kill-browser-process.js]: Look like 
```js
processList.splice(1, processList.length - 2) 
```
or
```
processList = processList.slice(1,-1);
```

File: src/browser/provider/utils/kill-browser-process.js [hunk 3]
```diff
@@ -1,17 +1,34 @@
...
+    processList.pop();
+
+    processList = processList.map(pid => ({ pid: Number(pid) }));
+    return processList;
```
Comment (kirovboris) [inline src/browser/provider/utils/kill-browser-process.js]: Please add an empty line before `return`
