### PR TITLE
Fix error messages when can't find firefox & chrome (closes #3534)

### LINKED ISSUE #3534: Different errors for missing browsers
### What is your Test Scenario?
Run a tests specifying not installed browser's alias.
 
### What is the Current behavior?
I get different errors for different browsers:
1) chrome\firefox:
```
Error: Was unable to open the browser "%browserName%" due to error.

Error: Unable to run the browser. The browser path or command template is not specified.
    at checkBrowserPath$ (D:\Projects\github-studio\node_modules\testcafe-browser-tools\lib\api\open.js:47:23)
    at tryCatch (D:\Projects\github-studio\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at Generator.invoke [as _invoke] (D:\Projects\github-studio\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:334:22)
    at Generator.prototype.(anonymous function) [as next] (D:\Projects\github-studio\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:105:21)
    at tryCatch (D:\Projects\github-studio\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:72:40)
    at invoke (D:\Projects\github-studio\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:146:20)
    at D:\Projects\github-studio\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:191:11
    at new Promise (<anonymous>)
    at new F (D:\Projects\github-studio\node_modules\testcafe-browser-tools\node_modules\core-js\library\modules\$.export.js:30:36)
    at callInvokeWithMethodAndArg (D:\Projects\github-studio\node_modules\testcafe-browser-tools\node_modules\babel-runtime\regenerator\runtime.js:190:16)
```
2) opera\safari:
```
Error: Unable to find the browser. "%browserName%" is not a browser alias or path to an executable file.
```
 
### What is the Expected behavior?
Consistent errors.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.0.2-alpha.1
* node.js version:                    v10.15.0
* command-line arguments:  
* browser name and version: 
* platform and version:          Windows 10
* other:

### PR DESCRIPTION
**Pull request by AndreyBelym**
Closes #3534.

### CODE REVIEW

File: src/browser/provider/built-in/chrome/index.js [hunk 1]
```diff
@@ -15,12 +17,15 @@ export default {
 
     isMultiBrowser: false,
 
+    _getBrowserName () {
```
Comment (miherlosev) [inline src/browser/provider/built-in/chrome/index.js]: Firefox and Chrome provides have a lot of code pieces :
```js
openedBrowsers: {},
isMultiBrowser: false,
 async isLocalBrowser () {...}
isHeadlessBrowser (browserId) {...}
 async maximizeWindow (browserId) {...}
```

In this PR you add two more pieces: ` _getBrowserName`  and `isValidBrowserName`.
Is it time to allocate this in a separate base class?

**Comment by AndreyBelym** [comment]
FPR \cc @AlexKamaev @LavrovArtem

**Comment by vire** [comment]
possible related regression https://github.com/DevExpress/testcafe-browser-provider-saucelabs/issues/52
