### PR TITLE
Make screenshot mark black'n'white (closes #2145)

### LINKED ISSUE #2145: TakeElementScreenshot doesn't work in Chrome with default `Force color profile` flag
Version: 0.19.0-alpha1

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @AlexanderMoskovkin @helen-dikareva

### CODE REVIEW

File: src/screenshots/generate-mark.js [hunk 1]
```diff
@@ -1,20 +1,17 @@
 import generateId from 'nanoid/generate';
 import { PNG } from 'pngjs';
-import { chunk, flatten } from 'lodash';
+import { map, flatten } from 'lodash';
+import { MARK_LENGTH } from './constants';
 
 
-const ALPHABET    = '1234567890abcdef';
-const MARK_LENGTH = 5;
+const ALPHABET    = '01';
```
Comment (helen-dikareva) [inline src/screenshots/generate-mark.js]: wrong formating
