### PR TITLE
Fixed mouseup emulation for click automation (closes #423)

### LINKED ISSUE #423: Wrong emulation of 'click' event if target element was changed during 'mousedown' or  'mouseup'
By now we just don't emulate `click` event if target element was changed during `mousedown` (and following `blur` and `focus`). Target element is an element returned by `document.elementFromPoint` for the point in which we need to perform a 'click' action event. We check this condition before emulating `mouseup`. 
But looks like rules are more complex:

 1. If changed element is contained in original target element, it will be a target for `mouseup` event. Also in this case a `click` event will be raised for the original target element.

 2.  If target element is changed during `mouseup` event, it must be contained in target element of `mousedown` event in order to raise `click` event. Target for `click` event will be a target element for 'mousedown' event.

Example:
Suppose we have elements `div1`, `div2`, `div3`. We are clicking on `div1`. For the event listeners:
```js
        //div1
        div1.addEventListener('mousedown', () => {
             console.log('div1 mousedown');
             div1.innerHTML = ''; //to get same bounding rectangle as a child element
             div1.appendChild(div2);
        });

        div1.addEventListener('mouseup', () => console.log('div1 mouseup'));

        div1.addEventListener('click', () => console.log('div1 click'));

        //div 2
        div1.addEventListener('mousedown', () => console.log('div2 mousedown'));

        div2.addEventListener('mouseup', () => {
              console.log('div2 mouseup');
              div2.innerHTML = ''; //to get same bounding rectangle as a child element
              div2.appendChild(div3);
        });

        div2.addEventListener('click', () => console.log('div2 click'));

        //div3
        div3.addEventListener('mousedown', () => console.log('div3 mousedown'));

        div3.addEventListener('mouseup', () => console.log('div3 mouseup'));

        div3.addEventListener('click', () => console.log('div3 click'));
```
the log output will be:
```
div1 mousedown
div2 mouseup
div1 click
```

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @inikulin, @AlexanderMoskovkin, @helen-dikareva, @VasilyStrelyaev

### CODE REVIEW

File: test/client/fixtures/automation/click-test.js [hunk 1]
```diff
@@ -775,6 +776,99 @@ $(document).ready(function () {
         }, 1500);
     });
 
+    asyncTest('Should raise click event except Firefox if target element appends child after mousedown (GH-423)', function () {
```
Comment (AlexanderMoskovkin) [inline test/client/fixtures/automation/click-test.js]: Please don't use qunit to test automations since we have functional tests.
Try to keep the rule: qunit - for unit testing, testcafe test (our functional test harness) - for functional testing. 

This fix relates to automation sources, they are common for es-next and legacy api. So you should just add a functional test for es-next api

File: src/client/automation/playback/click/index.js [hunk 2]
```diff
@@ -225,12 +225,20 @@ export default class ClickAutomation {
         return cursor
             .buttonUp()
             .then(() => {
-                var prevElementForEvent = this.eventArgs.element;
-
-                this.eventArgs            = this._calculateEventArguments();
-                this.eventState.skipClick = prevElementForEvent !== this.eventArgs.element;
-
-                eventSimulator.mouseup(this.eventArgs.element, this.eventArgs.options);
+                var topElementEventArgs = this._calculateEventArguments();
```
Comment (AlexanderMoskovkin) [inline src/client/automation/playback/click/index.js]: It's better to keep 
```js
var prevElementForEvent = this.eventArgs.element;

this.eventArgs            = this._calculateEventArguments();
```

because `this.eventArgs` is used in other methods of the class, so you should keep this as it is to avoid unexpected problems

Comment (helen-dikareva) [inline src/client/automation/playback/click/index.js]: Before we assing ` this.eventArgs` before raise `mouseup`. And raise `click` for `this.eventArgs.element`.
Should not we do it?

Comment (georgiy-abbasov) [inline src/client/automation/playback/click/index.js]: I agree, that this.eventArgs.options and this.eventArgs.point should be recalculated, but click should be raised over previous element.

File: src/client/automation/playback/click/index.js [hunk 3]
```diff
@@ -225,12 +225,20 @@ export default class ClickAutomation {
...
+
+                if (this.eventArgs.element !== topElementEventArgs.element) {
+                    // NOTE: Mozilla Firefox always prevents click emulation
+                    // if the element under cursor has been changed.
+                    if (browserUtils.isFirefox)
+                        this.eventState.skipClick = true;
+                    else {
+                        this.eventState.skipClick = !this.eventArgs.element.contains(topElementEventArgs.element) &&
+                                                    !topElementEventArgs.element.contains(this.eventArgs.element);
```
Comment (AlexanderMoskovkin) [inline src/client/automation/playback/click/index.js]: What the scenario covers the second condition?

File: src/client/automation/playback/click/index.js (hunk 2 above)
Comment (AlexanderMoskovkin) [inline src/client/automation/playback/click/index.js]: it should something like `this.clickEventElement` then.

File: src/client/automation/playback/click/index.js (hunk 3 above)
Comment (georgiy-abbasov) [inline src/client/automation/playback/click/index.js]: `!topElementEventArgs.element.contains(this.eventArgs.element)` - there is no scenario for this condition, my fault.

File: src/client/automation/playback/click/index.js (hunk 2 above)
Comment (AlexanderMoskovkin) [inline src/client/automation/playback/click/index.js]: @helen-dikareva maybe `this.eventArgs -> this.lastEventArgs`, what do you think?

Comment (helen-dikareva) [inline src/client/automation/playback/click/index.js]: we usually calculate `eventArgs` before raise event, so I like more just `eventArgs`

File: test/functional/fixtures/regression/gh-423/test.js [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+
+    it("Shouldn't not raise click if target is overlapped", function () {
+        return runTests('testcafe-fixtures/index.test.js', "Don't raise click if target is overlapped");
+    });
+
+    it("Should raise click event in Firefox if target's parent has been changed after mousedown", function () {
+        return runTests('testcafe-fixtures/index.test.js', 'Raise click if target parent changed', { only: ['firefox', 'firefox-osx'] });
+    });
+
+    it("Shouldn't raise click event except Firefox if target's parent been has changed  after mousedown", function () {
```
Comment (VasilyStrelyaev) [inline test/functional/fixtures/regression/gh-423/test.js]: > been has changed

File: src/client/core/utils/dom.js [hunk 5]
```diff
@@ -443,3 +443,9 @@ export function findIframeByWindow (iframeWindow, iframeDestinationWindow) {
 
     return null;
 }
+
+export function canAcceptValue (element) {
```
Comment (VasilyStrelyaev) [inline src/client/core/utils/dom.js]: are you sure about this `accept value` ?
what do these elements have in common? is this about 'accepting values'?

File: test/functional/fixtures/regression/gh-423/test.js [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+        return runTests('testcafe-fixtures/index.test.js', "Don't raise click if target parent changed", { skip: ['firefox', 'firefox-osx'] });
+    });
+
+    it("Shouldn't raise click if target appends element that can take a value", function () {
```
Comment (VasilyStrelyaev) [inline test/functional/fixtures/regression/gh-423/test.js]: see
https://github.com/DevExpress/testcafe/pull/753/files#r77666902

**Comment by VasilyStrelyaev** [comment]
\r-

File: test/functional/fixtures/regression/gh-423/test.js [hunk 7]
```diff
@@ -0,0 +1,25 @@
+describe('[Regression](GH-423)', function () {
+    it('Should raise click event except Firefox if target element appends child after mousedown', function () {
```
Comment (VasilyStrelyaev) [inline test/functional/fixtures/regression/gh-423/test.js]: except in Firefox

File: test/functional/fixtures/regression/gh-423/test.js (hunk 4 above)
Comment (VasilyStrelyaev) [inline test/functional/fixtures/regression/gh-423/test.js]: except in Firefox

**Comment by VasilyStrelyaev** [comment]
\r-

File: src/client/automation/playback/click/index.js [hunk 8]
```diff
@@ -225,10 +231,19 @@ export default class ClickAutomation {
...
+                    else {
+                        this.eventState.skipClick = !this.clickEventElement.contains(this.eventArgs.element) ||
+                                                    domUtils.canAcceptValue(this.eventArgs.element);
+                    }
+                }
 
-                this.eventArgs            = this._calculateEventArguments();
-                this.eventState.skipClick = prevElementForEvent !== this.eventArgs.element;
+                if (this.clickEventElement === this.eventArgs.element && !browserUtils.isFirefox)
+                    this.eventState.skipClick = !arrayUtils.equals(this.targetElementParentNodes, domUtils.getParents(this.eventArgs.element));
```
Comment (inikulin) [inline src/client/automation/playback/click/index.js]: Why not ternary here?

File: src/client/core/utils/array.js [hunk 9]
```diff
@@ -66,3 +66,22 @@ export function remove (arr, item) {
...
+
+export function equals (arr1, arr2) {
+    if (!arr2)
+        return false;
+
+    if (arr1.length !== arr2.length)
+        return false;
+
+    for (var i = 0, l = arr1.length; i < l; i++) {
+        if (arr1[i] instanceof Array && arr2[i] instanceof Array) {
```
Comment (inikulin) [inline src/client/core/utils/array.js]: First of all `instanceof Array` is not frame-safe. Also, do we really need this deep comparison? If so, why it's not named `deepEquals`?

File: test/functional/fixtures/regression/gh-423/testcafe-fixtures/index.test.js [hunk 10]
```diff
@@ -0,0 +1,69 @@
...
+
+const getEventStorage = ClientFunction(()=> window.eventStorage);
+
+
+test("Don't raise click if target is overlapped", async t => {
+    var expectedEvents = ['target mousedown', 'element mouseup'];
+
+    await t.click('#target1');
+
+    var actualEvents = await getEventStorage();
```
Comment (inikulin) [inline test/functional/fixtures/regression/gh-423/testcafe-fixtures/index.test.js]: Use `const` or `let`

**Comment by inikulin** [comment]
\r-

File: src/client/core/utils/array.js (hunk 9 above)
Comment (georgiy-abbasov) [inline src/client/core/utils/array.js]: We should check whether target element is changed position in the DOM. If it changes parent, but still on previous place, click doesn't raised natively in all browser (exc. Firefox)

Comment (AlexanderMoskovkin) [inline src/client/core/utils/array.js]: it's true, but you didn't answer the question, do we really need this *deep* comparison.

You have two arrays: [parentA1, parentB1, parentC1], [parentA2, parentB2, parentC2]. Why do you need to check `if (arr1[i] instanceof Array && arr2[i] instanceof Array)`?
You just check `arr1.length === arr2.length` and `arr1[n] === arr2[n]`

Comment (georgiy-abbasov) [inline src/client/core/utils/array.js]: My fault, we don't need deep comparsion in this case.

File: src/client/core/utils/dom.js (hunk 5 above)
Comment (georgiy-abbasov) [inline src/client/core/utils/dom.js]: @VasilyStrelyaev, in common these elements are input elements (they are placed for taking input data from user).
Can we pick an another common word or words combination for grouping these elements?

Comment (VasilyStrelyaev) [inline src/client/core/utils/dom.js]: @georgiy-abbasov hmm... if not `input` than probably `editor`?
`isEditorElement` ? @inikulin

Comment (inikulin) [inline src/client/core/utils/dom.js]: There is not special term in HTML spec that fits well for this meaning, e.g. see [textarea categories](https://html.spec.whatwg.org/#the-textarea-element). However `isEditorElement` sounds good to me

Comment (georgiy-abbasov) [inline src/client/core/utils/dom.js]: The word `editor`  has a narrower meaning (more specified) in my opinion. 
@VasilyStrelyaev, can we use the word "intake" ?

Comment (inikulin) [inline src/client/core/utils/dom.js]: > can we use the word "intake"

No.

> The word editor has a narrower meaning (more specified) in my opinion.

Call it `isEditableFormElement`

Comment (georgiy-abbasov) [inline src/client/core/utils/dom.js]: > Call it isEditableFormElement
That's better. Thanks @inikulin

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by georgiy-abbasov** [comment]
FPR

File: src/client/core/utils/array.js [hunk 11]
```diff
@@ -66,3 +66,18 @@ export function remove (arr, item) {
     if (index > -1)
         nativeSplice.call(arr, index, 1);
 }
+
+export function equals (arr1, arr2) {
+    if (!arr2)
```
Comment (inikulin) [inline src/client/core/utils/array.js]: In which case `arr2` can be `null`?

File: src/client/core/utils/dom.js [hunk 12]
```diff
@@ -443,3 +443,9 @@ export function findIframeByWindow (iframeWindow, iframeDestinationWindow) {
 
     return null;
 }
+
+export function isEditableFormElement (element) {
+    var tag = getTagName(element);
```
Comment (inikulin) [inline src/client/core/utils/dom.js]: `tag` -> `tagName`

File: src/client/core/utils/array.js (hunk 11 above)
Comment (georgiy-abbasov) [inline src/client/core/utils/array.js]: There is no case. `domUtils.getParents` returns empty array, if argument was top element

File: src/client/core/utils/dom.js [hunk 13]
```diff
@@ -443,3 +443,9 @@ export function findIframeByWindow (iframeWindow, iframeDestinationWindow) {
...
+
+    return tag === 'select' || tag === 'input' || tag === 'textarea';
```
Comment (AlexanderMoskovkin) [inline src/client/core/utils/dom.js]: it's better to use Hammerhead utils: [one](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/dom.js#L599), [two](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/dom.js#L431)

File: test/functional/fixtures/regression/gh-423/pages/index.html [hunk 14]
```diff
@@ -0,0 +1,157 @@
...
+
+        window.eventStorage.push('target mousedown');
+    });
+
+    target1.addEventListener('mouseup', function () {
+        window.eventStorage.push('target mouseup');
+    });
+
+    target1.addEventListener('click', function () {
+        window.eventStorage.push('target click');
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/regression/gh-423/pages/index.html]: I suppose, it's better to specify what the target was clicked (change `target` to `target1`). 
Also you can unify this handlers:
function saveEventToStorage (e) {
    window.eventStorage.push(e.target.id + ' ' + e.type);
}

target1.addEventListener('mouseup', saveEventToStorage);
element.addEventListener('mousedown', saveEventToStorage); etc...

File: test/functional/fixtures/regression/gh-423/test.js [hunk 15]
```diff
@@ -0,0 +1,25 @@
+describe('[Regression](GH-423)', function () {
+    it('Should raise click event except in Firefox if target element appends child after mousedown', function () {
+        return runTests('testcafe-fixtures/index.test.js', 'Raise click if target appends child', { skip: ['firefox', 'firefox-osx'] });
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/regression/gh-423/test.js]: you can write just `skip: ['firefox']` because of [this `indexOf` check](https://github.com/DevExpress/testcafe/blob/master/test/functional/setup.js#L142)

Comment (georgiy-abbasov) [inline test/functional/fixtures/regression/gh-423/test.js]: Nope:
`['firefox'].indexOf('firefox-osx') // returns -s`

Comment (AlexanderMoskovkin) [inline test/functional/fixtures/regression/gh-423/test.js]: hmmm, yes. My mistake. But on my feeling it should be conversely. 
I see no cases when the `skipOption.indexOf(browserInfo.settings.alias)` check may be useful, but now we have a case when the `browserInfo.settings.alias.indexOf(skipOption)` is better

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

File: test/functional/fixtures/regression/gh-423/pages/index.html [hunk 16]
```diff
@@ -0,0 +1,105 @@
...
+<div id="target3" style="left: 300px;background: violet;position: absolute; width:50px; height:50px;">
+</div>
+<div id="newParent" style="left: 300px;top:200px;background: yellow;position: absolute; width:100px; height:100px;">
+</div>
+<div id="target4" style="left:450px; background:orange;position: absolute; width:100px; height:100px;">
+</div>
+<input id="input" style="left:450px; top: 200px; position: absolute;">
+<script>
+    function saveEventToStorage (e) {
+        window.eventStorage.push(e.currentTarget.id + ' ' + e.type);
```
Comment (helen-dikareva) [inline test/functional/fixtures/regression/gh-423/pages/index.html]: Why you use `e.currentTarget` not `e.target`? I think better use `e.target` to check for what element event was raised.

Comment (AlexanderMoskovkin) [inline test/functional/fixtures/regression/gh-423/pages/index.html]: agree

Comment (georgiy-abbasov) [inline test/functional/fixtures/regression/gh-423/pages/index.html]: In that case [this line](https://github.com/DevExpress/testcafe/pull/753/files/174a0a584bf230f381f3269597ac15e2001043b2#diff-1d32e523b9a54ebb761ded0f76f558f1R32) will be another:
`const expectedEvents = ['target2 mousedown', 'target2 mouseup', 'target2 mouseup'];`, 
So, you think, that we shouldn't check, was even raised event on appended element ?

Comment (AlexanderMoskovkin) [inline test/functional/fixtures/regression/gh-423/pages/index.html]: it's reasonable. @georgiy-abbasov is right. In our case it's better to know what the handlers were called. So, I think we should leave it as is

Comment (helen-dikareva) [inline test/functional/fixtures/regression/gh-423/pages/index.html]: let's. lgtm then

**Comment by AlexanderMoskovkin** [comment]
@VasilyStrelyaev please look at this one more time. It possible it were some changes since your last review

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by georgiy-abbasov** [comment]
Thanks. Somebody, merge please.
