### PR TITLE
fix: fixed a parsing issue that caused by empty quarantine mode arguments (closes #6231)

### LINKED ISSUE #6231: Refactor CLI options to allow configuring quarantine
Before, `--quarantine-mode` was a boolean switch. That allowed using it like `testcafe -q chrome test.js`

If we allow optional parameters for it, (`-q opt=value`), the parser cannot deduct that `chrome` or `test.js` are not an input for this property

~~So we should use the dedicated `--quarantine-options retryCount=X,passCount=Y` switch.~~
UPDATE: We decided to fix the original case without adding the `--quarantine-options` option.

Options:
- [ ] ~~Add the `--quarantine` alias to `--quarantine-mode` to make naming more consistent.~~
- [x] Rename quarantine parameters as `attemptLimit` and `successThreshold` (https://github.com/DevExpress/testcafe/pull/6312)

Assignee: @Farfurix

### PR DESCRIPTION
**Pull request by Farfurix**
## Purpose
Fix parsing CLI issue: `testcafe -q chrome test.js`, `testcafe chrome -q test.js`.

## Approach
Modifying CLI arguments before parsing. Additional changes: added quarantine option validation to non-CLI interfaces.

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

File: src/runner/index.js [hunk 1]
```diff
@@ -384,6 +385,13 @@ export default class Runner extends EventEmitter {
         throw new GeneralError(RUNTIME_ERRORS.cannotEnableRetryTestPagesOption);
     }
 
+    _validateQuarantineOptions () {
+        const quarantineMode = this.configuration.getOption(OPTION_NAMES.quarantineMode);
+
+        if (typeof quarantineMode === 'object')
+            validateQuarantineOptions(quarantineMode, 'quarantineMode');
```
Comment (AndreyBelym) [inline src/runner/index.js:392]: Maybe we should use `OPTION_NAMES.quarantineMode` here?

**Review by AndreyBelym — APPROVED** [review]

**Review by miherlosev — APPROVED** [review]
