### PR TITLE
do not dispose temp profile on browser restart (closes #4554)

### LINKED ISSUE #4554: Concurrent Chrome can't reconnect after restart
### What is your Test Scenario?
Continue testing after browsers do not respond in concurrency mode.
 
### What is the Current behavior?
When a number of concurrent browsers restart simultaneously, some of them can't reconnect to TestCafe due to ERR_CACHE_READ_FAILURE for TestCafe resources.
  
### What is the Expected behavior?
TestCafe continues the test session after restarting browsers,
 
### What is your web application and your TestCafe test code?

NOTE: I've disabled the browser heartbeat and decreased the disconnection timeout down to 10 seconds.

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture`1`.page`example.com`;

test(`1`, async t => {
    await t.wait(30000);
});

test(`2`, async t => {
    await t.wait(30000);
});

test(`3`, async t => {
    await t.wait(30000);
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```
 - Chrome 78.0.3904.108 / Windows 10

 1
ERROR The Chrome 78.0.3904.108 / Windows 10 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.7.0
* node.js version:                    10.15.0
* command-line arguments:  `testcafe chrome -c 3 test.js`
* browser name and version: 
* platform and version:          
* other:

### PR DESCRIPTION
**Pull request by AlexKamaev**
It looks like a Chrome bug. If smth deletes Chrome temp profile folders when multiple Chrome instances are running, it breaks Chrome cache and leads to ERR_CACHE_READ_FAILURE.
I found a hint here: https://stackoverflow.com/questions/36741489/err-cache-read-failure-in-google-chrome

The solution: do not remove temp profile directories when browser is restarting.

All these temp direcotries will be removed when TestCafe finishes

### CODE REVIEW

**Review by AndreyBelym — APPROVED** [review]

File: src/browser/connection/index.ts [hunk 1]
```diff
@@ -59,6 +59,10 @@ interface ProviderMetaInfoOptions {
     appendToUserAgent?: boolean;
 }
 
+export interface BrowserCloseData {
```
Comment (miherlosev) [inline src/browser/connection/index.ts:62]: I proposing rename `BrowserCloseData` interface to `BrowserClosingInfo` for consistency (`BrowserInfo` and `ProviderMetaInfoOptions`).

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by miherlosev — APPROVED** [review]
