### PR TITLE
fix: create correct raw-callsite for hooks 

### LINKED ISSUE #7089: A non-informative report is generated for a failed assertion when running the *.testcafe fixture file using the CLI
### What is your Scenario?

Need to find out which assertion of the recorded (*.testcafe) test fails.

### What is the Current behavior?

If some action fails, the report shows an incorrect selector:
image

However, when an assertion fails, no selector info is shown:
image

### What is the Expected behavior?

It should show verbose info of the failed assertion.

### What is your public website URL? (or attach your complete example)

See the attachment

### What is your TestCafe test code?

[recorded-examples.zip](https://github.com/DevExpress/testcafe/files/8907776/recorded-examples.zip)

### Your complete configuration file

_No response_

### Your complete test report

_No response_

### Screenshots

_No response_

### Steps to Reproduce

1.
2.
3.

### TestCafe version

1.19.0

### Node.js version

16.14.2

### Command-line arguments

npx testcafe chrome recorded-examples.testcafe

### Browser name(s) and version(s)

_No response_

### Platform(s) and version(s)

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by Aleksey28**
[closes #7089]

## Purpose
`actionId` for hooks in raw-tests has a prefix, that is why it is impossible to parse it as Integer and impossible to create a callsite. It needs to use `actionId` without parsing.

## Approach
1. Add test for error in hooks
2. Fix using actionId

## References
https://github.com/DevExpress/testcafe/issues/7089

## Pre-Merge TODO
- [X] Write tests for your proposed changes
- [x] Make sure that existing tests do not fail

### CODE REVIEW

File: test/functional/fixtures/api/raw/test-controller/test.js [hunk 1]
```diff
@@ -2,8 +2,9 @@ const { expect } = require('chai');
 
 // NOTE: we run tests in chrome only, because we mainly test server API functionality.
 // Actions functionality is tested in lower-level raw API.
-describe('[Raw API] TestController', () => {
-    it('Should produce correct callsites for chained calls in raw test', () => {
+/* eslint-disable */
+describe.only('[Raw API] TestController', () => {
```
Comment (helen-dikareva) [inline test/functional/fixtures/api/raw/test-controller/test.js:6]: remove only

**Review by helen-dikareva — APPROVED** [review]

**Review by aleks-pro — APPROVED** [review]

**Comment by helen-dikareva** [comment]
please include it in 2.0.1 minor

**Review by AndreyBelym — APPROVED** [review]
