### PR TITLE
Fix multiple debug in headless mode warnings (closes #6605)

### LINKED ISSUE #6605: Fix multiple "Using t.debug in headless mode" warnings emitted via reportWarnings

### PR DESCRIPTION
**Pull request by AlexKamaev**
The `_enqueueSetBreakpointCommand` method is called from multiple places, so it's not suitable for emitting a warning. I moved the warning to the `_internalExecuteCommand` method.

### CODE REVIEW

**Review by AndreyBelym — APPROVED** [review]

**Review by Farfurix — APPROVED** [review]

File: test/functional/fixtures/regression/gh-2846/testcafe-fixtures/index.js [hunk 1]
```diff
@@ -2,4 +2,7 @@ fixture `GH-2846`;
 
 test(`Debug`, async t => {
     await t.debug();
+
+    // NOTE: for https://github.com/DevExpress/testcafe/issues/6605
+    await t.wait(1);
```
Comment (miherlosev) [inline test/functional/fixtures/regression/gh-2846/testcafe-fixtures/index.js:7]: Need to check that the test report contains only one `Using t.debug in headless mode` warning.

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: test/functional/fixtures/regression/gh-2846/testcafe-fixtures/index.js (hunk 1 above)
Comment (AlexKamaev) [reply test/functional/fixtures/regression/gh-2846/testcafe-fixtures/index.js:7]: The test already has this. Take a look here:
https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/regression/gh-2846/test.js#L13

Comment (miherlosev) [reply test/functional/fixtures/regression/gh-2846/testcafe-fixtures/index.js:7]: Ok

**Review by miherlosev — APPROVED** [review]
