### PR TITLE
Fixed cursor behavior on moving out from iframe (closes #850)

### LINKED ISSUE #850: Problem when moving out cursor from reloaded iframe
We have a problem when cursor tries to move out from reloaded iframe. Common scenario is next:
1. We perform an action inside iframe, which leads to reload or redirect in iframe.
2. We switch to top window, then try to perform an action there.
3. Since the position of the cursor after reload is `{x: -1, y: -1}`, line from this position to target point doesn't intersect iframe borders, it leads to an exception in `MoveAutomation.onMoveOutRequest` method
As the result - the test hangs (next API) or fails (legacy API).

Example to reproduce problem:

index.html:
```html
<button id="button">
    Simple button
</button>
<iframe id="iframe" src="iframe.html" height="200px" width="200px" style="left:20px; top:100px; position:absolute"></iframe>
```
iframe.html:

```
<button id="replaceSrc">Replace iframe source via top window</button>
<script>
    document
    	.getElementById('replaceSrc')
    	.addEventListener('click', function () {
        	window.top.document.getElementById('iframe').src = 'iframe.html';
    	});
</script>
```

index.test.js:
```js
'@test'['Move from replaced iframe'] = {
    '1.Click replace button': inIFrame('#iframe', function () {
        act.click('#replaceSrc');
    }),

    '2.Click top window button': function () {
        act.click('#button')
    }
};
```

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @AlexanderMoskovkin, @helen-dikareva, @AndreyBelym

### CODE REVIEW

**Comment by georgiy-abbasov** [comment]
Rebased. FPR

File: test/functional/fixtures/regression/gh-850/test.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+describe('[Regression](GH-850)', function () {
+    it('Should resume the test if the cursor is moving from reloaded iframe to top window', function () {
+        this.timeout(40000);
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/regression/gh-850/test.js]: why we need this?

Comment (georgiy-abbasov) [inline test/functional/fixtures/regression/gh-850/test.js]: I got timeout error when testing this test in loop locally with Travis. I repeated it and i've got it [this error](http://content.screencast.com/users/GeorgeZA/folders/Jing/media/dcdd2bd5-9ea8-4b43-be68-83f1aebe9884/2016-10-04_1931.png) again (looks like it's better to increase `selectorTimeout` too)

File: src/client/automation/playback/move.js [hunk 2]
```diff
@@ -158,6 +158,17 @@ export default class MoveAutomation {
         var endPoint          = { x: e.message.endX, y: e.message.endY };
         var intersectionPoint = getLineRectIntersection(startPoint, endPoint, iframeRectangle);
 
+        // NOTE: We should skip moving out, if there is no intersection point.
```
Comment (VasilyStrelyaev) [inline src/client/automation/playback/move.js]:
```
        // NOTE: We should not move the cursor out of the iframe if the cursor path does not
        // intersect with the iframe borders.
```

File: test/functional/fixtures/regression/gh-850/test.js (hunk 1 above)
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/regression/gh-850/test.js]: Do you mean it's ok that the tests is not finished in 30 seconds?? You should found out why it happened

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
FPR

File: test/functional/fixtures/regression/gh-850/test.js (hunk 1 above)
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/regression/gh-850/test.js]: Let's rerun tests on this PR several times (3 is enought). If this test is ok, we will merge this. If it's unstable we should modify it or find the cause of this before merge

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

File: test/functional/fixtures/regression/gh-850/test.js [hunk 3]
```diff
@@ -0,0 +1,7 @@
+describe('[Regression](GH-850)', function () {
+    it('Should resume the test if the cursor is moving from reloaded iframe to top window', function () {
+        // NOTE: we set selectorTimeout to a large value to wait for an iframe to load
+        // on the farm (it is fast locally but can take some time on the farm)
+        return runTests('testcafe-fixtures/index.test.js', 'Move from reloaded iframe', { selectorTimeout: 3000 });
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/regression/gh-850/test.js]: It's all ok, just increase please `selectorTimeout` for this tests to avoid the problems with slow connection on saucelabs vms (use 10 sec to be sure)
