### PR TITLE
Fix selector text filter for `document` nodes in MSEdge 14 (closes #875)

### LINKED ISSUE #875: Selector text filter doesn't work on `document` in MSEdge 14

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @helen-dikareva

### CODE REVIEW

**Comment by inikulin** [comment]
Rebased to fix compiler tests

File: src/client/driver/command-executors/client-functions/selector-executor/index.js [hunk 1]
```diff
@@ -60,17 +60,39 @@ function hasText (node, textRe) {
         return textRe.test(text);
     }
 
-    // Document and DocumentFragment
-    if (node.nodeType === 9 || node.nodeType === 11)
-        return !!filterNodeCollectionByText(node.childNodes, textRe).length;
+    // Document
+    if (node.nodeType === 9) {
+        // NOTE: latest version of Edge doesn't have `innerText` for `document`,
+        // `html` and `body`. So we check their children instead.
```
Comment (helen-dikareva) [inline src/client/driver/command-executors/client-functions/selector-executor/index.js]: I thing we should remove  `document` form comment, because no one browser have `innerText` for `document`, only for `documentElement` === `html` element

Comment (inikulin) [inline src/client/driver/command-executors/client-functions/selector-executor/index.js]: That's OK and it's actually true, I don't want to re-trigger CI for that.

Comment (helen-dikareva) [inline src/client/driver/command-executors/client-functions/selector-executor/index.js]: oooook
