### PR TITLE
fix serviceWorker with native automation (closes #7675)

### LINKED ISSUE #7675: Native Automation: `importScripts` error when using Service Worker
```JS
fixture`monaco`.page`https://microsoft.github.io/monaco-editor/playground.html?source=v0.34.1#example-creating-the-editor-hello-world`;

test('Test', async t => {
    await t.debug();
});
```

### PR DESCRIPTION
**Pull request by AlexKamaev**

### CODE REVIEW

File: src/native-automation/request-pipeline/special-handlers.ts [hunk 1]
```diff
@@ -17,17 +17,23 @@ import { toBase64String } from '../utils/string';
 import {
     safeContinueRequest,
     safeContinueResponse,
-    safeFailRequest,
     safeFulfillRequest,
 } from './safe-api';
 
+async function ignoreRequestPausedEvent (event: RequestPausedEvent, client: ProtocolApi): Promise<void> {
```
Comment (miherlosev) [inline src/native-automation/request-pipeline/special-handlers.ts:23]: rename to `handleRequestOrResponse` or `handleRequestPauseEvent`.

File: test/functional/fixtures/regression/gh-7675/pages/xhr.html [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+<html lang="en">
+<head>
+    <meta charset="UTF-8">
+    <title>Worker</title>
+</head>
+<body>
+<h1>Worker</h1>
+<script>
+    function handleWorkerMessage (msg) {
+        document.querySelector('h1').innerHTML = msg.data.foo
```
Comment (miherlosev) [inline test/functional/fixtures/regression/gh-7675/pages/xhr.html:11]: Add the `;` symbol to the end of this line.

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by miherlosev — APPROVED** [review]
