### PR TITLE
fix invisible iframe error issue(closes #3681)

### LINKED ISSUE #3681: Switch to IFrame: TypeError: Cannot call a class as a function
A strange error appears during switching to an iframe if this iframe is invisible.
image

URL: [https://demos.devexpress.com/ASPxSpreadsheetDemos/Features/DocumentManagement.aspx](https://demos.devexpress.com/ASPxSpreadsheetDemos/Features/DocumentManagement.aspx)

Test: 
```js
import { Selector } from 'testcafe';

fixture `https://demos.devexpress.com/ASPxSpreadsheetDemos/Features/DocumentManagement.aspx`
    .page `https://demos.devexpress.com/ASPxSpreadsheetDemos/Features/DocumentManagement.aspx`;

test('New Test', async t => {
    await t
        .switchToIframe(Selector('#ContentHolder_Spreadsheet_IT'));
});
```

### PR DESCRIPTION
**Pull request by AlexKamaev**

### CODE REVIEW

File: test/functional/fixtures/regression/gh-3681/test.js [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+describe('[Regression](GH-3681) - Should throw correct errors for non-exising and invisible iframes', function () {
+    it('Invisible iframe', function () {
+        return runTests('./testcafe-fixtures/index.js', 'Invisible iframe', { shouldFail: true, selectorTimeout: 1 })
+            .catch(function (errs) {
+                expect(errs[0]).contains('The element that matches the specified selector is not visible');
+                expect(errs[0]).contains('.switchToIframe(Selector(\'iframe\')');
+            });
+    });
+
+    it('Non-existing iframe', function () {
```
Comment (helen-dikareva) [inline test/functional/fixtures/regression/gh-3681/test.js]: We already have [a test](https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/api/es-next/iframe-switching/test.js#L56) for this error.
Would you mind just add missing test for invisible iframe error in that file?
