### PR TITLE
Overhaul t.resizeWindow and implement t.maximizeWindow (closes #816, closes #812)

### LINKED ISSUE #812: Implement `t.maximizeWindow`
# Feature summary

### maximizeWindow (browserId)
Maximizes the browser window `browserId`.

### LINKED ISSUE #816: Incorrect resizeToFitDevice on mac with portaitOrientation=true
``` javascript
fixture('React').page('https://facebook.github.io/react/');

test('Resize to fit device', async t => {
    await t.resizeWindowToFitDevice('Nexus 7 (2013)', { portraitOrientation: true });

    const getWindowHeight = ClientFunction(() => window.innerHeight);
    const getWindowWidth  = ClientFunction(() => window.innerWidth);

    expect(await getWindowHeight()).eql(960);
    expect(await getWindowWidth()).eql(600);
});
```

`AssertionError: expected 896 to deeply equal 960`

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @inikulin @kirovboris @VasilyStrelyaev

### CODE REVIEW

File: src/browser/provider/built-in/base.js [hunk 1]
```diff
@@ -15,10 +16,22 @@ function getCurrentSize () {
         height: window.innerHeight,
     };
 }
+
+function getMacSizeInfo () {
```
Comment (inikulin) [inline src/browser/provider/built-in/base.js]: `getWindowDimensionsInfo` - it's not related to Mac on it's own, so we can ommit `Mac` from the name

Comment (inikulin) [inline src/browser/provider/built-in/base.js]: BTW, can we get rid of duplication and just use `getSize` for this purpose (also rename it)?

File: src/browser/provider/built-in/base.js [hunk 2]
```diff
@@ -42,13 +55,18 @@ function subtractSizes (sizeA, sizeB) {
     };
 }
 
+function exceedsMaxSize (width, height, maxSize) {
```
Comment (inikulin) [inline src/browser/provider/built-in/base.js]: `exceedsMaxScreenSize`

File: src/browser/provider/built-in/path.js [hunk 3]
```diff
@@ -44,6 +44,8 @@ export default class PathBrowserProvider extends BrowserProviderBase {
 
         if (OS.win)
             await super.calculateResizeCorrections(browserId);
+        else if (OS.mac)
```
Comment (inikulin) [inline src/browser/provider/built-in/path.js]: Shouldn't it be in base provider? (like resize corrections). I wonder how I can use this functionality in my browser provider (e.g. for redistributable browsers)

File: src/browser/provider/built-in/remote.js [hunk 4]
```diff
@@ -7,14 +7,19 @@ export default class RemoteBrowserProvider extends BrowserProviderBase {
     constructor () {
         super();
 
-        // NOTE: This can be used to disable resize correction when running unit tests.
-        this.disableResizeHack = false;
+        // NOTE: This can be used to disable resize correction or maximum size calculation when running unit tests.
+        this.disableHacks = false;
```
Comment (inikulin) [inline src/browser/provider/built-in/remote.js]: It's not hacks anymore, since I can call `calculateMacSizeLimits` a hack. We need better name for this one \cc @VasilyStrelyaev

File: src/browser/provider/built-in/base.js [hunk 5]
```diff
@@ -80,13 +98,30 @@ export default class BrowserProviderBase {
...
+
     async resizeWindow (browserId, width, height, currentWidth, currentHeight) {
         // TODO: remove once https://github.com/DevExpress/testcafe-browser-tools/issues/12 implemented
         if (OS.linux) {
             this.reportWarning(browserId, WARNING_MESSAGE.browserManipulationsNotSupportedOnLinux);
             return;
         }
 
+        if (OS.mac && exceedsMaxSize(width, height, this.maxAvailableSize[browserId]))
+            throw new Error(MESSAGE.requestedSizeExceedsMaximumSize);
```
Comment (inikulin) [inline src/browser/provider/built-in/base.js]: Throw `APIError` here.

File: src/client/driver/command-executors/prepare-browser-manipulation.js [hunk 6]
```diff
@@ -47,5 +49,14 @@ export default function prepareBrowserManipulation (browserId) {
 
             return delay(RESTORE_DOCUMENT_TITLE_TIMEOUT);
         })
-        .then(() => new DriverStatus({ isCommandResult: true, result }));
+        .then(() => {
+            if (result.isError) {
```
Comment (inikulin) [inline src/client/driver/command-executors/prepare-browser-manipulation.js]: Can't we have early error in `resize` action? We have max available dimensions on startup, can't we check against them before going to client?  Note that it should work in raw API as well

File: src/errors/test-run/index.js [hunk 7]
```diff
@@ -368,3 +368,11 @@ export class SetNativeDialogHandlerCodeWrongTypeError extends TestRunErrorBase {
         this.actualType = actualType;
     }
 }
+
+export class RequestedSizeExceedsMaximumSizeError extends TestRunErrorBase {
```
Comment (inikulin) [inline src/errors/test-run/index.js]: `WindowDimensionsOverflowError`

File: src/errors/test-run/index.js [hunk 8]
```diff
@@ -368,3 +368,11 @@ export class SetNativeDialogHandlerCodeWrongTypeError extends TestRunErrorBase {
...
+    constructor (callsite) {
+        super(TYPE.requestedSizeExceedsMaximumSize);
```
Comment (inikulin) [inline src/errors/test-run/index.js]: `windowDimensionsOverflowError`

File: src/errors/test-run/templates.js [hunk 9]
```diff
@@ -207,5 +207,9 @@ export default {
         Action "${err.selectorName}" argument error:
 
         ${escapeHtml(err.errMsg)}
+    `),
+
+    [TYPE.requestedSizeExceedsMaximumSize]: err => markup(err, `
+        The requested size exceeds the available maximum size.
```
Comment (inikulin) [inline src/errors/test-run/templates.js]: We need better description for this one: we should describe that on MacOS window can't be bigger than screen size, so you can't resize to given dimensions

File: src/test-run/index.js [hunk 10]
```diff
@@ -270,13 +272,43 @@ export default class TestRun extends Session {
...
+    _isValidResize (command) {
+        if (!OS.mac)
+            return true;
+
+        var providerName  = this.browserConnection.browserInfo.providerName;
+        var browserId     = this.browserConnection.id;
+        var provider      = this.browserConnection.provider;
+        var maxScreenSize = provider.maxScreenSizes[browserId];
+
+        if (providerName !== 'remote' && providerName !== 'path' && providerName !== 'locally-installed')
```
Comment (inikulin) [inline src/test-run/index.js]: Why? If I create provider for redistributable chrome that runs on macOs this will not work?

File: src/test-run/index.js [hunk 11]
```diff
@@ -270,13 +272,43 @@ export default class TestRun extends Session {
...
+    static _transformResizeWindowToFitDeviceCommand (command) {
+        var { landscapeWidth, portraitWidth } = getViewportSize(command.device);
+        var portrait = command.options.portraitOrientation;
+        var width    = portrait ? portraitWidth : landscapeWidth;
+        var height   = portrait ? landscapeWidth : portraitWidth;
+
+        return new ResizeWindowCommand({ width, height });
+    }
+
+    _isValidResize (command) {
```
Comment (inikulin) [inline src/test-run/index.js]: `isValidResizeCommandDimensions`

Comment (inikulin) [inline src/test-run/index.js]: Event better move this function to `browserConnection` and name it `canResizeWindowToDimensions (width, height)`

File: src/errors/test-run/templates.js (hunk 9 above)
Comment (VasilyStrelyaev) [inline src/errors/test-run/templates.js]:
```
        Unable to resize the window because the specified size exceeds the screen size. On macOS, a window cannot be larger than the screen.
```

File: src/browser/provider/testcafe-api-bridge.js [hunk 12]
```diff
@@ -0,0 +1,33 @@
+import Promise from 'pinkie';
+import promisifyEvent from 'promisify-event';
+import BrowserConnection from '../connection';
+
+
+export default {
+    runInitScript (browserId, code) {
```
Comment (inikulin) [inline src/browser/provider/testcafe-api-bridge.js]: What is `apiBridge` and why we need it?

**Comment by AndreyBelym** [comment]
FPR

**Comment by inikulin** [comment]
@AndreyBelym We're in code freeze (kinda) now, so I would like to not introduce big changes before release. Let's merge it after release, ok?

**Comment by AndreyBelym** [comment]
Okay

**Comment by inikulin** [comment]
@AndreyBelym It requires rebase. Also, I see that it introduces some new API for browser providers. Can you write s a feature summary in appropriate issues, like https://github.com/DevExpress/testcafe/issues/771 So @VasilyStrelyaev will be aware about what to document. Also, do we need to update existing providers?

**Comment by AndreyBelym** [comment]
All introduced changes are backward-compatible with existing `saucelabs` and `phantomjs` providers, but we have to implement newly supported  functionality.

### maximizeWindow (browserId)
Maximizes the browser window `browserId`.

### canResizeWindowToDimensions(browserId, width, height)
Allows to validate the specified `width` and `height` of browser window `browserId` before the actual resize. The result is `true` if browser window can be resized to the specified dimensions, `false` otherwise.

### hasCustomActionForBrowser(browserId)
Enables feature querying for the specified browser window `browserId`. The function should return an object with the following properties:
`hasResizeWindow` - the browser window supports resizing,
`hasMaximizeWindow` - the browser  window supports maximizing,
`hasTakeScreenshots` - the browser window image can be captured to the file,
`hasCanResizeWindowToDimensions` - the requested window dimensions can be validated before resize.

If a property in the returned object has the `true` value, the provider should have an implemented function with the name corresponding to the property. (e.g. `hasTakeScreenshot` => `takeScreenshot`).

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
\cc @VasilyStrelyaev @AlexanderMoskovkin
