### PR TITLE
Fix test file scanning for Windows (closes #3918)

### LINKED ISSUE #3918: TestCafe can't detect test files located on a Windows network drive
### What is your Test Scenario?
Use test files located on a network drive.  

### What is the Current behavior?
TestCafe says that there is no files.
 
### What is the Expected behavior?
TestCafe should run tests from a network drive.

### Explanation:
We use an old `globby` version for searching test files. It is built upon [isaacs/glob](http://github.com/isaacs/node-glob] that doesn't with network drives. Newer `globby` versions use [fast-glob]() internally, that works well with network drives, but have different search algorithm: `glob` uses a depth-first search algorithm, `fast-glob` uses a width-first search algorithm. If we just update to the latest `globby` version, we can change test execution order. 
 
### Your Environment details:
 
* testcafe version:                   1.2.1
* node.js version:                    10.15.0
* command-line arguments:  testcafe chrome Z:\tests
* browser name and version: any
* platform and version:          Windows
* other:

### PR DESCRIPTION
**Pull request by AndreyBelym**
Closes #3918. Luckily I found a function that allowed me to avoid rewriting half of the `globby` code. Can't write a test for the fixed even with `proxyquire`, because the issue was caused by the internals of `node-glob`.

### CODE REVIEW

File: src/utils/parse-file-list.js [hunk 1]
```diff
@@ -56,12 +59,25 @@ async function convertDirsToGlobs (fileList, baseDir) {
...
 
+async function getFiles (globTask) {
+    const files = await globby(globTask.pattern, globTask.options);
+
+    return files.sort((fileA, fileB) => fileA.localeCompare(fileB));
+}
+
+async function execFileGlobs (globs, baseDir) {
+    const tasks = globby.generateGlobTasks(globs, { cwd: baseDir, expandDirectories: false, onlyFiles: true });
+    const files = await Promise.all(tasks.map(task => getFiles(task)));
```
Comment (kirovboris) [inline src/utils/parse-file-list.js]:
```js
const files = await Promise.all(tasks.map(getFiles));
```

File: src/utils/parse-file-list.js [hunk 2]
```diff
@@ -56,12 +59,25 @@ async function convertDirsToGlobs (fileList, baseDir) {
...
 }
 
+async function getFiles (globTask) {
+    const files = await globby(globTask.pattern, globTask.options);
+
+    return files.sort((fileA, fileB) => fileA.localeCompare(fileB));
+}
+
+async function execFileGlobs (globs, baseDir) {
+    const tasks = globby.generateGlobTasks(globs, { cwd: baseDir, expandDirectories: false, onlyFiles: true });
```
Comment (miherlosev) [inline src/utils/parse-file-list.js]: Please, add a comment described why we need this hack.
