### PR TITLE
Fixed '_waitIdle' method for browser set (closes #271)

### LINKED ISSUE #271: Node shows warning 'Possible memory leak'  during run of few tests .
To reproduce this issue, run next steps:
1. Create TestCafe, a TestCafe runner instance and a browser connection.
2. Establish the browser connection (for example, open connection.url in the local browser or call method ``establish()`` )
3. Run chain 
```js
runner
    .src(...)
    .browsers(...)
    .run() 
 ```
at least 11 times (simultaneously or sequentially, it doesn't matter).

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @inikulin, @AlexanderMoskovkin, @VasilyStrelyaev, @AndreyBelym 
PR

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

File: src/runner/browser-set.js [hunk 1]
```diff
@@ -32,10 +32,18 @@ export default class BrowserSet extends EventEmitter {
...
+
         await Promise.race([
-            promisifyEvent(bc, 'idle'),
-            promisifyEvent(bc, 'closed')
+            idlePromise,
+            closePromise
         ]);
+
+        // We must delete both listeners from browser connection after
+        // execution one of them to avoid overflow subscribers limit.
```
Comment (VasilyStrelyaev) [inline src/runner/browser-set.js]:
```
        // We must delete both listeners from the browser connection after
        // one of them is executed to avoid exceeding the subscribers limit.
```

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

File: src/runner/browser-set.js [hunk 2]
```diff
@@ -32,10 +32,18 @@ export default class BrowserSet extends EventEmitter {
...
+        var closePromise = promisifyEvent(bc, 'closed');
+
         await Promise.race([
-            promisifyEvent(bc, 'idle'),
-            promisifyEvent(bc, 'closed')
+            idlePromise,
+            closePromise
         ]);
+
+        // We must delete both listeners from the browser connection after
```
Comment (inikulin) [inline src/runner/browser-set.js]: Add `NOTE: ` prefix to the comment

**Comment by inikulin** [comment]
\r-

**Comment by georgiy-abbasov** [comment]
fpr

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Comment by AndreyBelym** [comment]
lgtm

**Comment by AndreyBelym** [comment]
I think, it will be nice to have a modification of `Promise.race` that will be automatically cancel pending promises.

**Comment by inikulin** [comment]
@AndreyBelym Do you willing issue a PR to promisifyEvent? =)

**Comment by AndreyBelym** [comment]
Ok, I'll do it sometime.
