### PR TITLE
Fix TS compilation performance (closes #3475)

### LINKED ISSUE #3475: Fix slow TypeScript test compilation time for a large number of tests
### What is your Test Scenario?
Run multiple TypeScript tests in a TestCafe test session.

### What are you suggesting?
Currently, TestCafe compiles TS files using the one-by-one approach, but compilation is significantly faster when done in the all-at-once approach. We should compile all specified test files at once to increase the compilation time.

### PR DESCRIPTION
**Pull request by AndreyBelym**
Closes #3475.

### CODE REVIEW

File: src/compiler/index.js [hunk 1]
```diff
@@ -43,31 +46,76 @@ export default class Compiler {
...
+
+        return await compiler.compile(code, filename);
+    }
 
+    async _compileTestFiles (filenames) {
+        const testFilesInfo = await this._createTestFilesInfo(filenames);
+        const compilerTasks = groupBy(testFilesInfo, ({ compilerName }) => compilerName);
+        const compilerNames = Object.keys(compilerTasks);
+
+        await Promise.all(compilerNames.map(compilerName => this._precompileFiles(testFileCompilersRegistry[compilerName], compilerTasks[compilerName])));
```
Comment (AlexKamaev) [inline src/compiler/index.js]: we already have `testFilesInfo` here which contains `compiler`. Can we get rid of `testFileCompilersRegistry`?
