### PR TITLE
fix: Native automation - Do not generate a char for hotkey combinations (closes #7680)

### LINKED ISSUE #7680: Native Automation: The "Ctrl+S" key combination produces the event.text property
### What is your Scenario?

Simulate the "Ctrl+S" key combination.

### What is the Current behavior?

It produces an event with the `text: "s"` property. Puppeteer does not. For example:

TestCafe:
image

Puppeteer:
image

image

### What is the Expected behavior?

It should not produce "text" property.

### What is your public website URL? (or attach your complete example)

example.com

### What is your TestCafe test code?

fixture`Fixture`.page`example.com`;

test('Test', async t => {
    await t.pressKey('Ctrl+s');
});

### Your complete configuration file

_No response_

### Your complete test report

_No response_

### Screenshots

_No response_

### Steps to Reproduce

1. Add console.log(options); in line 28 in the following file: node_modules\testcafe\lib\native-automation\utils\cdp.js:
image

2. Run the test.
3. See the event options in Console.

### TestCafe version

2.5.1-rc.1

### Node.js version

_No response_

### Command-line arguments

npx testcafe chrome test.js --native-automation

### Browser name(s) and version(s)

_No response_

### Platform(s) and version(s)

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by Dmitry-Ostashev**
## Purpose
For example, the `await t.pressKey('Ctrl+s')` action produces the 's' char in the input field. This behavior is incorrect.

## Approach
Do not produce a char when a modified Ctrl or Alt is enabled.

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

File: src/native-automation/client/event-descriptor.ts [hunk 1]
```diff
@@ -69,7 +70,7 @@ export default class CDPEventDescriptor {
         if (options.isNewLine)
             return '\r';
 
-        if (options.keyProperty.length === 1)
+        if (options.keyProperty.length === 1 && ![KeyModifierValues.ctrl, KeyModifierValues.alt, KeyModifierValues.meta].includes(options.modifiers))
```
Comment (miherlosev) [inline src/native-automation/client/event-descriptor.ts:73]: Please add the `Array.prototype.includes` method to the [native methods](https://github.com/DevExpress/testcafe-hammerhead/blob/b10bd8c688bdce0e25d8e33278bb3899dd274c2c/src/client/sandbox/native-methods.ts#L186) and use it here.

Also put this condition to the separate function:
```js
private static _getKeyDownEventText (options: SimulatedKeyInfo): any {
    if (options.isNewLine)
        return '\r';

    if (this._keyModifier(options)
        return options.keyProperty;
    ...
}

```

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by miherlosev — APPROVED** [review]
