### PR TITLE
Fix windows handling for IE (closes #559)

### LINKED ISSUE #559: IE cuts the page url if it is assigned to title
Since the release of `testcafe-browser-natives@0.11.0` we use general approach when searching for IE windows, and do it by enumerating window titles. It caused failures of screenshot functional tests, because we are still putting page URLs to the window title, and unfortunately IE cuts them if they are too long. As an example for the screenshot test
url was
`http://127.0.0.1:2000/sj5drnbq/http://localhost:3000/api/es-next/take-screenshot/pages/index.html `
and title was:
`[ http://127.0.0.1:2000/sj5drnbq/http://localhost:3000/api/es-next/take-screenshot/pages/index. - internet explorer`
`html` part of URL was missing.

So I propose to put `TestRunId` in window title instead of page url. What do @inikulin, @helen-dikareva think about it?

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @inikulin, @AlexanderMoskovkin, @helen-dikareva

### CODE REVIEW

File: src/client/driver/command-executors/prepare-browser-manipulation.js [hunk 1]
```diff
@@ -27,13 +27,13 @@ export default function prepareBrowserManipulation () {
...
-    document.title = assignedTitle;
+    document.title = testRunId;
 
     return delay(APPLY_DOCUMENT_TITLE_TIMEOUT)
         .then(() => {
             var message = {
-                cmd:     MESSAGE.readyForBrowserManipulation,
-                pageUrl: document.location.toString()
+                cmd:   MESSAGE.readyForBrowserManipulation,
+                title: testRunId
```
Comment (helen-dikareva) [inline src/client/driver/command-executors/prepare-browser-manipulation.js]: We can do not send it, because we have `testRunId` on server side

File: src/client/runner/runner.js [hunk 2]
```diff
@@ -140,7 +141,7 @@ Runner.prototype._reportErrorToServer = function (err, isAssertion) {
 Runner.prototype._onTestError = function (err, isAssertion) {
     // NOTE: we should not create multiple screenshots for a step. Create a screenshot if
     // it's the first error at this step or it's an error that occurs on page initialization.
-    err.pageUrl = document.location.toString();
+    err.title = this.testRunId;
```
Comment (helen-dikareva) [inline src/client/runner/runner.js]: It's seem like we need `pageUrl` to create error message in some case

Comment (AndreyBelym) [inline src/client/runner/runner.js]: Needed property is called `pageDestUrl`. https://github.com/DevExpress/testcafe/blob/master/src/client/runner/runner-base.js#L72, used in https://github.com/DevExpress/testcafe/blob/master/src/legacy/test-run-error/templates.js#L107

Comment (inikulin) [inline src/client/runner/runner.js]: > It's seem like we need pageUrl to create error message in some case

I don't get it. In which cases?

File: src/client/runner/runner.js [hunk 3]
```diff
@@ -213,7 +214,7 @@ Runner.prototype._onTakeScreenshot = function (e) {
             return new Promise(resolve => {
                 var msg = {
                     cmd:        COMMAND.takeScreenshot,
-                    pageUrl:    document.location.toString(),
+                    title:      this.testRunId,
```
Comment (inikulin) [inline src/client/runner/runner.js]: `title` -> `windowId`

File: src/runner/screenshots/capturer.js [hunk 4]
```diff
@@ -18,31 +18,31 @@ export default class Capturer {
         return `${stepName && stepName.replace(/\s|\\|\/|"|\*|\?|<|>|\|/g, '_') || 'page-load'}.png`;
     }
 
-    async _takeScreenshot (url, filePath) {
+    async _takeScreenshot (title, filePath) {
```
Comment (inikulin) [inline src/runner/screenshots/capturer.js]: `title` -> `windowId`

**Comment by helen-dikareva** [comment]
lgtm

**Comment by AndreyBelym** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm
