### PR TITLE
Fix error handling on beforeunload (closes #329)

### LINKED ISSUE #329: Missing errors raised on beforeunload event
If you have unexpected beforeunload dialog, or expected beforeunload dialog did not appear, no error will be reported since [my last commit](https://github.com/DevExpress/testcafe/commit/f0043dcee3d7db526edff9943e98c96450230103), which changed the way we handle error occuring on beforeunload event: instead of sending it to server and embedding in `task.js` template, it is saved in `TestContextStorage` now. 

Due to implementation of `TestContextStorage`, when you store a variable in it, it does'nt saved to `sessionStorage` immediatelly, but only when beforeunload event occurs. Unfortunately, `TestContextStorage` subscribes to the event before we are checking beforeunload dialog and raise an error, so the error will be stored after contents of `TestContextStorage` has saved in `sessionStorage`, and will not be saved after page reload.

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @inikulin @AlexanderMoskovkin @georgiy-abbasov

### CODE REVIEW

File: src/client/runner/runner.js [hunk 1]
```diff
@@ -167,7 +161,7 @@ Runner.prototype._onTestError = function (err, isAssertion) {
     return errorProcessingChain;
 };
 
-Runner.prototype._onFatalError = function (err) {
+Runner.prototype._onFatalError = function (err, isSavedError) {
```
Comment (AlexanderMoskovkin) [inline src/client/runner/runner.js]: I don't like the `isSavedError` argument because I can't get what does it mean without reading long notes and understanding `beforeunload event handler` logic.
Also we have to duplicate stepName escaping with this approach:
https://github.com/DevExpress/testcafe/pull/330/files#diff-619aff4845280917d61f0dfe5e1a6071R179
https://github.com/DevExpress/testcafe/pull/330/files#diff-619aff4845280917d61f0dfe5e1a6071R149

I suppose we should call `this._reportErrorToServer` from `this._onTestError` only. So we can do the following:
```js
//Runner.prototype._onFatalError = function (err) {
if (beforeUnloadRaised) {
        err.skipScreenshot = true;
        this.testContextStorage.setProperty('testError', err);
} else {
    this
        ._onTestError(err)
        .then(Runner.checkStatus);
}
```

```js
//Runner.prototype._onTestError = function (err, isAssertion) {
err.screenshotRequired = !err.skipScreenshot && SETTINGS.get()....
```

File: test/functional/fixtures/runner/browser-dialogs/base-page.html [hunk 2]
```diff
@@ -0,0 +1,33 @@
+<!DOCTYPE html>
+<html>
+<head>
+    <title>Index</title>
+    <script src="/jquery"></script>
+
+    <style type="text/css">
+        body {
+            padding: 100px 0 0 300px; /* move out content from recorder tooltip */
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/runner/browser-dialogs/base-page.html]: remove this since we don't have recorder here

File: test/functional/fixtures/runner/browser-dialogs/base-page.html [hunk 3]
```diff
@@ -0,0 +1,33 @@
+<!DOCTYPE html>
+<html>
+<head>
+    <title>Index</title>
+    <script src="/jquery"></script>
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/runner/browser-dialogs/base-page.html]: we don't use jquery here and can remove this line

File: test/functional/fixtures/runner/browser-dialogs/base-page.html [hunk 4]
```diff
@@ -0,0 +1,33 @@
+<!DOCTYPE html>
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/runner/browser-dialogs/base-page.html]: we can name it `browser-dialogs/index.html`

File: test/functional/fixtures/runner/browser-dialogs/basepage.test.js [hunk 5]
```diff
@@ -0,0 +1,31 @@
+'@fixture basePage';
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/runner/browser-dialogs/basepage.test.js]: I'd like to rename the file to `before-unload-diaog.test.js` if we will create separate files for other dialogs or `index.test.js` (if we will have just one test file here)

File: test/functional/fixtures/runner/browser-dialogs/native-dialogs-in-cross-domain-iframes-test.js [hunk 6]
```diff
@@ -0,0 +1,34 @@
+var expect = require('chai').expect;
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/runner/browser-dialogs/native-dialogs-in-cross-domain-iframes-test.js]: The filename is incorrect (`native-dialogs-in-cross-domain-iframes-test.js`). We don't test iframes here yet. Use the same name as for the `.test.js` file above

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by georgiy-abbasov** [comment]
@AndreyBelym, lgtm. Thanks for explanation.

**Comment by AlexanderMoskovkin** [comment]
lgtm
@VasilyStrelyaev please check comments and strings

**Comment by AlexanderMoskovkin** [comment]
@MargaritaLoseva please check comments and strings

File: src/client/runner/runner.js [hunk 7]
```diff
@@ -83,13 +83,13 @@ Runner.prototype._onNextStepStarted = function (e) {
 Runner.prototype._onActionTargetWaitingStarted = function (e) {
```
Comment (MargaritaLoseva) [inline src/client/runner/runner.js]: https://github.com/DevExpress/testcafe/pull/330/files#diff-619aff4845280917d61f0dfe5e1a6071R82
Replace with: 
//NOTE: decrease the step counter if the action restarts while waiting for an element to be available (T230851)

File: src/client/runner/runner.js [hunk 8]
```diff
@@ -176,8 +172,18 @@ Runner.prototype._onFatalError = function (err) {
 
     RunnerBase.prototype._onFatalError.call(this, err);
 
-    this._onTestError(err)
-        .then(Runner.checkStatus);
+    // NOTE: we should not stop the test run if an error occured during page unloading because we
```
Comment (MargaritaLoseva) [inline src/client/runner/runner.js]: Replace with:
"// NOTE: we should not stop the test running if an error occurs during page unload. As a result, we
// would destroy the session and wouldn't be able to get the next page in the browser.
// We have to set the deferred error to the task to have the test fail after page reload."

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js [hunk 9]
```diff
@@ -0,0 +1,34 @@
+var expect = require('chai').expect;
+
+describe('Native dialogs handling', function () {
+    it('Should succeed when expected before unload dialog appeared', function () {
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: Replace the text with "passes when the expected beforeUnload dialog appears"

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js [hunk 10]
```diff
@@ -0,0 +1,34 @@
...
+        return runTests('before-unload-dialog.test.js', 'Before unload dialog - should succeed')
+            .then(function (err) {
+                expect(err).eql('');
+            });
+    });
+
+    it('Should fail when expected before unload dialog did not appear', function () {
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: Replace the text with "fails if the expected beforeUnload dialog does not appear"

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js [hunk 11]
```diff
@@ -0,0 +1,34 @@
...
+                var expectedError = [
+                    'Error at step "1.Click link "This page"":',
+                    ' The expected system beforeUnload dialog did not appear.'
+                ].join('');
+
+                expect(err).eql(expectedError);
+            });
+    });
+
+    it('Should fail when unexpected before unload dialog appeared', function () {
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: Replace the text with "fails if the unexpected beforeUnload dialog appears"

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js [hunk 12]
```diff
@@ -0,0 +1,34 @@
...
+        return runTests('before-unload-dialog.test.js', 'Unexpected before unload dialog - should be failed', { shouldFail: true })
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: > Unexpected before unload dialog - should be failed
Replace with "An unexpected beforeUnload dialog. The check fails."

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js [hunk 13]
```diff
@@ -0,0 +1,34 @@
...
+describe('Native dialogs handling', function () {
+    it('Should succeed when expected before unload dialog appeared', function () {
+        return runTests('before-unload-dialog.test.js', 'Before unload dialog - should succeed')
+            .then(function (err) {
+                expect(err).eql('');
+            });
+    });
+
+    it('Should fail when expected before unload dialog did not appear', function () {
+        return runTests('before-unload-dialog.test.js', 'No expected before unload dialog - should be failed', { shouldFail: true })
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: > No expected before unload dialog - should be failed

Replace with "The expected beforeUnload dialog does not appear. The check fails."

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js [hunk 14]
```diff
@@ -0,0 +1,34 @@
+var expect = require('chai').expect;
+
+describe('Native dialogs handling', function () {
+    it('Should succeed when expected before unload dialog appeared', function () {
+        return runTests('before-unload-dialog.test.js', 'Before unload dialog - should succeed')
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: > Before unload dialog - should succeed

Replace with: "The expected beforeUnload dialog. The check has passed."

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js [hunk 15]
```diff
@@ -0,0 +1,34 @@
...
+                expect(err).eql('');
+            });
+    });
+
+    it('Should fail when expected before unload dialog did not appear', function () {
+        return runTests('before-unload-dialog.test.js', 'No expected before unload dialog - should be failed', { shouldFail: true })
+            .catch(function (err) {
+                var expectedError = [
+                    'Error at step "1.Click link "This page"":',
+                    ' The expected system beforeUnload dialog did not appear.'
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: > The expected system beforeUnload dialog did not appear.

The expected beforeUnload system dialog has not appeared.

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js [hunk 16]
```diff
@@ -0,0 +1,34 @@
...
+                expect(err).eql(expectedError);
+            });
+    });
+
+    it('Should fail when unexpected before unload dialog appeared', function () {
+        return runTests('before-unload-dialog.test.js', 'Unexpected before unload dialog - should be failed', { shouldFail: true })
+            .catch(function (err) {
+                var expectedError = [
+                    'Error at step "2.Click link "This page"":',
+                    ' Unexpected system beforeUnload dialog message appeared.'
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: >   ' Unexpected system beforeUnload dialog message appeared.'

  An unexpected beforeUnload system dialog has appeared.'

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog.test.js [hunk 17]
```diff
@@ -0,0 +1,31 @@
+'@fixture before-unload-dialog';
+'@page ./index.html';
+
+
+'@test'['Before unload dialog - should succeed'] = {
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog.test.js]: Replace with "The expected beforeUnload dialog. The test should pass."

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog.test.js [hunk 18]
```diff
@@ -0,0 +1,31 @@
...
+        act.click('#enableBeforeUnload');
+    },
+
+    '2.Click link "This page"': function () {
+        handleBeforeUnload();
+        act.click(':containsExcludeChildren(This page)');
+    }
+};
+
+'@test'['Unexpected before unload dialog - should be failed'] = {
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog.test.js]: Replace with "An unexpected beforeUnload dialog. The test should fail."

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog.test.js [hunk 19]
```diff
@@ -0,0 +1,31 @@
...
+    '1.Click submit button "Enable..."': function () {
+        act.click('#enableBeforeUnload');
+    },
+
+    '2.Click link "This page"': function () {
+        act.click(':containsExcludeChildren(This page)');
+    }
+};
+
+'@test'['No expected before unload dialog - should be failed'] = {
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog.test.js]: Replace with "The expected beforeUnload dialog does not appear. The test should fail."

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js (hunk 15 above)
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: @MargaritaLoseva This error template was reviewed before when it was commited, It's defined [here](https://github.com/DevExpress/testcafe/blob/master/src/reporter/errors/templates.js#L209).  @AndreyBelym just use it here. So, I propose to don't change it in this pr. If you would like to correct them we can create a separate issue to discuss this.

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js (hunk 16 above)
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: The same as above

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js (hunk 12 above)
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: All of our server test names have the following structure: `it('Should <do smthg>')` (Please see, `test/server/*-test.js` files in our repo). Maybe we should keep this template here too?
/cc @MargaritaLoseva @inikulin

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js (hunk 11 above)
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: All of our server test names have the following structure: `it('Should <do smthg>')` (Please see, `test/server/*-test.js` files in our repo). Maybe we should keep this template here too?
/cc @MargaritaLoseva @inikulin

Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: Correctors said that should can be used as well. Let's use "should". I'll update my comments.

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js [hunk 20]
```diff
@@ -0,0 +1,34 @@
+var expect = require('chai').expect;
+
+describe('Native dialogs handling', function () {
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: > Native dialogs handling

Replace with "Handling native dialogs"

File: test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js (hunk 15 above)
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js]: Ok, let's use the variant that was earlier. Don't mind my previous comment.

**Comment by MargaritaLoseva** [comment]
I've updated my comments.

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by MargaritaLoseva** [comment]
lgtm

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm
