### PR TITLE
Make CLI video options undefined if they're not specified (closes #3415)

### LINKED ISSUE #3415: videoOptions option is ignored
### What is your Test Scenario?
Run test with ` "testcafe -c 2 chrome tests/fixtures/**/*.spec.ts --env=pre --selector-timeout 10000 "`
Save video capture to the path pattern provided in `.testcaferc.json` 
### What is the Current behavior?
`videoOptions` option from the configuration file is ignored 
### What is the Expected behavior?
Save video capture to the path pattern provided in `.testcaferc.json` 
### What is your web application and your TestCafe test code?

<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

fixture`Getting Started`.page`http://devexpress.github.io/testcafe/example`;

test('My first test', async (t) => {
  await t.typeText('#developer-name', 'John Smith').click('#submit-button');
});

```
```json

{
  "videoPath": "reports/screen-captures",
  "videoOptions": {
    "singleFile": false,
    "failedOnly": false,
    "pathPattern": "${FIXTURE}/${TEST}/${USERAGENT}/${FILE_INDEX}.mp4"
  }
}
```
</details>

<details>
<summary>Your complete test report:</summary>

```
npm run test                                                                                                                                               

> e2e_smart@1.0.0 test /X/e2e_smart
> testcafe -c 2 chrome tests/fixtures/**/*.spec.ts --env=pre --selector-timeout 10000 

The "videoOptions" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 71.0.3578 / Linux 0.0.0

 Getting Started
 ✓ My first test
```
</details>

<details>

### Steps to Reproduce:

1. Run test with ` "testcafe -c 2 chrome tests/fixtures/**/*.spec.ts --env=pre --selector-timeout 10000 "`
2. Video saved in different folder
 
image

### Your Environment details:
 
* testcafe version:                   1.0.0
* node.js version:                    v10.15.0
* command-line arguments: testcafe -c 2 chrome tests/fixtures/**/*.spec.ts --env=pre --selector-timeout 10000
* browser name and version: Chrome 71
* platform and version:          Linux

### PR DESCRIPTION
**Pull request by AndreyBelym**
Closes #3415.

### CODE REVIEW

File: src/cli/argument-parser.js [hunk 1]
```diff
@@ -203,8 +203,11 @@ export default class CLIArgumentParser {
     }
 
     async _parseVideoOptions () {
-        this.opts.videoOptions         = typeof this.opts.videoOptions === 'string' ? await getVideoOptions(this.opts.videoOptions) : null;
-        this.opts.videoEncodingOptions = typeof this.opts.videoEncodingOptions === 'string' ? await getVideoOptions(this.opts.videoEncodingOptions) : null;
+        if (this.opts.videoOptions)
+            this.opts.videoOptions = await getVideoOptions(this.opts.videoOptions);
+
+        if (this.opts.videoEncodingOptions)
```
Comment (miherlosev) [inline src/cli/argument-parser.js]: Raise an error if video encoding options were specified without video options.

Comment (AndreyBelym) [reply src/cli/argument-parser.js]: It's already done: https://github.com/DevExpress/testcafe/blob/master/src/runner/index.js#L241
