### PR TITLE
Fix Headless Firefox resize (closes #1825)

### LINKED ISSUE #1825: Test with resize fails on firefox:headless
```javascript
import { ClientFunction } from 'testcafe';

fixture `My fixture`
    .page `https://testcafe.devexpress.com/Example/`;

const getWindowProperty = new ClientFunction(propName => window[propName]);

test('test', async t => {
    await t
        .resizeWindow(600, 400)
        .expect(getWindowProperty('innerWidth')).eql(600)
        .expect(getWindowProperty('innerHeight')).eql(400);
});
```
 AssertionError: expected 617 to deeply equal 600

 Browser: Firefox 56.0.0 / Windows 8.1 0.0.0

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @LavrovArtem @helen-dikareva

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

File: src/browser/provider/built-in/firefox/marionette-client.js [hunk 1]
```diff
@@ -8,9 +8,10 @@ import delay from '../../../../utils/delay';
 
 const CONNECTION_READY_TIMEOUT   = 300;
 const MAX_CONNECTION_RETRY_COUNT = 10;
+const MAX_RESIZE_RETRY_COUNT     = 5;
 const HEADER_SEPARATOR           = ':';
 
-const GET_PAGE_SIZE_SCRIPT = 'return {width:document.documentElement.clientWidth, height: document.documentElement.clientHeight}';
```
Comment (LavrovArtem) [inline src/browser/provider/built-in/firefox/marionette-client.js]: I think the [getWindowDimensionsInfo](https://github.com/DevExpress/testcafe/blob/master/src/browser/provider/built-in/chrome/index.js#L9) function must be shared and used in this place.
