### PR TITLE
Make testCafe.close wait until connections are closed (closes #216)

### LINKED ISSUE #216: TestCafe.close() issue
The process is still hanging after the gulp task is finished.

To reproduce this issue, create a gulp task that:
1. Creates TestCafe, a TestCafe runner instance and a browser connection.
2. Establishes the browser connection (for example, opens connection.url in the local browser)
3. Closes TestCafe.

After closing TestCafe and finishing the task, the node process is still hanging for about 2 minutes, which is equivalent to the HEARTBEAT_TIMEOUT value.

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @AlexanderMoskovkin @georgiy-abbasov

### CODE REVIEW

File: src/runner/index.js [hunk 1]
```diff
@@ -14,6 +14,8 @@ export default class Runner extends EventEmitter {
 
         this.proxy        = proxy;
         this.bootstrapper = new Bootstrapper(browserConnectionGateway);
+        this.task         = null;
+        this.browserSet   = null;
```
Comment (inikulin) [inline src/runner/index.js]: We can't do this. Runner can spawn more than one task simultaneously.

**Comment by inikulin** [comment]
\r-

File: src/testcafe.js [hunk 2]
```diff
@@ -42,10 +45,18 @@ export default class TestCafe {
...
+
+        this.runners.push(newRunner);
+        promisifyEvent(newRunner, 'stopped').then(() => remove(this.runners, newRunner));
+
+        return newRunner;
     }
 
-    close () {
+    async close () {
+        await Promise.all(this.runners.slice().map(runner => runner.stop()));
```
Comment (AlexanderMoskovkin) [inline src/testcafe.js]: @inikulin I suppose we should not force stopping of all current runners in the `testcafe.close()` method. We should only close opened `browserConnections` (to clear heartbeat timeouts) and close the `proxy` to avoid node process hanging. Or I'm wrong?

Comment (inikulin) [inline src/testcafe.js]: Well, the best way will be to stop by gracefully shutting everything down. I think we should start from other point. For `testcafe-studio` we will need ability to `cancel` task Promise which is returned by the `runner.run()`. So we need to extend this Promise with the `cancel()` method which will behave like if we have fatal run error: aborts tasks and gracefully closes remaining unused connection. So, if we we'll implement it, we can have `pendingTaskPromises` array in `runner`, so testcafe will just `cancel` all such Promises in all active tasks and then just `close` proxy. \cc @AndreyBelym

Comment (AndreyBelym) [inline src/testcafe.js]: OK, got it.

Comment (inikulin) [inline src/testcafe.js]: We need a separate issue and PR for `taskPromise.cancel()` BTW.

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
FPR

File: src/utils/promise-finally.js [hunk 3]
```diff
@@ -0,0 +1,13 @@
+export default function (promise, onFinally) {
```
Comment (inikulin) [inline src/utils/promise-finally.js]: Refactor it's to the external micromodule and don't return the promise, it will make code much cleaner:
```js
var promise = createPromise();

onceDone(promise, doSomething);
```

File: src/runner/index.js [hunk 4]
```diff
@@ -126,6 +137,10 @@ export default class Runner extends EventEmitter {
                 return this._runTask(reporterPlugin, browserSet, tests);
             });
 
-        return Runner._createCancelablePromise(runTaskPromise);
+        return this._createCancelablePromise(runTaskPromise);
+    }
+
+    async stop () {
+        await Promise.all(this.pendingTaskPromises.slice().map(taskPromise => taskPromise.cancel()));
```
Comment (inikulin) [inline src/runner/index.js]: To complicated. Refactor it by introducing intermidiate vars

File: src/runner/index.js [hunk 5]
```diff
@@ -31,11 +34,20 @@ export default class Runner extends EventEmitter {
         await browserSet.dispose();
     }
 
-    static _createCancelablePromise (taskPromise) {
-        var promise = taskPromise.then(({ completionPromise }) => completionPromise);
+    _createCancelablePromise (taskPromise) {
+        var promise           = null;
+        var removeTaskPromise = () => remove(this.pendingTaskPromises, promise);
```
Comment (inikulin) [inline src/runner/index.js]: Rename to `removeFromPending` maybe

File: src/runner/index.js (hunk 4 above)
Comment (inikulin) [inline src/runner/index.js]: We need a comment about `slice` as well. This is not quite ovbious thing, so we need to describe it (see BrowserSet)

**Comment by inikulin** [comment]
\r-

File: src/runner/index.js (hunk 4 above)
Comment (AndreyBelym) [inline src/runner/index.js]: I have figured out how we can get rid of that nasty `slice()`'s: ES6 `for..of` loop uses Array iterator, that observes changes in array. So it's possible to remove and even insert elements with `splice()` when iterating.

File: src/utils/promise-finally.js (hunk 3 above)
Comment (AndreyBelym) [inline src/utils/promise-finally.js]: Maybe it would be better to take code from proposal of [Promise.prototype.finally](https://gist.github.com/rbuckton/66918c8491aa335b003c) and rewrite is as independent function?
Proposal:
```
Promise.prototype.finally = function (callback) {
    return this.then(
        value => this.constructor.resolve(callback()).then(() => value),
        reason => this.constructor.resolve(callback()).then(() => this.constructor.reject(reason))
    );
};
```

Free function:
```
function finally (promise, callback) {
    return promise.then(
        value => promise.constructor.resolve(callback()).then(() => value),
        reason => promise.constructor.resolve(callback()).then(() => promise.constructor.reject(reason))
    );
};
```

Comment (AndreyBelym) [inline src/utils/promise-finally.js]: Argh, without ES6 features it will not be so elegant.

Comment (inikulin) [inline src/utils/promise-finally.js]: I like free function implementation

File: src/runner/index.js (hunk 4 above)
Comment (inikulin) [inline src/runner/index.js]: Nice!

Comment (AndreyBelym) [inline src/runner/index.js]: Unfortunately, I have realized that `for..of` doesn't iterate over an element that is next to deleted one. So when trying to do
```
var a = [1,2,3,4,5,6]; 
for(var x of a) 
    a.splice(a,indexOf(x), 1);
```
`a` will be equal to `[2,4,6]`.

Comment (inikulin) [inline src/runner/index.js]: Let's keep slice then

**Comment by AndreyBelym** [comment]
New modules: [onceDone](https://github.com/AndreyBelym/once-done) and [mapReverse](https://github.com/AndreyBelym/map-reverse).

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

File: src/runner/index.js [hunk 6]
```diff
@@ -126,6 +133,14 @@ export default class Runner extends EventEmitter {
...
             });
 
-        return Runner._createCancelablePromise(runTaskPromise);
+        return this._createCancelablePromise(runTaskPromise);
+    }
+
+    async stop () {
+        // NOTE: When taskPromise is cancelled it is removed from pendingTaskPromises array, that leads to shifting indexes
+        // to the beginning. So in order to iterate the array we must copy it, or perform iteration from the end to beginning.
+        var cancellationPromises = mapReverse(this.pendingTaskPromises, taskPromise => taskPromise.cancel());
```
Comment (inikulin) [inline src/runner/index.js]: Can you do the same for the BrowserSet in context of this PR, pls?

**Comment by inikulin** [comment]
lgtm, just add BrowserSet update pls

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm
/cc @VasilyStrelyaev please, check comments

File: src/runner/browser-set.js [hunk 7]
```diff
@@ -120,11 +121,9 @@ export default class BrowserSet extends EventEmitter {
     }
 
     async dispose () {
-        // FIXME: make a shallow copy of `this.connections`, because it
-        // will be modified inside `releaseConnection`.
-        // Not the most clear piece of code here. I hope we can do
-        // better. But I'm out of ideas for now.
-        this.connections.slice().forEach(bc => this.releaseConnection(bc));
+        // NOTE: When taskPromise is cancelled it is removed from pendingTaskPromises array, that leads to shifting indexes
+        // to the beginning. So in order to iterate the array we must copy it, or perform iteration from the end to beginning.
```
Comment (inikulin) [inline src/runner/browser-set.js]: Can we keep original formatting of the comment? It's hard to read, when it's that long.

Comment (VasilyStrelyaev) [inline src/runner/browser-set.js]:
```
        // NOTE: When taskPromise is cancelled, it is removed from the pendingTaskPromises array, which leads to shifting indexes
        // towards the beginning. So, we must copy the array in order to iterate it, or we can perform iteration from the end to the beginning.
```

File: src/runner/index.js (hunk 6 above)
Comment (VasilyStrelyaev) [inline src/runner/index.js]:
```
        // NOTE: When taskPromise is cancelled, it is removed from the pendingTaskPromises array, which leads to shifting indexes
        // towards the beginning. So, we must copy the array in order to iterate it, or we can perform iteration from the end to the beginning.
```

**Comment by VasilyStrelyaev** [comment]
\r-

**Comment by AndreyBelym** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm
