### PR TITLE
fix: throw error and provide original error details to read/parse config errors and attach reporter error(closes #7208, #6437) 

### LINKED ISSUE #7208: TestCafe hides errors thrown in the `.testcaferc.js` file
### What is your Scenario?

Running tests with a configuration file that should throw an error.

### What is the Current behavior?

TestCafe hides the real error and instead shows: `ERROR You have not specified a browser`.

### What is the Expected behavior?

TestCafe should show the real error.

### Your complete configuration file

```js
throw new Error('Do not hide this Error!');

module.exports = {
    browsers: ['chrome', 'firefox']
};
```

### Your complete test report

```
An error has occurred while reading the "C:\Users\admin\TestCafeStudio\Examples\003\.testcaferc.js" configuration file.
ERROR You have not specified a browser.
```

### Steps to Reproduce

1. Create `.testcaferc.js` which throws an error.
2. Run in console: `testcafe`.

### TestCafe version

1.20.0

### Node.js version

18.5.0

### Command-line arguments

`testcafe`

### PR DESCRIPTION
**Pull request by Artem-Babich**
## Purpose
#7208
#6437

When an error occurs during reading the config file you need to know more details about this error. Especially in JS config file.
The same is for the require('testcafe-reporter-name'). Or even custom reporter code.

## Approach
Provide original error message and formatted stack.

## Breaking Change
**Old behavior:** 
Config file reading or parsing error doesn't stop the test run and only a warning is shown.

**New behavior:** 
Config file reading or parsing error stops the test run and a formatted error message is shown.

## References
#7208
#6437

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [x] Make sure that existing tests do not fail

### CODE REVIEW

File: src/errors/runtime/index.js [hunk 1]
```diff
@@ -9,7 +9,18 @@ import util from 'util';
 import semver from 'semver';
 import { removePreventModuleCachingSuffix } from '../test-run/utils';
 
-const ERROR_SEPARATOR = '\n\n';
+const ERROR_SEPARATOR        = '\n\n';
+const NO_STACK_AVAILABLE_MSG = 'No stack trace available for this error';
+const MODULE_NOT_FOUND_CODE  = 'MODULE_NOT_FOUND';
+const REPORTER_MODULE_PREFIX = 'testcafe-reporter-';
```
Comment (miherlosev) [inline src/errors/runtime/index.js:15]: Move to the separate `/report/prefix.ts` file and reuse here and [here](https://github.com/DevExpress/testcafe/pull/7759/files#diff-ae666665181ee43a04b6e756d3f8fbd260352222e8942b31d0ec501187b57d30R5).

File: src/errors/runtime/index.js [hunk 2]
```diff
@@ -187,3 +198,53 @@ export class ImportESMInCommonJSError extends GeneralError {
...
+
+        return name;
+    }
+
+    static _getReporterModuleNotFoundMessage (reporterModuleName) {
+        return `Cannot find module "${reporterModuleName}"`;
+    }
+
+    static _getFormattedMessage (originalError, reporterFullName) {
+        const isModuleNotFoundError    = originalError.code && originalError.code === MODULE_NOT_FOUND_CODE;
```
Comment (miherlosev) [inline src/errors/runtime/index.js:235]: Remove extra spaces

File: src/errors/runtime/index.js [hunk 3]
```diff
@@ -187,3 +198,53 @@ export class ImportESMInCommonJSError extends GeneralError {
...
+
+    static _getFormattedMessage (originalError, renderCallsite) {
+        if (!renderCallsite)
+            return originalError.message;
+
+        return formatErrorWithCallsite(originalError);
+    }
+}
+
+export class AttachReporterError extends GeneralError {
```
Comment (miherlosev) [inline src/errors/runtime/index.js:215]: Rename to `LoadReporterError`

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by miherlosev — APPROVED** [review]
