### PR TITLE
fix: fixed hanging in NA if url has hash

### LINKED ISSUE #7652: testcafe just stops/hangs with nativeAutomation true
### What is your Scenario?

i'm testing a Vue3 application. Without nativeAutomation everything runs fine (the tests i mean)
If i turn on NativeAutomation, the tests just stops, or hangs or just doesn't do anything.

There are no errors, no warnings in the output of testcafe, nor in the console of the browser. It just 'stops'. it seems like the expect doesn't signal to the test that it is finished.

As you can see in below example, i get the console.logs a and b, but never c. the browser just sits there. Also no timeout errors. just ...nothing...

I cannot create a sample repo as it is internal app. but i would like to have hints or tips on what i can turn on to get more info or debug info? I tried debugMode, and it stops at the first expect, upon resuming it has the same behaviour: it just stops

### What is the Current behavior?

test run just hangs

### What is the Expected behavior?

run to the finish

### What is your public website URL? (or attach your complete example)

internal app.

### What is your TestCafe test code?

import RequestTravellerInfo from '../pageModels/RequestTravellerInfo';

fixture('Request traveller info page')
  .page(RequestTravellerInfo.pageURL)

test('The request-traveller-info page should show the correct title', async (testController) => {
  console.log('do i get here?','a');//yes
  await testController
    .expect(RequestTravellerInfo.title.innerText)
    .contains('Warp tickets');
  console.log('do i get here?','b');//yes
  await testController
    .expect(RequestTravellerInfo.title.innerText)
    .contains('Warp tickets');
});

test('The user should be able to fill in the inputfield firstname', async (testController) => {
  console.log('do i get here?','c');//NO!!
  await testController
    .typeText(RequestTravellerInfo.firstNameInput, 'Spock')
    .expect(RequestTravellerInfo.firstNameInput.value).eql('Spock');
});

### Your complete configuration file

{
    "browsers": [
        "chrome"
    ],
    "src": "./tests/functional/**/*.cspec.js",
    "hostname": "localhost",
    "reporter": [
        {
            "name": "spec"
        },
        {
            "name": "html",
            "output": "./tests/functional/reports/html/index.html"
        },
        {
            "name": "xunit",
            "output": "./tests/functional/reports/report.xml"
        }
    ],
    "screenshots": {
        "takeOnFails": true,
        "path": "./tests/screenshots",
        "fullPage": true,
        "pathPattern": "${FIXTURE}/${TEST}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png"
    },
    "pageLoadTimeout": 10000,
    "clientScripts": [
        {
            "module": "axe-core/axe.min.js"
        }
    ],
    "debugMode": true,
    "nativeAutomation": true
}

### Your complete test report

no report, because the tests doesn't conclude.

### Screenshots

_No response_

### Steps to Reproduce

1.
2.
3.

### TestCafe version

2.5.0

### Node.js version

16.18.1

### Command-line arguments

testcafe './tests/functional/fixtures/RequestTravellerInfo.cspec.js'

### Browser name(s) and version(s)

chrome 112

### Platform(s) and version(s)

macOS 13.3.1

### Other

_No response_

### PR DESCRIPTION
**Pull request by Aleksey28**
[closes #7652]

## Purpose
Fix hanging

## Approach
Force page reloading page between tests in NA if URL has a hash.

## References
https://github.com/DevExpress/testcafe/issues/7652

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

File: test/functional/fixtures/driver/test.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ describe('TestRun - Driver protocol', function () {
         return runTests('./testcafe-fixtures/prevent-real-action-test.js', 'Perform native click');
     });
 
-    describe('Regression', function () {
+    describe.only('Regression', function () {
```
Comment (miherlosev) [inline test/functional/fixtures/driver/test.js:33]: Remove the `only` hook.

Comment (miherlosev) [inline test/functional/fixtures/driver/test.js:33]: Remove the `only` hook.

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: src/client/browser/index.js [hunk 2]
```diff
@@ -104,17 +104,27 @@ export function stopInitScriptExecution () {
...
     if (isFileProtocol(command.url))
-        redirectUsingCdp(command, createXHR, openFileProtocolUrl);
+        redirectUsingCdp(command, opts);
     else
-        document.location = command.url;
+        setLocation(command, opts);
+}
+
+function setLocation (command, opts) {
+    const hashIndex         = command.url.indexOf('#');
```
[the remark this answers is not in the document]
Comment (Aleksey28) [reply src/client/browser/index.js]: I disagree with `hasHash`, because we need to get a hash index to check that only hash has changed.

**Review by miherlosev — APPROVED** [review]
