### PR TITLE
Fix the "Cannot redefine property" error (closes #1996).

### LINKED ISSUE #1996: The "Cannot redefine property %testCafeCore%" error is appeared
based on the [comment](https://github.com/DevExpress/testcafe/issues/1938#issuecomment-345393431).

We should make TestCafe client submodules configurable as it's done in [testcafe-hammerhead](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/index.js#L227).

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**
Additionally Define the "testcafeDriverInstance" client global var in iframes.

/cc @AndreyBelym @miherlosev

### CODE REVIEW

File: src/client/automation/index.js [hunk 1]
```diff
@@ -49,7 +49,7 @@ exports.get = require;
 
 hammerhead.nativeMethods.objectDefineProperty.call(window, window, '%testCafeAutomation%', {
     enumerable:   false,
-    configurable: false,
+    configurable: true,
```
Comment (miherlosev) [inline src/client/automation/index.js]: Flags `enumerable`, `configurable` and `writable` have `false` value by default.
You can omit flags that has 'false' value.

**Comment by AlexanderMoskovkin** [comment]
FPR
