### PR TITLE
Should not wait for selector timeout if element has border-radius (closes #3021)

### LINKED ISSUE #3021: Problem with border-radius and selectText [ie11, edge]
### What is your Test Scenario?
I have problem with ie11 and with edge browsers and selectText. If input has border-radius and I perform testcafe with assertion and selection timeout parameters  then input will be selected only after assertion or selection timeout. I think it's wrong, because I would like to select text after typing it.

### What is the Current behavior?
Text is selcted only after assertion or selection timeout

### What is the Expected behavior?
I expect text is selected after typing it like as it works in chrome or ff browsers
 
### What is your web application and your TestCafe test code?

I have test scenario test_select.js: 

```
import { Selector } from 'testcafe';

fixture `Getting Started`
    .page `YOUR_DOMAIN/test_login.html`;

test('My first test 1', async t => {
    await t
        .typeText("#t1", 'test_test_test', { replace: true })
        .selectText("#t1");
});
```
 
And, I have page test_login.html

```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>test</title>
	
	<style>

	input {
	    border-radius: 3px;
	}
	</style>
</head>
<body>
    <input id="t1" type="text"/>
</body>
</html>
```

And I perform

`testcafe ie test_select.js --selector-timeout 10000 --assertion-timeout 10000`
or
`testcafe edge test_select.js --selector-timeout 10000 --assertion-timeout 10000`
 
### Your Environment details:
 
* testcafe version:                  0.22.0
* node.js version:                  8.9.1
* command-line arguments:  
`testcafe ie test_select.js --selector-timeout 10000 --assertion-timeout 10000`
`testcafe edge test_select.js --selector-timeout 10000 --assertion-timeout 10000`

* browser name and version: IE11 (11.0.9600.19155), Edge 
* platform and version:          Windows7, Windows10

### PR DESCRIPTION
**Pull request by AlexKamaev**

### CODE REVIEW

File: src/client/automation/playback/visible-element-automation.js [hunk 1]
```diff
@@ -58,9 +59,20 @@ export default class VisibleElementAutomation extends serviceUtils.EventEmitter
             .then(() => delay(this.automationSettings.mouseActionStepDelay));
     }
 
+    _getElementOffset () {
+        const defaultOffsets = getOffsetOptions(this.element);
+
+        let { offsetX, offsetY } = this.options;
```
Comment (helen-dikareva) [inline src/client/automation/playback/visible-element-automation.js]: we can use `let { offsetX = defaultOffsets.offsetX , offsetY = defaultOffsets.offsetY} = this.options;`

File: test/functional/fixtures/regression/gh-3021/test.js [hunk 2]
```diff
@@ -0,0 +1,10 @@
+const getTimeLimitedPromise = require('time-limit-promise');
+
+describe('[Regression](GH-3021) - Should not wait for selector timeout', function () {
```
Comment (helen-dikareva) [inline test/functional/fixtures/regression/gh-3021/test.js]: Subject of the issue is not descriptive enough
