### PR TITLE
fix issues with window search (closes #5463, #5597)

### LINKED ISSUE #5463: switchWindow , swithctopreviouswindow is giving error "cannot find specified action parameter / previous window not found"
Scenario:
1.	Launch URL1 and do some actions through pageobject model classes to get URL2 in UI
2.	Launch URL2 
3.	Switch to URL1 window
Using  await t.switchToWindow(firstWindow)
 
Getting ```1 Cannot find the window specified in the action parameters.
 
{
  code: 'E74',
  isTestCafeError: true,
  callsite: CallsiteRecord {
    filename: 'C:\\Users\\xxxx\\Desktop\\Tool\\xxxxx.js',
    lineNum: 76,
    callsiteFrameIdx: 6,
    stackFrames: [
      [CallSite], [CallSite],
      [CallSite], [CallSite],
      [CallSite], [CallSite],
      [CallSite], CallSite {},
      [CallSite], [CallSite],
      [CallSite], [CallSite]
    ],
    isV8Frames: true
  }
} 

Tried using switchToPreviousWindow as well
    
Environment details:
 
* testcafe version:                   1.9
* node.js version:                    12.18.3
* browser name and version: chrome
* platform and version:          windows 10

### PR DESCRIPTION
**Pull request by AlexKamaev**
The cause:
If the page is reloaded it loses all its childLinks and parent links.

The approach:
Parent link is restorable easily since we have the `window.opener` property.
It is more difficult to restore child links since we do not have parent-child relationship.

So, I handle the `beforeunload` event and send a command to all child windows to start to ping parents.
Child windows get the command and start sending messages to parent. The child will repeat the sending until the parent does not confirm. So while the parent is reloading, the child is sending a message and do not get the confirmation. After the parent is reloaded, the new parent driver gets the message and send a confirmation. When the new parent gets the message it can restore the child window links.

### CODE REVIEW

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

File: src/client/driver/driver.js [hunk 1]
```diff
@@ -1110,6 +1162,18 @@ export default class Driver extends serviceUtils.EventEmitter {
...
     }
 
+    async _restoreChildWindowLinks () {
+        if (!this.contextStorage.getItem(PENDING_CHILD_WINDOW_COUNT))
+            return Promise.resolve();
+
+        return getTimeLimitedPromise(new Promise(resolve => {
+            this._restoreChildWindowsPromiseResolver = resolve;
+        }), RESTORE_CHILD_WINDOWS_TIMEOUT)
+            .catch(() => {
```
Comment (miherlosev) [inline src/client/driver/driver.js:1172]: Remove dev artifacts.

File: src/client/driver/driver.js [hunk 2]
```diff
@@ -1459,7 +1523,7 @@ export default class Driver extends serviceUtils.EventEmitter {
     }
 
     _initParentWindowLink () {
-        if (window.opener)
+        if (window.opener && window.opener !== window && this.windowId)
```
Comment (miherlosev) [inline src/client/driver/driver.js:1526]: Add comment describing this condition `window.opener !== window && this.windowId`;

File: src/client/driver/driver.js [hunk 3]
```diff
@@ -723,6 +771,10 @@ export default class Driver extends serviceUtils.EventEmitter {
                 this._handleGetWindows(msg, window);
             else if (msg.type === MESSAGE_TYPE.closeAllChildWindows)
                 this._handleCloseAllWindowsMessage(msg, window);
+            else if (msg.type === MESSAGE_TYPE.startToRestoreChildLink)
```
Comment (miherlosev) [inline src/client/driver/driver.js:774]: Can we use `switch` instruction here?

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: src/client/driver/driver.js (hunk 2 above)
Comment (AlexKamaev) [reply src/client/driver/driver.js:1534]: done

File: src/client/driver/driver.js (hunk 1 above)
Comment (AlexKamaev) [reply src/client/driver/driver.js]: this is not a dev artifact.
we need an empty line inside the catch block according to our linter rules.
As for the catch block. I decided not to throw an error if the link is not restored. I throw the error that the window is not found.

File: src/client/driver/driver.js (hunk 3 above)
Comment (AlexKamaev) [reply src/client/driver/driver.js:775]: We can. Do you prefer `switch`? In case of switch we will need to add extra `return` statements.

Comment (miherlosev) [reply src/client/driver/driver.js:775]: Yes, in this case the `switch` statement is more preferable.

File: src/client/driver/driver.js (hunk 1 above)
Comment (miherlosev) [reply src/client/driver/driver.js:1173]: It's better to raise a specific error ('Failed to restore connection to window within the allocated timeout').
It will allow to localize the problematic code place on errors.

Comment (miherlosev) [reply src/client/driver/driver.js:1173]: Also let's rewrite the `_restoreChildWindowLinks` using `async/await` statements.

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Comment by AlexKamaev** [comment]
@testcafe-build-bot retest

**Review by miherlosev — APPROVED** [review]

**Review by AndreyBelym — APPROVED** [review]
