### PR TITLE
Fix scrolling for negative scroll target coordinates(closes #2148)

### LINKED ISSUE #2148: Wrong taking element screenshot if scroll options are negative
According to docs we can set `scrollTargetX/scrollTargetY` negative numbers. But I have three the same screenshots in this test:
```js
import { Selector } from 'testcafe';

fixture `f`
    .page `https://www.amazon.com/`;

test('scroll points', async t => {
    await t
        .resizeWindow(500, 500)
        .takeElementScreenshot(Selector('body').nth(0))
        .takeElementScreenshot(Selector('body').nth(0),  { scrollTargetX: 100, scrollTargetY: 200 })
        .takeElementScreenshot(Selector('body'), { scrollTargetX: -10, scrollTargetY: -20 })
});
```

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @helen-dikareva @kirovboris

### CODE REVIEW

File: src/errors/test-run/templates.js [hunk 1]
```diff
@@ -198,6 +198,10 @@ export default {
         The "${err.argumentName}" argument specifies an unsupported "${err.actualValue}" device. For a list of supported devices, refer to <a href="http://viewportsizes.com">http://viewportsizes.com</a>.
     `),
 
+    [TYPE.actionInvalidScrollTargetError]: err => markup(err, `
+        Unable to scroll to the specified point of the element, because a point with the specified ${err.properties} is not inside the element's cropping region.
```
Comment (helen-dikareva) [inline src/errors/test-run/templates.js]: Let @VasilyStrelyaev check the text, if it's not done yet

Comment (VasilyStrelyaev) [reply src/errors/test-run/templates.js]:
```
        Unable to scroll to the specified point because a point with the specified ${err.properties} is not located inside the element's cropping region.
```
