### PR TITLE
fix: quarantine and skipJsErrors CLI option value cannot be set to false(closes #7077)

### LINKED ISSUE #7077: CLI command to set quarantine mode to false
### What is your Scenario?

In our .testcaferc file, we have quarantine mode enabled and use it for all of our runs, but we've implemented a feature that we don't want to use quarantine mode for (visual testing using Applitools).

### What are you suggesting?

Allow us to disable (set quarantine mode to false) in the CLI so we can write a script to kick off our visual tests without having to alter the .testcaferc file or have to write a separate config file just to have quarantine mode disabled for this one run.

### What alternatives have you considered?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Artem-Babich**
## Purpose
You cannot set the quarantine or skipJsErrors value to false via CLI. This should be allowed in order to have an ability to override the config file value

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

File: src/cli/argument-parser/index.ts [hunk 1]
```diff
@@ -454,9 +455,12 @@ export default class CLIArgumentParser {
             el => optionNames.some(opt => el.startsWith(opt)));
 
         if (optionIndex > -1) {
-            const isNotLastOption       = optionIndex < argv.length - 1;
-            const shouldMoveOptionToEnd = isNotLastOption &&
-                !subOptionsNames.some(opt => argv[optionIndex + 1].startsWith(opt));
+            const isNotLastOption        = optionIndex < argv.length - 1;
```
Comment (miherlosev) [inline src/cli/argument-parser/index.ts:458]: Move this code to the separate utility function `cli/util/should-move-option-to-end.js` and add tests to it.

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by miherlosev — APPROVED** [review]
