### PR TITLE
Fixed behavior for functional tests with attributes 'SKIP' and 'ONLY' (closes #444)

### LINKED ISSUE #444: Incorrect behavior of running functional tests with attributes 'SKIP' and 'ONLY'.
Irrelevant tests shouldn't run in browsers, but they do. Attributes affect only final report.

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @inikulin, @AlexanderMoskovkin

### CODE REVIEW

File: test/functional/is-browser-relevant.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+module.exports = function isBrowserRelevant (testName, browserAlias) {
```
Comment (inikulin) [inline test/functional/is-browser-relevant.js]: Why we need dedicated file for this? It's used only in `setup.js`

Comment (georgiy-abbasov) [inline test/functional/is-browser-relevant.js]: For the same reason as the file get-test-error.js is dedicated too. I thought this variant better, than overflowed setup.js file.

Comment (inikulin) [inline test/functional/is-browser-relevant.js]: > thought this variant better, than overflowed setup.js file.

Nope. Refactoring with functions just fine here.

Comment (inikulin) [inline test/functional/is-browser-relevant.js]: It's just a single function that used in one place. It's definetly belongs to the place there it was called.

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
We need to add `skip` and `only` fields to `runTests`'s `opts` argument instead of adding `[ONLY:], [SKIP:]` directives to TestCafe tests

File: test/functional/setup.js [hunk 2]
```diff
@@ -98,8 +118,15 @@ before(function () {
...
                 var quarantineMode = opts && opts.quarantineMode;
+                var skipOption     = opts && opts.skip;
+                var onlyOption     = opts && opts.only;
+
+                var connections = browsersInfo.filter(function (browserInfo) {
+                    var only = onlyOption ? onlyOption.indexOf(browserInfo.settings.alias) > -1 : true;
+                    var skip = skipOption ? skipOption.indexOf(browserInfo.settings.alias) < 0 : true;
 
-                var connections = browsersInfo.map(function (browserInfo) {
+                    return only && skip;
```
Comment (AlexanderMoskovkin) [inline test/functional/setup.js]: it's a strange combination of `only and skip`. Why we return `true` is `skip` is `true`? We should return `only && !skip` here as it was before

**Comment by AlexanderMoskovkin** [comment]
@VasilyStrelyaev please, check the comment

File: test/functional/setup.js [hunk 3]
```diff
@@ -76,6 +75,27 @@ function closeLocalBrowsers () {
     return Promise.all(closeBrowserPromises);
 }
 
+function getTestError (testReport, browsersCount) {
+    var testError = '';
+
+    if (testReport.errs.length) {
+        //NOTE: if the test failed in different browsers with the same error we join it to one error
```
Comment (VasilyStrelyaev) [inline test/functional/setup.js]:
```
        //NOTE: if the test failed in different browsers with the same error, we combine these errors into one
```

**Comment by VasilyStrelyaev** [comment]
\r-

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
please, rebase to upstream and correct functional tests with `only, skip` that were added in the #449

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
FPR

File: test/functional/fixtures/api/raw/click/test.js [hunk 4]
```diff
@@ -1,86 +1,88 @@
...
+var expect                        = require('chai').expect;
+var checkTestErrorContainsMessage = require('../../../../utils/assertion-helper.js').checkTestErrorContainsMessage;
+
 
 describe('[Raw API] Click action', function () {
     it('Should make click on a button', function () {
         return runTests('./testcafe-fixtures/click.testcafe', 'Click simple button', { shouldFail: true })
             .catch(function (err) {
-                expect(err).to.contains('Click on input raised');
+                checkTestErrorContainsMessage(err, 'Click on input raised');
```
Comment (inikulin) [inline test/functional/fixtures/api/raw/click/test.js]: Rename to `assertErrorContains`

File: test/functional/utils/assertion-helper.js [hunk 5]
```diff
@@ -0,0 +1,11 @@
+var expect = require('chai').expect;
```
Comment (inikulin) [inline test/functional/utils/assertion-helper.js]: Just put in `test/functional` dir.

File: test/functional/utils/assertion-helper.js [hunk 6]
```diff
@@ -0,0 +1,11 @@
+var expect = require('chai').expect;
+
+
+module.exports = {
+    // NOTE: this method checks, is the specified message the part of the value of keys given in testError object.
+    checkTestErrorContainsMessage: function (testError, message) {
+        Object.keys(testError).forEach(function (key) {
+            expect(testError[key]).with.deep.property('[0]').that.contains(message);
```
Comment (inikulin) [inline test/functional/utils/assertion-helper.js]: Why not just `testError[key][0]`?

File: test/functional/utils/assertion-helper.js [hunk 7]
```diff
@@ -0,0 +1,11 @@
+var expect = require('chai').expect;
+
+
+module.exports = {
```
Comment (inikulin) [inline test/functional/utils/assertion-helper.js]:
```js
exports.errorInEachBrowserContains = function errorInEachBrowserContains(error, message) {
```

File: test/functional/fixtures/api/es-next/click/test.js [hunk 8]
```diff
@@ -4,10 +4,10 @@ var expect = require('chai').expect;
 // Actions functionality is tested in lower-level raw API.
 describe('[API] t.click()', function () {
     it('Should make click on a button [ONLY:chrome]', function () {
-        return runTests('./testcafe-fixtures/click-test.js', 'Click button', { shouldFail: true })
+        return runTests('./testcafe-fixtures/click-test.js', 'Click button', { shouldFail: true, only: 'chrome' })
             .catch(function (err) {
-                expect(err).to.contains('Button clicked');
-                expect(err).to.contains(
+                expect(err[0]).to.contains('Button clicked');
+                expect(err[0]).to.contains(
```
Comment (inikulin) [inline test/functional/fixtures/api/es-next/click/test.js]: Here and in all other cases: rename `err` var to `errs` since it's now always contains multiple errors

File: test/functional/utils/assertion-helper.js (hunk 6 above)
Comment (inikulin) [inline test/functional/utils/assertion-helper.js]: Also, what if each browser has multiple errors? How can I check second error? We need to pass index as parameter here

**Comment by inikulin** [comment]
\r-

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

File: test/functional/assertion-helper.js [hunk 9]
```diff
@@ -0,0 +1,9 @@
+var expect = require('chai').expect;
+
+
+exports.errorInEachBrowserContains = function errorInEachBrowserContains (error, message, index) {
+    // NOTE: this method checks that in all browsers, errors with a particular index contain the specified message.
```
Comment (inikulin) [inline test/functional/assertion-helper.js]: Why we need this comment?

**Comment by inikulin** [comment]
There were some new tests added in the latest PR, it would be nice to rebase and take a look if they require fix.

**Comment by georgiy-abbasov** [comment]
@inikulin, this PR is based on the latest commit in the master branch. Did you mean the latest open PR ?

File: test/functional/assertion-helper.js (hunk 9 above)
Comment (georgiy-abbasov) [inline test/functional/assertion-helper.js]: Can we discuss in private ?

Comment (inikulin) [inline test/functional/assertion-helper.js]: Yep

**Comment by inikulin** [comment]
> Did you mean the latest open PR ?

Nope


>this PR is based on the latest commit in the master branch

good

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
FPR

File: test/functional/get-test-error.js [hunk 10]
```diff
@@ -30,28 +19,36 @@ function sanitizeError (err) {
...
 }
 
-module.exports = function getTestError (testReport, browsersInfo) {
-    var testError = '';
+// NOTE: This method should return dictionary or array object depending on the test result. If testing was against
+// several browsers and same error was occured in all of them, there should be an array with this error. In other
+// case, if tests were against one browser, there should be the array with errors too, regardless of their count.
+// Dictionary will be returned, if we got different errors in several browsers. In this case browser aliases will
+// be keys, and values will be arrays as described above.
+module.exports = function getTestError (testReport, browsers) {
```
Comment (inikulin) [inline test/functional/get-test-error.js]: Have you checked this with tech writers?

Comment (georgiy-abbasov) [inline test/functional/get-test-error.js]: Not yet. \cc @MargaritaLoseva, take a look, please.

Comment (MargaritaLoseva) [inline test/functional/get-test-error.js]: This method should return either a dictionary or array object with errors depending on the number of browsers and errors. The possible variants:
 
If tests run in one browser, the method returns an array with errors regardless of the number of errors.
 
If tests run in several browsers and the same error occurs in all of them, the method returns an array as well. 
 
If different errors occur in several browsers, a dictionary object is returned. In this case, browser aliases are keys, and values are arrays of errors.

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
FPR

File: test/functional/assertion-helper.js [hunk 11]
```diff
@@ -0,0 +1,8 @@
+var expect = require('chai').expect;
+
+
+exports.errorInEachBrowserContains = function errorInEachBrowserContains (testError, message, errorIndex) {
```
Comment (AlexanderMoskovkin) [inline test/functional/assertion-helper.js]: you can use an unnamed function here because it's not used in the file
```js
exports.errorInEachBrowserContains = function (testError, message, errorIndex) {
```

**Comment by AlexanderMoskovkin** [comment]
I suppose we should remove all `[ONLY:*]` entries from mocha test and testcafe test names to avoid `skip-only` directive duplication since we have `only` option in `runTests`. @inikulin do you agree or it doesn't matter?

**Comment by georgiy-abbasov** [comment]
These `[ONLY:...]` entries have been deleted from testcafe test names.

File: test/functional/assertion-helper.js (hunk 11 above)
Comment (inikulin) [inline test/functional/assertion-helper.js]: No. Bad advice. Always try to export named functions. This way you will have proper stack traces

**Comment by inikulin** [comment]
>  @inikulin do you agree or it doesn't matter?

Yes

File: test/functional/assertion-helper.js (hunk 11 above)
Comment (AlexanderMoskovkin) [inline test/functional/assertion-helper.js]: got it

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm
