### PR TITLE
stop spinner in LiveMode if bootstrapping failed (closes #3451)

### LINKED ISSUE #3451: TestCafe spinner doesn't stop in live mode if a test file has syntax error
### What is your Test Scenario?
Make a mistake in a test file and run it in live mode.
 
### What is the Current behavior?
TestCafe doesn't hide the spinner after printing an error. 
```
F:\test\release> npx testcafe -L
|

Live mode is enabled.
TestCafe now watches source files and reruns
the tests once the changes are saved.

You can use the following keys in the terminal:
'Ctrl+S' - stops the test run;
'Ctrl+R' - restarts the test run;
'Ctrl+W' - enables/disables watching files;
'Ctrl+C' - quits live mode and closes the browsers.


Watching the following files:
  F:\test\release\blabla\testi.ts
|

Make changes to the source files or press Ctrl+R to restart the test run.
ERROR: Error: Cannot prepare tests due to an error.

Error: TypeScript compilation failed.
F:/test/release/blabla/testi.ts (5, 20): Cannot find module './blablabla'.
/       <= spins until <Ctrl> + R is pressed or the test file is edited

```

### What is the Expected behavior?
TestCafe should hide the spinner after printing an error.

### PR DESCRIPTION
**Pull request by AlexKamaev**
Closes #3451.

### CODE REVIEW

File: src/cli/cli.js [hunk 1]
```diff
@@ -96,7 +96,9 @@ async function runTests (argParser) {
         .screenshots(opts.screenshots, opts.screenshotsOnFails, opts.screenshotPathPattern)
         .startApp(opts.app, opts.appInitDelay);
 
-    runner.once('done-bootstrapping', () => log.hideSpinner());
+    runner.initEvents({
```
Comment (miherlosev) [inline src/cli/cli.js]: What about raising `done-bootstrapping` event in the `Runner._createRunnableConfiguration` method?
```js
_createRunnableConfiguration () {
        return this.bootstrapper
            .createRunnableConfiguration()
            .then(runnableConfiguration => {
                this.emit('done-bootstrapping');

                return runnableConfiguration;
            });
    }

```
