### PR TITLE
Fix quarantine mode (closes #328)

### LINKED ISSUE #328: BrowserConnection and BrowserJob interoperation issue in quarantine mode
When a test fails in quarantine mode, browser goes to idle page, and server hangs. 

*Short version:*
We need to refactor how `browserConnection` removes `browserJob` from its `jobQueue`.

*Long version:*
For simplification, let's assume that a `browserConnection` has an one `browserJob` in `jobQueue`, and the `browserJob` has an one `testRun` in `testRunQueue`. 

Whats going on when you start test in quarantine mode and it fails:

1. Just when we are about to start the test, Idle Page requests status from server, so [browserConnection.getStatus](https://github.com/DevExpress/testcafe/blob/master/src/browser-connection/index.js#L105) is called. The method calls itself [browserConnection._popNextTestRunUrl](https://github.com/DevExpress/testcafe/blob/master/src/browser-connection/index.js#L51), that checks `jobQueue.length` and makes a call to [browserJob.popNextTestRunUrl](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-job.js#L105).

2. [browserJob.popNextTestRunUrl](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-job.js#L105) shifts `testRunQueue` and returns URL to an opened session. Note that `testRunQueue` is empty now.

3. After we have returned to  [browserConnection._popNextTestRunUrl](https://github.com/DevExpress/testcafe/blob/master/src/browser-connection/index.js#L51), we are calling [browserJob.hasQueuedTestRun](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-job.js#L101). Because `testRunQueue` is empty, it returns `false`, so `browserConnections` shifts `jobQueue`. So `jobQueue` is empty now.

4. When test is failed, client sends a message with error to server and requests status. The message is passed to server `testRun` object, that reports failure to `browserJob`. Because we are quarantine mode, [_startQuarantine](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-job.js#L29) and [_keepInQuarantine](https://github.com/DevExpress/testcafe/blob/master/src/runner/browser-job.js#L50) are called, and a new `testRun` is prepended into `testRunQueue`. Now `browserConnection` must return status url. We are expecting that `browserConnection` will call `browserJob.popNextTestRunUrl` and get a url for the new `testRun`, but `browserConnection` removed `browserJob` from `jobQueue`, so it's empty and `browserConnection` simply returns idle page url. So client navigates to idle page, and server waits for `done` event from `browserJob` that will never be emitted.

### LINKED ISSUE #329: Missing errors raised on beforeunload event
If you have unexpected beforeunload dialog, or expected beforeunload dialog did not appear, no error will be reported since [my last commit](https://github.com/DevExpress/testcafe/commit/f0043dcee3d7db526edff9943e98c96450230103), which changed the way we handle error occuring on beforeunload event: instead of sending it to server and embedding in `task.js` template, it is saved in `TestContextStorage` now. 

Due to implementation of `TestContextStorage`, when you store a variable in it, it does'nt saved to `sessionStorage` immediatelly, but only when beforeunload event occurs. Unfortunately, `TestContextStorage` subscribes to the event before we are checking beforeunload dialog and raise an error, so the error will be stored after contents of `TestContextStorage` has saved in `sessionStorage`, and will not be saved after page reload.

### PR DESCRIPTION
**Pull request by AndreyBelym**
\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
You have a typo in the commit name and in the pr title. Should change #329 with #328

File: src/runner/browser-job.js [hunk 1]
```diff
@@ -99,7 +102,7 @@ export default class BrowserJob extends EventEmitter {
 
     // API
     get hasQueuedTestRuns () {
-        return !!this.testRunQueue.length;
+        return !!this.testRunQueue.length || this.opts.quarantineMode && !this.done;
```
Comment (AlexanderMoskovkin) [inline src/runner/browser-job.js]: I don't so like this fix because it adds some mishmash. With this fix the `getQueuedTestRuns` don't tell us "is there a test run in the queue", but it's "is there a test run in the queue or there are a running test in quarantine mode".

Maybe we should fix just `browserConnection`?
Now it's 
```js
_popNextTestRunUrl () {
        if (this.jobQueue.length) {
            var job = this.jobQueue[0];
            var url = job.popNextTestRunUrl();

            if (!job.hasQueuedTestRuns)
                this.jobQueue.shift();

            return url;
        }

        return null;
    }
```
This gets the next test run url from a `job` and remove the `job` from the `jobQueue`. I propose change the sequence:
```js
_popNextTestRunUrl () {
        if (this.jobQueue.length) {
            if (!job.hasQueuedTestRuns)
                this.jobQueue.shift();

           if (this.jobQueue.length) {
                var job = this.jobQueue[0];
                var url = job.popNextTestRunUrl();

                return url;
          }
        }

        return null;
    }
```

/cc @inikulin @AndreyBelym

Comment (inikulin) [inline src/runner/browser-job.js]: With this approach we will always have on job left in the queue after test run. However, I agree with @AlexanderMoskovkin points. We need something conceptually better.

Comment (AndreyBelym) [inline src/runner/browser-job.js]: > With this approach we will always have one job left in the queue

No it won't be so, because next call of `job.hasQueuedTestRuns` will return `false` after calling `job.popNextTestRunUrl`, so `job` will be removed on next call of `browserConnection._popNextTestRunUrl()`. Looks like solution to me.

Comment (inikulin) [inline src/runner/browser-job.js]: OK, let's try this one

**Comment by AndreyBelym** [comment]
FPR

File: src/browser-connection/index.js [hunk 2]
```diff
@@ -48,18 +48,19 @@ export default class BrowserConnection extends EventEmitter {
...
-        if (this.jobQueue.length) {
-            var job = this.jobQueue[0];
-            var url = job.popNextTestRunUrl();
+    _hasQueuedJobs () {
+        return !!this.jobQueue.length;
+    }
 
-            if (!job.hasQueuedTestRuns)
-                this.jobQueue.shift();
+    _currentJob () {
```
Comment (inikulin) [inline src/browser-connection/index.js]: Both `_hasQueuedJobs` and `_currentJob` can be getters like `hasQueuedTestRuns` in `BrowserJob`

**Comment by inikulin** [comment]
\r-

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
Can we write a regression functional test on this?

**Comment by AndreyBelym** [comment]
FPR

File: test/functional/setup.js [hunk 3]
```diff
@@ -1,143 +1,149 @@
-var browserNatives     = require('testcafe-browser-natives');
```
Comment (AndreyBelym) [inline test/functional/setup.js]: Strange, looks like that `git` have decided that file was rewritten. I'll reset the commit and then apply it back.

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

File: test/functional/fixtures/runner/regression/fails-by-request.html [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+<head>
+    <meta charset="UTF-8">
+    <title>Test fails by a request</title>
+</head>
+<body>
+<script type="text/javascript">
+    function sendRequest (callback) {
+        var request = new XMLHttpRequest();
+        request.addEventListener('load', function () {
+            debugger;
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/runner/regression/fails-by-request.html]: remove `debugger;`

File: test/functional/fixtures/runner/regression/fails-by-request.html [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+<html lang="en">
+<head>
+    <meta charset="UTF-8">
+    <title>Test fails by a request</title>
+</head>
+<body>
+<script type="text/javascript">
+    function sendRequest (callback) {
+        var request = new XMLHttpRequest();
+        request.addEventListener('load', function () {
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/runner/regression/fails-by-request.html]: empty line after var declaration

**Comment by AndreyBelym** [comment]
@MargaritaLoseva, please, check test's names.

File: test/functional/fixtures/runner/regression/fails-by-request.html [hunk 6]
```diff
@@ -0,0 +1,27 @@
+<!DOCTYPE html>
+<html lang="en">
+<head>
+    <meta charset="UTF-8">
+    <title>Test fails by a request</title>
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/regression/fails-by-request.html]: Test fails on sending a request

File: test/functional/fixtures/runner/regression/quarantine-mode-test.js [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+    });
+
+    beforeEach(function () {
+        expectedBrowsersCount = BROWSERS_COUNT;
+        requestNumber         = 0;
+        responses             = [];
+        serverResponse        = null;
+    });
+
+    it('Should pass if an unstable test mostly passes', function () {
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/regression/quarantine-mode-test.js]: Should pass if an unstable test passes in most of runs

File: test/functional/fixtures/runner/regression/quarantine-mode-test.js [hunk 8]
```diff
@@ -0,0 +1,98 @@
...
+        return runTests('quarantine-mode.test.js', 'Wait 200ms', { quarantineMode: true })
+            .then(function (err) {
+                expect(requestNumber).to.be.at.least(3);
+                expect(testReport.unstable).to.be.true;
+                expect(err).to.equal('');
+            });
+    });
+
+
+    it('Should fail if an unstable test mostly fails', function () {
```
Comment (MargaritaLoseva) [inline test/functional/fixtures/runner/regression/quarantine-mode-test.js]: Should fail if an unstable test fails in most of runs

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AndreyBelym** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
Failed tests are unstable qunit tests. They don't relate to this PR. So we can review it now.
/cc @inikulin

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by AndreyBelym** [comment]
FPR

File: test/functional/fixtures/runner/regression/quarantine-mode-test.js [hunk 9]
```diff
@@ -0,0 +1,98 @@
...
+    });
+
+    beforeEach(function () {
+        expectedBrowsersCount = BROWSERS_COUNT;
+        requestNumber         = 0;
+        responses             = [];
+        serverResponse        = null;
+    });
+
+    it('Should pass if an unstable test passes in most of runs', function () {
```
Comment (inikulin) [inline test/functional/fixtures/runner/regression/quarantine-mode-test.js]: These tests requires GH issue reference in the name

Comment (inikulin) [inline test/functional/fixtures/runner/regression/quarantine-mode-test.js]: I've just found out that we don't have any other tests for the quarantine mode and regression tests test some very basic scenarios. I guess we shouldn't name it regression tests then. They should be just regular functionality tests.

**Comment by inikulin** [comment]
\r-

**Comment by AndreyBelym** [comment]
FPR

File: test/functional/fixtures/quarantine-mode/quarantine-mode-test.js [hunk 10]
```diff
@@ -0,0 +1,98 @@
+var expect         = require('chai').expect;
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/quarantine-mode/quarantine-mode-test.js]: usually we name this file`index-test.js`. To avoid duplication in `/quarantine-mode/quarantine-mode-test.js`

**Comment by AndreyBelym** [comment]
FPR

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm
