### PR TITLE
fix: fixed regression with using tests and fixture methods

### LINKED ISSUE #7482: Regression in 2.3.0
### What is your Scenario?

A regression was introduced in testcafe 2.3.0 which causes the following code to throw an error.

It used to run in older versions of testcafe and does not look faulty.

### What is the Current behavior?

Running the test fails with this message:
```
~/tmp/testcafe-bug »  npx testcafe chrome:headless
ERROR Cannot prepare tests due to the following error:

TypeError: _index.test.meta is not a function
    at Object.<anonymous> (/Users/user/tmp/testcafe-bug/tests/test.js:14:6)

Type "testcafe -h" for help.
```

### What is the Expected behavior?

the test runs without issues

### What is your public website URL? (or attach your complete example)

-

### What is your TestCafe test code?

```js
// this is working:
//import { Selector } from 'testcafe';
// this works also:
//import { Selector, fixture } from 'testcafe';
// this causes the described error message:
import { Selector, fixture, test } from 'testcafe';

const nameInput = Selector('#developer-name');

fixture `A set of examples that illustrate how to use TestCafe API`
    .page `https://devexpress.github.io/testcafe/example/`;

// Tests
test.meta('dev', 'true')('Text typing basics', async t => {
    await t
        .typeText(nameInput, 'Peter') // Type name
        .typeText(nameInput, 'Paker', { replace: true }) // Replace with last name
        .typeText(nameInput, 'r', { caretPos: 2 }) // Correct last name
        .expect(nameInput.value).eql('Parker'); // Check result
});
```

### Your complete configuration file

_No response_

### Your complete test report

_No response_

### Screenshots

_No response_

### Steps to Reproduce

1. create the testfile with the code above
2. run it either with `npx testcafe chrome` or whatever
3. see it fail

if you change to another kind of import in the first few lines it is working. It stops working as soon as `test` is imported from testcafe package (which makes typehints in your editor possible, that's why we have this somewhat redundant import)

### TestCafe version

2.3.0

### Node.js version

_No response_

### Command-line arguments

irrelevant

### Browser name(s) and version(s)

_No response_

### Platform(s) and version(s)

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by Aleksey28**
[closes #7482]

## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
https://github.com/DevExpress/testcafe/issues/7482

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

File: test/functional/fixtures/regression/gh-7482/test.js [hunk 1]
```diff
@@ -0,0 +1,5 @@
+describe('[Regression](GH-7482)', () => {
+    it('Shouldn\'t throw errors if test and fixtures methods are executed before test and fixtures', async () => {
```
Comment (miherlosev) [inline test/functional/fixtures/regression/gh-7482/test.js:2]: It's better do not escape the `'` in the test name.
If this test will fail, you can't find it using Ctrl+C, Ctrl+F in IDE.
Surround the string in double quotes.
```js
it("Should n't throw errors if test and fixtures methods are executed before test and fixtures",
```

File: src/api/structure/testing-unit.ts [hunk 2]
```diff
@@ -155,6 +155,25 @@ export default abstract class TestingUnit extends BaseUnit {
         //@ts-ignore
         ChildClass.API_LIST = TestingUnit.API_LIST.concat(getDelegatedAPIList(ChildClass.prototype));
     }
+
+    public static initTestingUnit (ChildClass: unknown, ...initProps: unknown[]): Function {
```
Comment (miherlosev) [inline src/api/structure/testing-unit.ts:159]: I think you can rename this method to `init` to consistent with `Fixture` and `Test` classes.

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by miherlosev — APPROVED** [review]
