### PR TITLE
Increase remote browser connection waiting timeout (closes #1078)

### LINKED ISSUE #1078: Increase remote browser conneciton waiting timeout
When I run tests via the `testcafe-browser-provider-saucelabs` often TestCafe fails with the `Unable to establish` before a virtual machine on Saucelabs is ready to run tests. Especially virtual machine bootstrapping takes some more time when it's a mobile device.

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**
/cc @inikulin @georgiy-abbasov

### CODE REVIEW

File: src/runner/browser-set.js [hunk 1]
```diff
@@ -44,16 +45,24 @@ export default class BrowserSet extends EventEmitter {
         await promisifyEvent(bc, 'closed');
     }
 
-    _waitConnectionsOpened () {
+    async _getReadyTimeout () {
+        var isLocalBrowserPromises = this.connections.map(connection => connection.provider.plugin.isLocalBrowser());
```
Comment (kirovboris) [inline src/runner/browser-set.js]: I don't know details of implementation, but it looks like you can subtract the number of ```localBrowserPromises``` from number of connections. Or even 
```javascript
var remoteBrowserExists = this.connections.map(connection => !connection.provider.plugin.isLocalBrowser());
```
Otherwise, variable name is confusing me.

File: src/runner/browser-set.js [hunk 2]
```diff
@@ -46,10 +46,16 @@ export default class BrowserSet extends EventEmitter {
     }
 
     async _getReadyTimeout () {
-        var isLocalBrowserPromises = this.connections.map(connection => connection.provider.plugin.isLocalBrowser());
-        var remoteBrowsersCount    = (await Promise.all(isLocalBrowserPromises)).filter(isLocal => !isLocal).length;
+        var remoteBrowsersExists = false;
```
Comment (kirovboris) [inline src/runner/browser-set.js]:
```javascript
for (var i = 0; i < this.connections.length; i++) {
    var isLocalBrowser = await this.connections[i].provider.plugin.isLocalBrowser();

	if (!isLocalBrowser) 
		return REMOTE_BROWSERS_READY_TIMEOUT;
}

return LOCAL_BROWSERS_READY_TIMEOUT;
```

Comment (AlexanderMoskovkin) [inline src/runner/browser-set.js]: I've decided to do it in parallel

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
It's an unstable test, so I merge this
