### PR TITLE
Provide capability to pass timeStamp as mouseClick argument (closes #3645)

### LINKED ISSUE #3645: Click action performed twice
### Steps to Reproduce:
1. Run test (one click on checkbox):
```js
import { Selector } from 'testcafe';

fixture `enactjs sampler`
    .page `http://enactjs.com/2.3.0/sampler/`;

test('New Test', async t => {
    await t
        .setTestSpeed(0.75)
        .click(Selector('div').withText('Moonstone').nth(12).find('div').find('div').find('svg'))
        .click(Selector('[data-radium="true"]').nth(5).find('div').withText('CheckboxItem').nth(1))
        .switchToIframe(Selector('#storybook-preview-iframe'))
        .click(Selector('[class^="ToggleIcon-module__toggleIcon___2V_Lg Checkbox-mod"]')) // one click on checkbox
        .debug();
});
```
2. See "Action Logger":
Capture

### Additional info
`.click(Selector('[class^="ToggleIcon-module__toggleIcon___2V_Lg Checkbox-mod"]'))`:
1. First `onToggle` after `ClickAutomation.prototype._mousedown`.
2. Second `onToggle` after `ClickAutomation.prototype._click`.

Support Center ticket: T676301.
 
### Your Environment details:
 * testcafe version:                 1.1.1 [e26eebc]
* browser name and version: Chrome, Firefox, Internet Explorer 11, Edge
* platform and version:          Windows 10

### PR DESCRIPTION
**Pull request by AlexKamaev**

### CODE REVIEW

**Comment by AlexKamaev** [comment]
https://github.com/DevExpress/testcafe-hammerhead/pull/2015

File: src/client/automation/playback/click/mouseup-command.js [hunk 1]
```diff
@@ -0,0 +1,34 @@
+import hammerhead from '../../deps/hammerhead';
+
+const browserUtils   = hammerhead.utils.browser;
+const eventSimulator = hammerhead.eventSandbox.eventSimulator;
+const listeners      = hammerhead.eventSandbox.listeners;
+
+class ElementMouseUpCommand {
```
Comment (miherlosev) [inline src/client/automation/playback/click/mouseup-command.js]: We don't have other commands. So, the packing code to the separate `Command` class is unnecessary.

File: src/client/automation/playback/click/mouseup-command.js [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+    run () {
+        let timeStamp = {};
+
+        const getTimeStamp = e => {
+            timeStamp = e.timeStamp;
+
+            listeners.removeInternalEventListener(window, ['mouseup'], getTimeStamp);
+        };
+
+        if (!browserUtils.isIE)
```
Comment (miherlosev) [inline src/client/automation/playback/click/mouseup-command.js]: `if (!browserUtils.isIE11)`

File: test/client/fixtures/automation/click-test.js [hunk 3]
```diff
@@ -715,6 +715,43 @@ $(document).ready(function () {
             });
     });
 
+    if (!browserUtils.isIE) {
+        asyncTest('click and mouseup events have equal `timeStamp` properties', function () {
```
Comment (miherlosev) [inline test/client/fixtures/automation/click-test.js]: `asyncTest('click and mouseup events should have equal `timeStamp` properties'`

File: test/client/fixtures/automation/click-test.js [hunk 4]
```diff
@@ -715,6 +715,43 @@ $(document).ready(function () {
             });
     });
 
+    if (!browserUtils.isIE) {
```
Comment (miherlosev) [inline test/client/fixtures/automation/click-test.js]: `if (!browserUtils.isIE11)`

File: src/client/automation/playback/click/index.js [hunk 5]
```diff
@@ -212,6 +215,10 @@ export default class ClickAutomation extends VisibleElementAutomation {
                 return Promise.all([delay(this.automationSettings.mouseActionStepDelay), this._mousedown(eventArgs)]);
             })
             .then(() => this._mouseup(eventArgs))
-            .then(() => this._click(eventArgs));
+            .then(({ timeStamp }) => {
+                eventArgs.options.timeStamp = timeStamp;
```
Comment (miherlosev) [inline src/client/automation/playback/click/index.js]: Does `mousedown` event should have `timeStamp` property value same as for `mouseup` and `click`?

File: src/client/automation/playback/click/mouseup-command.js (hunk 2 above)
Comment (AlexKamaev) [reply src/client/automation/playback/click/mouseup-command.js]: We need both IE and Edge here

File: test/client/fixtures/automation/click-test.js (hunk 4 above)
Comment (AlexKamaev) [reply test/client/fixtures/automation/click-test.js]: here too

File: src/client/automation/playback/click/index.js (hunk 5 above)
Comment (AlexKamaev) [reply src/client/automation/playback/click/index.js]: no, we can hold mouse button

File: src/client/automation/playback/click/mouseup-command.js (hunk 1 above)
Comment (AlexKamaev) [reply src/client/automation/playback/click/mouseup-command.js]: I found it useful, it helps to keep `index.js` clean, since it should not know anything about hacks like `getTimeStamp` or `browserUtils.isIE`

Comment (AndreyBelym) [reply src/client/automation/playback/click/mouseup-command.js]: I also feel that there is too much code for this. I feel it can be useful to extract timestamp manipulation functions to a separate file, but it's better to use them directly in `_mouseUp` in the click automation.

**Comment by AndreyBelym** [comment]
Maybe instead of this tricky timestamp capturing we can just create `MouseUp` and `Click` event objects at the same time? However I doubt if we can implement it easily

**Comment by AlexKamaev** [comment]
> Maybe instead of this tricky timestamp capturing we can just create `MouseUp` and `Click` event objects at the same time? However I doubt if we can implement it easily

You're right it's difficult and I think it hardly will help us in the future, so I think it's better to fix it in the easiest manner

File: src/client/automation/playback/click/mouseup-command.js (hunk 2 above)
Comment (miherlosev) [reply src/client/automation/playback/click/mouseup-command.js]: Ok

File: test/client/fixtures/automation/click-test.js [hunk 6]
```diff
@@ -715,6 +715,43 @@ $(document).ready(function () {
...
+            target.addEventListener('click', function (e) {
+                clickTimeStamp = e.timeStamp;
+            });
+
+            const clickAutomation = new ClickAutomation(target, { });
+
+            return clickAutomation
+                .run()
+                .then(function () {
+                    ok(!!mouseUpTimeStamp);
```
Comment (miherlosev) [inline test/client/fixtures/automation/click-test.js]: You check that `mouseUpTimeStamp` is a valid timestamp and not equal `null`.
In my opinion, it's more readable to use this notation:
```js
ok (typeof `mouseUpTimeStamp` === 'number');
```

**Comment by AlexKamaev** [comment]
> It's fine. Let's wait until the hammerhead part is published to NPM.

Since it's fine I'll merge it
