### PR TITLE
fix cookie filtering in Native Automation, fix httpOnly (closes #7798, #7793)

### LINKED ISSUE #7798: The `getCookies` action with filter parameters returns the wrong set of cookies in Native Automation mode
### What is your Scenario?

Use the `getCookies` action to get coockies with filter parameters

### What is the Current behavior?

Cookies are missing in returned cookies set

### What is the Expected behavior?

The `getCookies` action should return all requested cookies

### What is your public website URL? (or attach your complete example)

https://devexpress.github.io/testcafe/example/

### What is your TestCafe test code?

```ts
fixture('[API] Get Cookies')
    .page('https://devexpress.github.io/testcafe/example/');

test('Should retrieve a cookie with the specified url', async t => {
    //set a cookie for the Example page
    await t.setCookies({ name: 'apiCookie1', value: 'value1' });

    //set a cookie for localhost
    await t.setCookies({ name: 'apiCookie2', value: 'value2' }, 'http://localhost');

    //retrieve all cookies
    let cookies = await t.getCookies(['apiCookie1', 'apiCookie2']);

    await t.expect(cookies.length).eql(2);

    //retrieve cookies from the Example page
    cookies = await t.getCookies(['apiCookie1', 'apiCookie2'], 'https://devexpress.github.io/testcafe/example/');
    await t.expect(cookies.length).eql(1);

    //retrieve cookies from localhost
    cookies = await t.getCookies(['apiCookie1', 'apiCookie2'], 'https://localhost');
    await t.expect(cookies.length).eql(1);
});
```

### Your complete configuration file

_No response_

### Your complete test report

_No response_

### Screenshots

_No response_

### Steps to Reproduce

You can reproduce the problematic behavior on the following examples:
https://github.com/DevExpress/testcafeio-examples/blob/main/tests/documentation/reference/test-api/test-controller/get-cookies/single-by-url.js
https://github.com/DevExpress/testcafeio-examples/blob/main/tests/documentation/reference/test-api/test-controller/get-cookies/all-by-url.js

### TestCafe version

3.0.0-rc.1

### Node.js version

_No response_

### Command-line arguments

npx testcafe chrome

### Browser name(s) and version(s)

_No response_

### Platform(s) and version(s)

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by AlexKamaev**

### CODE REVIEW

File: src/utils/match-collection.ts [hunk 1]
```diff
@@ -3,15 +3,15 @@ import { isMatch } from 'lodash';
 // NOTE: this method will duplicate the matching items
 // currently cookies-tests use incorrect behavior of this method
 // the method and cookies-tests should be rewritten
-export default function matchCollection (items: object[], filters: object[]): object[] {
+export default function matchCollection (items: object[], filters: object[], customFilter?: Function): object[] {
```
Comment (miherlosev) [inline src/utils/match-collection.ts:6]: Can we rewrite this function as follows:
```js
export default function matchCollection (items: object[], filters: object[], matchFn = isMatch): object[] {
...
if (matchFn(item, filter))
    result.push(item);
...
```

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: src/utils/match-collection.ts (hunk 1 above)
Comment (AlexKamaev) [reply src/utils/match-collection.ts:6]: Sure

**Review by miherlosev — APPROVED** [review]
