### PR TITLE
fix: SkipJsErrors RegExp parsed incorrectly if it is passed through CLI(closes #7301)

### LINKED ISSUE #7301: SkipJsErrors RegExp parsed incorrectly when set through CLI
### What is your Scenario?

Run tests with the following params: 
`testcafe chrome test.js -e message="/.*User ID.*/ig"`

And call the following code on page:
`throw new Error('User ID');`

### What is the Current behavior?

The error is not skipped.

### What is the Expected behavior?

The error must be skipped.

### What is your public website URL? (or attach your complete example)

localhost

### What is your TestCafe test code?

does not matter

### Your complete configuration file

_No response_

### Your complete test report

_No response_

### Screenshots

_No response_

### Steps to Reproduce

Run tests with the following params: 
`testcafe chrome test.js -e message="/.*User ID.*/ig"`

And call the following code on page:
`throw new Error('User ID');`

### TestCafe version

2.0.1-rc.1

### Node.js version

any

### Command-line arguments

-e message="/.*User ID.*/ig"`

### Browser name(s) and version(s)

any

### Platform(s) and version(s)

any

### Other

_No response_

### PR DESCRIPTION
**Pull request by Artem-Babich**
## Purpose
RegExp parsed incorrectly when passing it via CLI or as a string argument. After parsing the string into source and flags, we pass the source to a function that escapes all characters associated with the RegExp. We should escape characters only if the user sets a non-regex value.

## Approach
Do not escape chars in the string if it is a regular expression string.

## References
[#7301](https://github.com/DevExpress/testcafe/issues/7301)

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

File: src/utils/make-reg-exp.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ export function parseRegExpString (regExp) {
     const parsedRegExpWithFlags = regExp.match(SPLIT_INPUT_AND_FLAGS_REG_EXP);
 
     if (parsedRegExpWithFlags)
-        return makeRegExp(parsedRegExpWithFlags[1], parsedRegExpWithFlags[2]);
+        return RegExp(parsedRegExpWithFlags[1], parsedRegExpWithFlags[2]);
```
Comment (miherlosev) [inline src/utils/make-reg-exp.js:12]: I guess you should remove outer quotes for the string `SkipJSOptions` options in the `src/utils/get-options/skip-js-errors.ts` file. Use the `src/utils/get-options/compiler.ts` file as an example.

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by miherlosev — APPROVED** [review]
