### PR TITLE
fix TestCafe hangs during TestCafe Studio tests (closes #5207)

### LINKED ISSUE #5207: TestCafe hangs during TestCafe Studio tests
See https://github.com/DevExpress/testcafe-studio/pull/3121 and https://github.com/DevExpress/testcafe-studio/issues/3086#issuecomment-638245790.

Tests hangs due to a missed `testRun.ready` event. Tried to subscribe to the event as early as possible. Improved the situation, but TestCafe still hangs sometimes.

### PR DESCRIPTION
**Pull request by AlexKamaev**
if we have `disablePageReloads` enabled and the next test is from next fixture, then we need to wait until all reporters finished to prevent redirecting to the `idle` page

### CODE REVIEW

File: test/functional/fixtures/regression/gh-5207/test.js [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+        },
+        async reportTestDone () {
+            return new Promise(resolve => {
+                setTimeout(resolve, 5000);
+            });
+        },
+        async reportTaskDone () {
+        }
+    };
+}
```
Comment (miherlosev) [inline test/functional/fixtures/regression/gh-5207/test.js:15]: You can simplify creation of the custom reporter using the `createReporter` utility function.
```js
import createReporter from 'test/functional/utils/reporter.js'

createReporter({
  reportTestDone: async () {
      return new Promise(resolve => {
          setTimeout(resolve, 5000);
       });
  }
})

```

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by AndreyBelym — APPROVED** [review]

**Review by miherlosev — APPROVED** [review]
