### PR TITLE
fix: durationMs value is incorrect for skipped tests(closes #7731)

### LINKED ISSUE #7731: Unexpected testRunInfo.durationMs times
### What is your Scenario?

I am running my tests in parallel with test duration outputs.

### What is the Current behavior?

Non-zero durations for skipped tests indicate that the logged test duration may not be matching the actual runtime of each test.

### What is the Expected behavior?

`durationMs` returns accurate test runtime durations.

### What is your public website URL? (or attach your complete example)

https://devexpress.github.io/testcafe/example/

### What is your TestCafe test code?

[example.zip](https://github.com/DevExpress/testcafe/files/11574709/example.zip)

This can be reproduced running the example project tests from `create-testcafe` several times in parallel.

### Your complete configuration file

```js
function onBeforeWriteHook(writeInfo) {
  if (writeInfo.initiator === "reportTestDone") {
    const {testRunInfo} = writeInfo.data ?? {};
    const testDurationInSeconds = testRunInfo.durationMs / 1000;
    const warnings = testRunInfo.warnings;
    writeInfo.formattedText += ` (${testDurationInSeconds}s)`;
    if (warnings.length > 0) {
      for (const warning of warnings) {
        writeInfo.formattedText += `\n${warning}`;
      }
    }
  }
}

module.exports = {
  "src": "tests",
  hooks: {
    reporter: {
      onBeforeWrite: {
        "spec": onBeforeWriteHook
      }
    }
  }
}
```

### Your complete test report

```
chris@chrispc% npx testcafe chromium:headless -c 3
 Running tests in:
 - Chrome 113.0.5672.126 / Arch Linux "rolling"
 - Chrome 113.0.5672.126 / Arch Linux "rolling"
 - Chrome 113.0.5672.126 / Arch Linux "rolling"

 A set of examples that illustrate how to use TestCafe API
 - Text typing basics (0.001s)
 - Click an array of labels and then check their states (0s)
 - Dealing with text using keyboard (0s)
 - Moving the slider (0.001s)
 - Dealing with text using selection (0s)
 - Handle native confirmation dialog (0.001s)
 - Pick option from select (0s)
 - Filling a form (0s)

 A set of examples that illustrate how to use TestCafe API
 ✓ Text typing basics (1.28s)
 ✓ Click an array of labels and then check their states (0.74s)
 ✓ Dealing with text using keyboard (1.222s)
 ✓ Moving the slider (0.934s)
 ✓ Dealing with text using selection (0.964s)
 ✓ Handle native confirmation dialog (0.866s)
 ✓ Pick option from select (0.661s)
 ✓ Filling a form (3.524s)

 A set of examples that illustrate how to use TestCafe API
 ✓ Text typing basics (3.514s)
 ✓ Click an array of labels and then check their states (3.334s)
 ✓ Dealing with text using keyboard (2.754s)
 ✓ Moving the slider (2.656s)
 ✓ Dealing with text using selection (1.93s)
 ✓ Handle native confirmation dialog (1.633s)
 ✓ Pick option from select (1.124s)
 ✓ Filling a form (3.534s)

 A set of examples that illustrate how to use TestCafe API
 - Text typing basics (3.217s)
 - Click an array of labels and then check their states (3.216s)
 - Dealing with text using keyboard (3.217s)
 - Moving the slider (3.216s)
 - Dealing with text using selection (3.216s)
 - Handle native confirmation dialog (3.215s)
 - Pick option from select (3.215s)
 - Filling a form (3.215s)


 16 passed (11s)
 16 skipped
 ```

### Screenshots

_No response_

### Steps to Reproduce

1. Run example project with `npx testcafe chromium:headless -c 3`

### TestCafe version

2.6.0

### Node.js version

v20.2.0

### Command-line arguments

testcafe chromium:headless -c 3

### Browser name(s) and version(s)

Chromium 113.0.5672.126

### Platform(s) and version(s)

Arch Linux 6.3.4

### Other

_No response_

### PR DESCRIPTION
**Pull request by Artem-Babich**
## Purpose
#7731

## Approach
Set the durationMs value to 0 for skipped tests

## References
#7731

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [x] Make sure that existing tests do not fail

### CODE REVIEW

File: src/reporter/index.ts [hunk 1]
```diff
@@ -347,11 +347,15 @@ export default class Reporter {
     }
 
     private static _createTestRunInfo (reportItem: TestInfo): TestRunInfo {
+        const durationMs = !reportItem.test.skip
```
Comment (miherlosev) [inline src/reporter/index.ts:350]: I propose moving this code to the separate function and split it to the better redability

```js
_getTestDuration (reportItem: TestInfo): number {
    if (reportItem.test.skip)
        return 0;

    return +new Date() - (reportItem.startTime as number);
}
```

File: test/functional/fixtures/reporter/testcafe-fixtures/skipped-tests.js [hunk 2]
```diff
@@ -0,0 +1,22 @@
+fixture `Skipped tests`
+    .page `http://localhost:3000/fixtures/reporter/pages/index.html`;
+test('Simple test', async t => {
+    await t.wait(1);
+    await t.report();
+});
+test.skip('Simple command err test', async t => {
```
Comment (miherlosev) [inline test/functional/fixtures/reporter/testcafe-fixtures/skipped-tests.js:7]: I guess it's too much.
We need covering only two cases: skipped test has duration 0 ms, non-skipped - not 0 ms.

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: test/functional/fixtures/reporter/testcafe-fixtures/skipped-tests.js [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+    await t.click('#non-existing-target');
+});
+
+test.skip('Complex command test', async () => {
```
Comment (miherlosev) [inline test/functional/fixtures/reporter/testcafe-fixtures/skipped-tests.js:11]: I guess you copy tests from somewhere. The `Complex command test` is a strange name for the empty test. Rename the empty tests as `empty test 1`, `empty test 2`, etc.

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by miherlosev — APPROVED** [review]
