### PR TITLE
Fix 'Can't click on an "option" element' (closes #628)

### LINKED ISSUE #628: Can't click on an "option" element

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**
/cc @inikulin @helen-dikareva

### CODE REVIEW

File: src/client/ui/select-element.js [hunk 1]
```diff
@@ -265,3 +265,15 @@ export function switchOptionsByKeys (element, command) {
         }
     }
 }
+
+export function isOptionElementVisible (el) {
```
Comment (inikulin) [inline src/client/ui/select-element.js]: Why it's in UI?

File: src/client/runner/api/actions.js [hunk 2]
```diff
@@ -148,24 +148,14 @@ function ensureElementVisibility (element, actionName, callback) {
     var success = false;
 
     if (domUtils.isOptionElement(element) || domUtils.getTagName(element) === 'optgroup') {
-        var parentSelect = domUtils.getSelectParent(element);
-
-        if (!parentSelect) {
+        if (selectElement.isOptionElementVisible(element))
```
Comment (inikulin) [inline src/client/runner/api/actions.js]: BTW, do we have tests for the legacy API to ensure that we didn't break anything?

**Comment by inikulin** [comment]
\r-

File: src/client/runner/api/actions.js (hunk 2 above)
Comment (AlexanderMoskovkin) [inline src/client/runner/api/actions.js]: Yes, this all is tested in client tests

File: test/functional/fixtures/regression/gh-628/test.js [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+
+describe('[Regression](GH-628)', function () {
+    it('Should click on an "option" element', function () {
+        return runTests('./testcafe-fixtures/click-on-select-child-test.js', 'Click on an "option" element');
+    });
+
+    it('Should fail if try to click on an "option" element in a closed "select" element', function () {
+        return runTests('./testcafe-fixtures/click-on-select-child-test.js', 'Click on an invisible "option" element', {
+            shouldFail: true
+        })
```
Comment (helen-dikareva) [inline test/functional/fixtures/regression/gh-628/test.js]: I think it better looks
```
return runTests('./testcafe-fixtures/click-on-select-child-test.js', 'Click on an invisible "option" element', 
{ shouldFail: true })
```

File: src/client/ui/select-element.js (hunk 1 above)
Comment (AlexanderMoskovkin) [inline src/client/ui/select-element.js]: look at the comment: https://github.com/DevExpress/testcafe/blob/master/src/client/ui/select-element.js#L1
To know is the `<option>` element visible or not we should know is the parent `<select>` element is expanded. During execution we "expand" this element via [testCafeUI function](https://github.com/DevExpress/testcafe/blob/master/src/client/ui/select-element.js#L121), so we can get this info from UI only.
We can refactor all this but it will affect on legacy and the new code and will take some additional time

File: test/functional/fixtures/regression/gh-628/test.js (hunk 3 above)
Comment (inikulin) [inline test/functional/fixtures/regression/gh-628/test.js]: Nah, just keep it as is. it will be screwed up by WebStorm auto-formatting anyway

**Comment by helen-dikareva** [comment]
lgtm

File: test/functional/fixtures/regression/gh-628/test.js [hunk 4]
```diff
@@ -0,0 +1,19 @@
+var expect = require('chai').expect;
+
+describe('[Regression](GH-628)', function () {
```
Comment (inikulin) [inline test/functional/fixtures/regression/gh-628/test.js]: It's better be moved to `Regression` sub-fixture of `t.click`. We create dedicated fixtures only for tests that involve different API.

**Comment by AlexanderMoskovkin** [comment]
FPR

File: src/client/ui/select-element.js (hunk 1 above)
Comment (inikulin) [inline src/client/ui/select-element.js]: Ok

**Comment by inikulin** [comment]
lgtm
