### PR TITLE
Replace the BOM symbol when reading a file (closes #212)

### LINKED ISSUE #212: Test run failed when the test_config.json has the BOM symbol
Check also files with helpers and wrappers

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**
/cc @inikulin

### CODE REVIEW

File: src/utils/read-file.js [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+import promisify from 'es6-promisify';
+
+var readFile = promisify(fs.readFile);
+
+export default async function (file) {
+    var data = await readFile(file);
+
+    //NOTE: removing byte order mark (BOM)
+    return data.toString().replace(/^\uFEFF/, '');
+};
```
Comment (inikulin) [inline src/utils/read-file.js]: Let's move it to the utils inside `compiler` since the whole code from there will be moved to the separate package soon. And let's rename it to `readSourceFile`

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
ping @inikulin

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
thanks
