### PR TITLE
Fixed the error in an iframe after the "document.open" call in IE and Edge (close #3343)

### LINKED ISSUE #3343: Error in iFrame on IE and Edge
### What is your Test Scenario?
The tested page is a payment page, implementing CyberSource's [Secure Acceptance workflow](https://apps.cybersource.com/library/documentation/dev_guides/Secure_Acceptance_Checkout_API/html/wwhelp/wwhimpl/js/html/wwhelp.htm#href=introduction.04.3.html) (a payment processor):
- the page contains a form for credit card details
- when submitted, the form is signed by server
- with server's response, the page builds an iFrame to Cybersource API, and push the signed payload
- the iFrame will push transaction outcome using window's postMessage
 
### What is the Current behavior?
Using Edge or IE, the built iFrame fails because of testCafé's injected code:
```js
"TypeError: cannot access property "clientHeight" of a null or undefined reference
at h (eval code:11:10347)
at a (http://192.168.10.177:64304/testcafe-ui.js:1:21034)
at e (http://192.168.10.177:64304/testcafe-ui.js:1:18357)
at o.prototype.start (http://192.168.10.177:64304/testcafe-driver.js:1:57797)
at Anonymous function (eval code:23:5)
at Anonymous function (eval code:13:6)
at eval code (eval code:12:2)
at t.prototype.iframeReadyToInitHandler (http://192.168.10.177:64304/hammerhead.js:5:4814)
at e.prototype.emit (http://192.168.10.177:64304/hammerhead.js:10:19304)
at t.prototype.\_emitEvents (http://192.168.10.177:64304/hammerhead.js:5:3511)"
```
Please note this is not happening without testCafé. When I manually submit the form on those browsers, it works as expected.

**Another important finding: this seems a regression introduced with 0.23.3.
With versions up to 0.23.2 work as expected.**
 
### What is the Expected behavior?
As for chromium-based browsers and firefox, the iFrame should not receive any error.
 
### What is your web application and your TestCafe test code?
Unfortunately, I cannot share code at the moment.
I'll try to make a test case in the near future.
 
### Your Environment details:
 
* testcafe version:                  0.23.3 (also broken with 1.0.0-alpha.2)
* node.js version:                   8.15.0
* command-line arguments:   testcafe ie ./end-to-end/tests/**/*.js --skip-js-errors
* browser name and version: IE 11.523.17134.0, Edge 42.17134.1.0
* platform and version:          Windows 10 Pro
* other:                                  probably introduced with 0.23.3: previous versions used to work

### PR DESCRIPTION
**Pull request by LavrovArtem**

### CODE REVIEW

File: test/functional/fixtures/regression/gh-3343/testcafe-fixtures/index.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
+import { Selector } from 'testcafe';
+
+fixture `Should not raise an error when an iframe is rewrited`
```
Comment (kirovboris) [inline test/functional/fixtures/regression/gh-3343/testcafe-fixtures/index.js]: /cc @VasilyStrelyaev 
Check strings please.
