### PR TITLE
fix 'Testcafe hungs if the window closed immediately after opening' (close #3762)

### LINKED ISSUE #3762: Testcafe scripts always switches to newly opened window
### What is your Test Scenario?

 browse the page which has pop up blocker checker on load and observe that testcafe switches to pop up blocker checker window instead of main page
### What is the Current behavior?

 Test cafe switches to newly opened window instead of staying in browsed page
### What is the Expected behavior?

 It should switch to window if we have script to that. or at least i should be able to close the other window
### What is your web application and your TestCafe test code?

https://pegasus5.qa.pegasus.pearsoncmg.com/Pegasus/frmLogin.aspx?s=3

 
```js
 import { ClientFunction } from 'testcafe';

fixture `My second fixture`
    .page `https://pegasus5.qa.pegasus.pearsoncmg.com/Pegasus/frmLogin.aspx?s=3`;
   
    const getLocation = ClientFunction(() => window.location.href);
    test('second test', async t => {
        await t
        //.expect(getLocation()).contains('about:blank')
        //.expect(getLocation()).contains('pegasus')
        .wait(15000);
        //await (()=>window.close());
            //const goBack=ClientFunction(()=>window.history.back());
            //await goBack();
            //await t.expect(getLocation()).contains('pegasus');
           await t.typeText('#username','test')
            .click('#mainButton');
    });
```

### Steps to Reproduce:

1. run the above code
2. it will browse the url ,now there is a pop up blocker window which opens and closes automatically when i browse manually.if i run through test cafe,it will switch to that pop up and blank page will be loaded
3. I tried using window.close ,window.history etc...but whatever I may do,it will browse and switch to newly opened window and i cant proceed further
 
### Environment details:
 
* testcafe version:  0.20.5                 
* node.js version:     v10.0.0               
* command-line arguments:  
* browser name and version: chrome 73 
* platform and version:  win 10        
* other:

### PR DESCRIPTION
**Pull request by miherlosev**

### CODE REVIEW

File: src/client/driver/driver-link/window/child-window-closed-before-switching-error.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+export default class ChildWindowClosedBeforeSwitchingError extends Error {
+    constructor () {
+        super();
+
+        // NOTE: https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work
```
Comment (AndreyBelym) [inline src/client/driver/driver-link/window/child-window-closed-before-switching-error.js]: Due to this limitation on the client side, we use the special [isTestCafeError](https://github.com/DevExpress/testcafe/blob/master/src/errors/test-run/index.js#L11) property to detect our custom errors. So maybe it's better to subclass `TestRunErrorBase` to avoid messing with prototypes directly?

Comment (miherlosev) [reply src/client/driver/driver-link/window/child-window-closed-before-switching-error.js]: `ChildWindowClosedBeforeSwitchingError` inherits the `Error` class only for semantic purposes.
`TestRunErrorBase` contains the `code`, `callsite` and `isTestCafeError` properties. I will not use one of these properties.
So, I propose to not inherit the `ChildWindowClosedBeforeSwitchingError` class from any class at all.
```js
export default class ChildWindowClosedBeforeSwitchingError {
}
```
That do you think about it?

Comment (miherlosev) [reply src/client/driver/driver-link/window/child-window-closed-before-switching-error.js]: ping @AndreyBelym

**Comment by miherlosev** [comment]
@VasilyStrelyaev Check please this error message - https://github.com/DevExpress/testcafe/pull/4786/files#diff-247c66d328cd46fdca1b97d218b1a1c4R336

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

File: src/errors/test-run/templates.js [hunk 2]
```diff
@@ -330,5 +330,9 @@ export default {
 
     [TEST_RUN_ERRORS.closeChildWindowError]: () => `
         An error occurred while closing child windows.
+    `,
+
+    [TEST_RUN_ERRORS.childWindowClosedBeforeSwitchingError]: () => `
+        The child window was closed before switching to it.
```
Comment (VasilyStrelyaev) [inline src/errors/test-run/templates.js]: `        The child window was closed before TestCafe could switch to it.`

**Comment by miherlosev** [comment]
@testcafe-build-bot retest
