### PR TITLE
fix " Wrong duplicated scripts calculation'' (close #4116)

### LINKED ISSUE #4116: Client scripts: wrong duplicated scripts calculation
Warnings (1):
 --
  You injected the following client script several times:
   "{ path: 'C:\work\backup\testcafe4\node_modules\moment\moment.js' }"

fixture `local`
    .page `http://localhost/testcafe`
    .clientScripts(
        {
            page:   'https://devexpress.github.io/testcafe/documentation/getting-started/',
            module: 'moment'
        },
        {
            page:   /https:\/\/www.google.com/,
            module: 'moment'
        }
    );

### PR DESCRIPTION
**Pull request by miherlosev**
@helen-dikareva @AndreyBelym

### CODE REVIEW

File: src/custom-client-scripts/utils.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ export function setUniqueUrls (collection) {
 
 export function findProblematicScripts (collection) {
     const nonEmptyScripts              = collection.filter(s => !!s.content);
-    const scriptsWithDuplicatedContent = getDuplicatedScripts(nonEmptyScripts, s => s.content);
+    const scriptsWithDuplicatedContent = getDuplicatedScripts(nonEmptyScripts, s => s.content + s.page.toString());
```
Comment (AndreyBelym) [inline src/custom-client-scripts/utils.js]: Looks like a hack. Script's content can be very large. This sum can lead to performance degradation and memory leaks, can we avoid it somehow?

Comment (miherlosev) [reply src/custom-client-scripts/utils.js]: Theoretically you are right.  But I guess we should wait until the first customer issue, because we don't know now with which amount of client scripts customers will operate.

> can we avoid it somehow?
We can calculate hash of the script content and group by this.

Comment (helen-dikareva) [reply src/custom-client-scripts/utils.js]: For me it would be better if we show a warning when we really inject the same script to a page with particular url. I mean, as far as I can see if we set the same page by url and by some RegExp we can't detect this 'overinjecting'. Correct me if I'm wrong.

Comment (miherlosev) [reply src/custom-client-scripts/utils.js]: @helen-dikareva 

> For me it would be better if we show a warning when we really inject the same script to a page with particular url.

We show such warning - https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/api/es-next/custom-client-scripts/test.js#L41

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

File: src/custom-client-scripts/utils.js (hunk 1 above)
Comment (miherlosev) [reply src/custom-client-scripts/utils.js]: @AndreyBelym 

I will rewrite the duplicated script calculation using the hash. It's faster to do than discuss.

**Comment by miherlosev** [comment]
@AndreyBelym @helen-dikareva FPR

File: test/server/custom-client-scripts-test.js [hunk 2]
```diff
@@ -222,6 +222,27 @@ describe('Client scripts', () => {
                     });
             });
 
+            it('Duplicated content for the several pages', () => {
+                const scripts = [
+                    { content: '1' },
+                    { content: '1', page: 'https://example.com' },
```
Comment (AndreyBelym) [inline test/server/custom-client-scripts-test.js]: This should cause the warning too.

**Comment by miherlosev** [comment]
FPR @helen-dikareva @AndreyBelym

**Comment by miherlosev** [comment]
ping @helen-dikareva @AndreyBelym

**Comment by helen-dikareva** [comment]
I'm in progress

File: src/custom-client-scripts/utils.js (hunk 1 above)
Comment (helen-dikareva) [reply src/custom-client-scripts/utils.js]: I think that the current solution is quite enough, but I meant showing warning for the following case (in [my comment])(https://github.com/DevExpress/testcafe/pull/4118#discussion_r311535403)
```js
fixture `f`
    .page `https://devexpress.github.io/testcafe/documentation/getting-started/`;

test.clientScripts([
    {
        page:   'https://devexpress.github.io/testcafe/documentation/getting-started/',
        module: 'lodash'
    },
    {
        page:   /getting-started/,
        module: 'lodash'
    }
])('t1', async t => {
    await t.click('body');
});

```

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest
