### PR TITLE
fix `key` property of KeyboardEvent in Safari (closes #3282)

### LINKED ISSUE #3282: Safari key presses are empty (KeyboardEvent.code, KeyboardEvent.key)
### What is your Test Scenario?
We use key presses (1 to 4) to pin a number of viewports.
 
### What is the Current behaviour?
Key presses are not acknowledged by Safari -> key and code are empty (see screenshot) => viewports are unpinned.
Manual keypresses do work. 

### What is the Expected behaviour?
Key presses are acknowledged and viewports are pinned -> Key presses work on Edge, Firefox and Chrome. 

### What is your web application and your TestCafe test code?
await t.pressKey('1');

image

### Your Environment details:
 
* testcafe version:                   0.23.3
* node.js version:                    v8.11.3
* browser name and version: Safari 12.02.2
* platform and version:          macOS 10.14.2

### PR DESCRIPTION
**Pull request by AlexKamaev**

### CODE REVIEW

File: src/client/automation/playback/press/key-press-simulator.js [hunk 1]
```diff
@@ -73,10 +72,10 @@ export default class KeyPressSimulator {
     }
 
     _addKeyPropertyToEventOptions (eventOptions) {
-        if (keyIdentifierRequiredForEvent())
+        if (browserUtils.isSafari)
```
Comment (miherlosev) [inline src/client/automation/playback/press/key-press-simulator.js]: I guess we should use the feature detection in this case:
```js
if ('key' in KeyboardEvent.prototype)
   eventOptions.key = ...

if ('keyIdentifier' in KeyboardEvent.prototype)
   eventOptions.keyIdentifier = ...
```

Comment (AlexKamaev) [reply src/client/automation/playback/press/key-press-simulator.js]: ok
