### PR TITLE
Fix unstable functional test, closes #847

### LINKED ISSUE #847: Move automation works wrong if moving from iframe to an element requires page scrolling

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**
/cc @inikulin @georgiy-abbasov 
Sometimes the DOMContentLoaded event raises too late, as a result the iframe is empty when we are going to click inside it

### CODE REVIEW

**Comment by inikulin** [comment]
@AlexanderMoskovkin Seems like we have opposite results

**Comment by AlexanderMoskovkin** [comment]
nope. I've forgotten to update callsites.

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by inikulin** [comment]
@AlexanderMoskovkin Let's run it one more time, to ensure that it fixes instability
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
failed on iOS. Will be investigated

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
functional tests are ok (task was failed because of unstable qunit).
The PR is approved by @VasilyStrelyaev 
/cc @helen-dikareva @georgiy-abbasov

File: src/client/automation/playback/move.js [hunk 1]
```diff
@@ -154,9 +155,10 @@ export default class MoveAutomation {
         var intersectionPoint = getLineRectIntersection(startPoint, endPoint, iframeRectangle);
 
         var moveOptions = new MoveOptions({
-            modifiers: e.message.modifiers,
-            offsetX:   intersectionPoint.x - iframeRectangle.left,
-            offsetY:   intersectionPoint.y - iframeRectangle.top
+            modifiers:     e.message.modifiers,
+            offsetX:       intersectionPoint.x - iframeRectangle.left,
+            offsetY:       intersectionPoint.y - iframeRectangle.top,
+            skipScrolling: true
```
Comment (helen-dikareva) [inline src/client/automation/playback/move.js]: Why we shouls not set `skipScrolling` flag for `onMoveToIframeRequest `?

**Comment by inikulin** [comment]
@AlexanderMoskovkin Can you elaborate please on how it fixes issue with tests? Also, as far as I understand `skipScrolling` is not a part of public API, but it's in options object that contains only public API options. I believe we should move it to other parameters object

**Comment by helen-dikareva** [comment]
rebase will be required

**Comment by AlexanderMoskovkin** [comment]
@inikulin 
>  Can you elaborate please on how it fixes issue with tests?

Oh, yes, I've forgotten to explain this. I've changed the test page markup to fix it. But this helped me to find a new issue (#847). So this pull request contains page markup changing to fix the unstable test and fix for the #847

File: src/client/automation/playback/move.js (hunk 1 above)
Comment (AlexanderMoskovkin) [inline src/client/automation/playback/move.js]: agree, we should

**Comment by inikulin** [comment]
@AlexanderMoskovkin Can we add code comment that explains why we need to disable scrolling with reference to the issue? Because it's not quite clear from code, so let's take care of future us.

**Comment by georgiy-abbasov** [comment]
@AlexanderMoskovkin, just rebase on master

File: src/client/automation/playback/move.js [hunk 2]
```diff
@@ -97,7 +98,11 @@ export default class MoveAutomation {
         var moveOptions = new MoveOptions({
             modifiers: e.message.modifiers,
             offsetX:   intersectionRelatedToIframe.x + iframeBorders.left + iframePadding.left,
-            offsetY:   intersectionRelatedToIframe.y + iframeBorders.top + iframePadding.top
+            offsetY:   intersectionRelatedToIframe.y + iframeBorders.top + iframePadding.top,
+
+            // NOTE: we should not run scrolling because it was scrolled to the
+            // target element in the active window before the request (GH-847)
```
Comment (VasilyStrelyaev) [inline src/client/automation/playback/move.js]:
```
            // NOTE: we should not perform scrolling because the active window was already
            // scrolled to the target element before the request (GH-847)
```

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
FPR
/cc @georgiy-abbasov
