### PR TITLE
Fixed raising `click` and `dblclick` events in automations (closes #851)

### LINKED ISSUE #851: Fix emulation of click for click automation
Click should be emulated in non-FF browsers in next case: if initial target and top element (which appears after mousedown) have common parent - it'll be target for click.

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @inikulin, @AlexanderMoskovkin, @helen-dikareva

### CODE REVIEW

**Comment by georgiy-abbasov** [comment]
FPR

File: src/client/automation/playback/click/index.js [hunk 1]
```diff
@@ -54,7 +53,7 @@ export default class ClickAutomation {
             mousedownPrevented:      false,
             blurRaised:              false,
             simulateDefaultBehavior: true,
-            skipClick:               false
+            clickElement:            false
```
Comment (helen-dikareva) [inline src/client/automation/playback/click/index.js]: use `null`

File: src/client/automation/playback/click/index.js [hunk 2]
```diff
@@ -222,21 +221,43 @@ export default class ClickAutomation {
...
-                if (this.eventArgs.element !== this.clickEventElement) {
-                    this.eventState.skipClick = browserUtils.isFirefox ||
-                                                !this.clickEventElement.contains(this.eventArgs.element) ||
-                                                domUtils.isEditableFormElement(this.eventArgs.element);
-                }
-                else {
-                    this.eventState.skipClick = !browserUtils.isFirefox &&
-                                                !arrayUtils.equals(this.targetElementParentNodes, domUtils.getParents(this.eventArgs.element));
-                }
+                this.eventState.clickElement = this._getElementForClick(this.eventState.clickElement, this.eventArgs.element,
```
Comment (helen-dikareva) [inline src/client/automation/playback/click/index.js]: Why we need to send `this.eventState.clickElement, this.eventArgs.element, ...` in not static method? We can use it without args

File: test/functional/fixtures/regression/gh-851/test.js [hunk 3]
```diff
@@ -0,0 +1,5 @@
+describe('[REGRESSION](GH-851)', function () {
```
Comment (helen-dikareva) [inline test/functional/fixtures/regression/gh-851/test.js]: use `[Regression]` to unify test naming

File: src/client/automation/playback/click/index.js [hunk 4]
```diff
@@ -222,21 +221,43 @@ export default class ClickAutomation {
         return focusAndSetSelection(elementForFocus, simulateFocus, this.caretPos);
     }
 
+    _getElementForClick (targetElement, topElement, targetElementParentNodes, topElementParentNodes) {
```
Comment (AlexanderMoskovkin) [inline src/client/automation/playback/click/index.js]: I suppose we have too complicated naming. 
a) I don't know what does it mean: `this.eventState.clickElement`. It maybe `elementForClick`. But it's strange to call like `this._getElementForClick(elementForClick)`..
b) what the difference between `targetElement` and `topElement`? `targetElement` was a top element before mousedown too.

So, my proposals: 
rename `this.eventState.clickElement` -> `this.eventState.mouseDownElement`
rename `this.targetElementParentNodes` -> `this.mousedownElementParentNodes`

so, this function will be `_getElementForClick(mouseDownElement, topElement)`

You need not send `targetElementParentNodes` because you can use `this.mousedownElementParentNodes`.
And you need not send `topElementParentNodes`, you just call `domUtils.getParents(topElement)` here

Comment (AlexanderMoskovkin) [inline src/client/automation/playback/click/index.js]: @helen-dikareva @georgiy-abbasov  Hmmm. just read your discussion. You are right there are no reason to send this vars to a non-static method. But it will be difficult to understand that `this.eventArgs.element` is actually 'element before click event'.. Maybe it's better to do this method static?
```js
static _getElementForClick(mousedownElement, topElement, mousedownElementParents)
```

File: src/client/automation/playback/click/index.js [hunk 5]
```diff
@@ -222,21 +221,43 @@ export default class ClickAutomation {
...
+                return targetElement;
+
+            if (topElement.contains(targetElement))
+                return topElement;
+
+            // NOTE: If elements are not in parent relationship, non-ff browsers
+            // are raising`click` event for their common parent.
+            var commonElement = arrayUtils.getCommonElement(topElementParentNodes, targetElementParentNodes);
+
+            if (!commonElement)
```
Comment (AlexanderMoskovkin) [inline src/client/automation/playback/click/index.js]: What situation it's possible in? I suppose they should have at least one common element - body

File: src/client/automation/playback/click/index.js (hunk 4 above)
Comment (helen-dikareva) [inline src/client/automation/playback/click/index.js]: may be

Comment (georgiy-abbasov) [inline src/client/automation/playback/click/index.js]: I prefer static

Comment (AlexanderMoskovkin) [inline src/client/automation/playback/click/index.js]: great! let's do this

**Comment by georgiy-abbasov** [comment]
FPR

File: test/functional/fixtures/regression/gh-851/test.js [hunk 6]
```diff
@@ -0,0 +1,5 @@
+describe('[Regression](GH-851)', function () {
+    it('Should call click for common parent element', function () {
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/regression/gh-851/test.js]: You've added code with a lot of conditions. I suppose we should have several tests for them. And at least one test for dblclick changes.

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by georgiy-abbasov** [comment]
FPR

File: test/functional/fixtures/regression/gh-851/test.js [hunk 7]
```diff
@@ -0,0 +1,17 @@
+describe('[Regression](GH-851)', function () {
+    it('Should raise click for common parent element', function () {
+        return runTests('testcafe-fixtures/index.test.js', 'Raise click for common parent', { skip: ['firefox', 'firefox-osx'] });
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/regression/gh-851/test.js]: it's all ok, but I suppose we should add separate tests for `firefox` since it has a different behavior

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by georgiy-abbasov** [comment]
\cc @inikulin

**Comment by georgiy-abbasov** [comment]
ping @inikulin, @VasilyStrelyaev

File: src/client/automation/playback/click/index.js [hunk 8]
```diff
@@ -222,21 +222,39 @@ export default class ClickAutomation {
...
+
+        if (!areElementsSame) {
+            if (mouseDownElement.contains(topElement) && !domUtils.isEditableFormElement(topElement))
+                return mouseDownElement;
+
+            if (topElement.contains(mouseDownElement))
+                return topElement;
+
+            // NOTE: If elements are not in parent relationship, non-ff browsers
+            // are raising`click` event for their common parent.
```
Comment (VasilyStrelyaev) [inline src/client/automation/playback/click/index.js]:
```
            // NOTE: If elements are not in the parent-child relationships, non-ff browsers
            // raise the 'click' event for their common parent.
```

File: src/client/automation/playback/click/index.js [hunk 9]
```diff
@@ -222,21 +222,39 @@ export default class ClickAutomation {
...
+            return arrayUtils.getCommonElement(topElementParentNodes, mouseDownElementParentNodes);
+        }
+
+        // NOTE: If target element and top element are same, non-FF browsers are dispatching `click`
+        // event on condition, that target element hasn't changed it position in DOM after mousedown.
```
Comment (VasilyStrelyaev) [inline src/client/automation/playback/click/index.js]:
```
        // NOTE: In case the target element and the top element are the same, non-FF browsers are dispatching the 'click'
        // event if the target element hasn't changed its position in the DOM after mousedown.
```

File: src/client/automation/playback/dblclick.js [hunk 10]
```diff
@@ -102,19 +102,19 @@ export default class DblClickAutomation {
         return clickAutomation
             .run()
             .then(() => {
-                this.eventState.skipClick = clickAutomation.eventState.skipClick;
-                this.eventArgs            = clickAutomation.eventArgs;
+                // NOTE: We should raise `dblclick` event on element, which
+                // actually has been clicked in second click automation.
```
Comment (VasilyStrelyaev) [inline src/client/automation/playback/dblclick.js]:
```
                // NOTE: We should raise the `dblclick` event on an element that
                // has been actually clicked during the second click automation.
```

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
lgtm
