### PR TITLE
fire `beforeInput` (closes #4486 after hh is published)

### LINKED ISSUE #4486: t.typeText() function does not fire beforeInput event on input.
### What is your Test Scenario?
I have an input and some functionality in beforeInput event handler, that prevents characters other than digits to be stored into value. Once text with incorrect characters is typed into the input, the value should ignore them and contain only digits. I need the beforeInput event specifically for typing on Android keyboard, which works badly with KeyPress, KeyUp and KeyDown. 
 
### What is the Current behavior?
.typeText() types correctly text into input, but beforeinput event is never called, so the stored value is not changed.
 
### What is the Expected behavior?
Typing into input should fire same events as in manual tests on Chrome.
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):
I made a simple Stackblitz use case.
https://stackblitz.com/edit/angular-xcfta5?file=src%2Fapp%2Ftestfile.ts

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import {Selector} from 'testcafe';
 fixture `Input type number`
    .page(`https://angular-xcfta5.stackblitz.io`);
test.only('Should test that the value contains only digits', async () => {
    await t
        .typeText(Selector('#nativeInput'), 'abc25')
        .expect(Selector('#inputString').value).eql('25');
});
```
</details>

### Steps to Reproduce:

1. Go to the stackblitz example
2. Type text  'abc25' into the input
3. You can see that below the input 25 would be shown as the value stored.
4. Run the test
5. See that the value would be undefined because .typeText does not react to beforeinput event
 
### Your Environment details:
 
* testcafe version:                   1.2.1
* node.js version:                    10.16.0
* command-line arguments:  testcafe chrome test.ts
* browser name and version: Chrome 78, Android Chrome 78
* platform and version:          Win10, Android 9

### PR DESCRIPTION
**Pull request by AlexKamaev**
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event

The `beforeInput` events fires only in Chrome and Safari.
However, the order of events is different.
In Chrome the order is `beforeinput - textInput - input`
In Safari - `textInput - beforeinput - input`

Any preceding event can prevent the next one. This behavior is shown in tests.
The `beforeinput` event handler has an argument of `InputEvent`. IE/Edge does not support `InputEvent`. Firefox supports `InputEvent` but does no support `beforeinput`

### CODE REVIEW

File: src/client/automation/playback/type/type-text.js [hunk 1]
```diff
@@ -109,6 +109,10 @@ function _excludeInvisibleSymbolsFromSelection (selection) {
     return selection;
 }
 
+function simulateBeforeInput (element, text) {
```
Comment (helen-dikareva) [inline src/client/automation/playback/type/type-text.js]: Can we get rid of `simulateBeforeInput` and call `eventSimulator.beforeInput` directly?

File: test/functional/fixtures/regression/gh-4486/testcafe-fixtures/index.js [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+    { type: 'textInput', data: '2' },
+    { type: 'textInput', data: '3' }
+];
+
+test(`beforeinput`, async t => {
+    await t.typeText('#input1', '123');
+
+    const log = await getEventLog();
+
+    if (t.browser.alias === 'chrome')
```
Comment (helen-dikareva) [inline test/functional/fixtures/regression/gh-4486/testcafe-fixtures/index.js]: Can we merge these conditions?

File: test/functional/fixtures/regression/gh-4486/testcafe-fixtures/index.js [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+        await t.expect(log).eql(expectedOnlyBeforeInput);
+    if (t.browser.alias === 'safari')
+        await t.expect(log).eql(expectedAllEvents);
+
+    await t.expect(Selector('#input2').value).eql('');
+});
+
+test(`Prevent textInput`, async t => {
```
Comment (helen-dikareva) [inline test/functional/fixtures/regression/gh-4486/testcafe-fixtures/index.js]: I think it would be better to write unit tests for the click automation instead of these functional ones

Comment (AlexKamaev) [reply test/functional/fixtures/regression/gh-4486/testcafe-fixtures/index.js]: It definitely would

File: src/client/automation/playback/type/type-text.js (hunk 1 above)
Comment (AlexKamaev) [reply src/client/automation/playback/type/type-text.js]: we can

File: test/functional/fixtures/regression/gh-4486/testcafe-fixtures/index.js (hunk 2 above)
Comment (AlexKamaev) [reply test/functional/fixtures/regression/gh-4486/testcafe-fixtures/index.js]: Of course, thank for pointing to this

Comment (AlexKamaev) [reply test/functional/fixtures/regression/gh-4486/testcafe-fixtures/index.js]: Any way I'll remove this test ;)

File: test/client/fixtures/automation/type-test.js [hunk 4]
```diff
@@ -503,6 +503,120 @@ $(document).ready(function () {
         });
     }
 
+    if (nativeMethods.WindowInputEvent && !browserUtils.isFirefox) {
+        asyncTest('Should fire `beforeInput` event', function () {
+
```
Comment (helen-dikareva) [inline test/client/fixtures/automation/type-test.js]: (minor) an extra line

File: src/client/automation/playback/type/type-text.js [hunk 5]
```diff
@@ -219,12 +219,20 @@ function _typeTextToContentEditable (element, text) {
...
-    let startSelection    = textSelection.getSelectionStart(element);
-    let endSelection      = textSelection.getSelectionEnd(element);
-    const isInputTypeNumber = domUtils.isInputElement(element) && element.type === 'number';
-    const needProcessInput  = simulateTextInput(element, text);
+    const elementValue         = domUtils.getElementValue(element);
+    const textLength           = text.length;
+    let startSelection         = textSelection.getSelectionStart(element);
+    let endSelection           = textSelection.getSelectionEnd(element);
+    const isInputTypeNumber    = domUtils.isInputElement(element) && element.type === 'number';
+    const needProcessTextInput = !browserUtils.isChrome || eventSimulator.beforeInput(element, text);
```
Comment (kirovboris) [inline src/client/automation/playback/type/type-text.js]: I rarely review the automation codebase, but seriously, I have no faintest idea why we should check if the browser is chrome. If you find any kind of browser-specific behavior, please add a comment. It can save a lot of time later.
E.g., I'd like to see this link in the comment https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event

Also, I think the pr summary should be obligatory.

Comment (AlexKamaev) [reply src/client/automation/playback/type/type-text.js]: I added description to the first post.

>Also, I think the pr summary should be obligatory.

Of course,  I've missed it

Comment (kirovboris) [reply src/client/automation/playback/type/type-text.js]: Thanks 👍

**Comment by AlexKamaev** [comment]
@AndreyBelym review please
