### PR TITLE
Fixed preventing from real actions (closes #591)

### LINKED ISSUE #591: Key pressing doesn't work in ASP Test
`act.press` doesn't work in `ASPxGridViewDemos/Accessibility/KeyboardSupport` test. I've found that the issue is contained in #551.

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @AlexanderMoskovkin, @AndreyBelym

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
we need a simple regression test for this

**Comment by AndreyBelym** [comment]
I'm confirming, that it fixes problem ins ASP test, thanks.

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by AndreyBelym** [comment]
Okay, we have solved my troubles with the ASP test and Saucelabs by just rebooting my machine. LGTM then.

**Comment by georgiy-abbasov** [comment]
\cc @VasilyStrelyaev

File: test/functional/fixtures/regression/gh-591/test.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+it("Press action with CTRL+SHIFT shouldn't be prevented", function () {
```
Comment (VasilyStrelyaev) [inline test/functional/fixtures/regression/gh-591/test.js]: maybe, this will be a bit clearer?
```
it("Pressing CTRL+SHIFT+key combinations shouldn't be prevented", function () {
```

**Comment by VasilyStrelyaev** [comment]
\r-

**Comment by AlexanderMoskovkin** [comment]
lgtm
