### PR TITLE
fix: The 'WebSocket connection closed' error on Chrome 130

### LINKED ISSUE #8286: Tests fail with "Error: WebSocket connection closed" for Chrome 130.0.6723.6 (2024-09-18)
### What is your Scenario?

We run the exact same 170+ TestCafe tests against the latest version of **Chrome** and **Chrome Beta**.

### What is the Current behavior?

Our tests still pass for **Chrome**. However, the majority of them started failing for **Chrome Beta** with the stacktrace below after we upgraded to the version `130.0.6723.6`. That version has been promoted to the _Beta_ channel on September 18, 2024 (see [here](https://chromereleases.googleblog.com/2024/09/chrome-beta-for-desktop-update_18.html)).

```
Error: WebSocket connection closed
at node_modules/chrome-remote-interface/lib/chrome.js:94:35
at Chrome._handleConnectionClose (node_modules/chrome-remote-interface/lib/chrome.js:256:13)
at WebSocket.<anonymous> (node_modules/chrome-remote-interface/lib/chrome.js:243:22)
at WebSocket.emit (node:events:519:28)
at WebSocket.emit (node:domain:488:12)
at WebSocket.emitClose (node_modules/ws/lib/websocket.js:246:10)
at Socket.socketOnClose (node_modules/ws/lib/websocket.js:1150:15)
at Socket.emit (node:events:519:28)
at Socket.emit (node:domain:488:12)
at TCP.<anonymous> (node:net:339:12)
```

### What is the Expected behavior?

Running tests against Chrome `130.0.6723.6` should not trigger `Error: WebSocket connection closed`.

### What is the public URL of the test page? (attach your complete example)

NA

### What is your TestCafe test code?

NA

### Your complete configuration file

_No response_

### Your complete test report

_No response_

### Screenshots

_No response_

### Steps to Reproduce

1.
2.
3.

### TestCafe version

3.6.2

### Node.js version

_No response_

### Command-line arguments

NA

### Browser name(s) and version(s)

_No response_

### Platform(s) and version(s)

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by PavelMor25**
## Purpose
When requesting active tabs in Chrome 130.0.6723.6, a chrome-extension tab is included in the list. A CDP client is created based on this tab, but the tab gets closed, which results in the error.

## Approach
Excluded tabs with `^chrome-extension` URLs from the list of tabs.

## References
closes #8286 

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

File: src/browser/provider/built-in/dedicated/chrome/cdp-client/utils.ts [hunk 1]
```diff
@@ -1,11 +1,17 @@
 import remoteChrome, { TargetInfo } from 'chrome-remote-interface';
 
 const DEVTOOLS_TAB_URL_REGEX = /^devtools:\/\/devtools/;
+// NOTE: Github issue: https://github.com/DevExpress/testcafe/issues/8286
+const CHROME_EXTENSION_TAB_URL_REGEX = /^chrome-extension:\/\//;
+
+function isNotException (url: string): boolean {
```
Comment (AlexKamaev) [inline src/browser/provider/built-in/dedicated/chrome/cdp-client/utils.ts:7]: rename:
`isNotException` -> `isInternalUrl`
refactor:
`!DEVTOOLS_TAB_URL_REGEX.test(url) && !CHROME_EXTENSION_TAB_URL_REGEX.test(url)` ->
`DEVTOOLS_TAB_URL_REGEX.test(url) || CHROME_EXTENSION_TAB_URL_REGEX.test(url)`

**Review by AlexKamaev — APPROVED** [review]

**Review by Bayheck — APPROVED** [review]
