### PR TITLE
fix: ExternalAssertionLibraryError when assertion gets failed in testcafe (close #4613)

### LINKED ISSUE #4613: ExternalAssertionLibraryError when assertion gets failed in testcafe
image

getting assertion on failed assertion
await t.expect(false).ok("response of student school is not in arrayformat");
testcafe 1.7.1

### PR DESCRIPTION
**Pull request by miherlosev**
Changes:
* don't raise an error if it occurred after test function execution.
* add a warning message about assertion placed into the unawaited method

### CODE REVIEW

File: src/notifications/warning-message.ts [hunk 1]
```diff
@@ -46,6 +46,7 @@ export default {
     retryTestPagesIsNotSupported:       'Cannot enable the \'retryTestPages\' option in "{browserAlias}". Please ensure that your version of "{browserAlias}" supports the Service Worker API (https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API).\n',
     browserProviderDropOfPerformance:   'We detected \'{browserName}\' runs slowly. Try to free up or allocate more system resources on its host machine.',
     testsCompilationTakesTooLong:       'Tests took too long to compile ({compileTime}). Ensure the test code has no excessive imports.',
-    deprecatedAPI:                      '{API} is deprecated and will be removed in the next major release. Use {replacement} instead.'
+    deprecatedAPI:                      '{API} is deprecated and will be removed in the next major release. Use {replacement} instead.',
+    unawaitedMethodWithAssertion:       "You used an assertion in the unawaited asynchronous method. Inspect that method's execution chain and add the 'await' keyword where it's necessary."
```
Comment (titerman) [inline src/notifications/warning-message.ts:50]:
```suggestion
    unawaitedMethodWithAssertion:       "An asynchronous method that you do not await includes an assertion. Inspect that method's execution chain and add the 'await' keyword where necessary." 
```

**Review by AlexKamaev — APPROVED** [review]
