### PR TITLE
fix: hangs in an iframe when it redirects to a cross-domain site

### LINKED ISSUE #4232: TestCafe hangs on click of submit button in an iframe when the click is submitting form and redirecting to a page of a different domain
### What is your Test Scenario?
We are testing a page that loads a form in an iframe from source (www.domain1.comapny.com/load).
User completes the form and submit's it to www.domain1.company.com/submit which then redirects to www.domain2.company.com/anotherform(within the same iframe).

Test hangs after submit. It submits and redirects to the new page(i can see in the UI) but is stuck there(window never closes and next steps are not executed).

 
### What is your web application and your TestCafe test code?
Web application is in ruby on rails framework.
 
Your website URL (or attach your complete example):

Unfortunately I can't share the code but I'm happy to share snippets and video if that helps.
Wanted to understand if this is a limitation with testcafe framework as it's redirecting to a cross domain.

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   1.3.0-alpha.1
* node.js version:                    12.9.0
* command-line arguments:  "testcafe chrome -e test.js"
* browser name and version: Chrome Version 74.0.3729.131
* platform and version:          Mac OS Mojave Version 10.14.5
* other:

### PR DESCRIPTION
**Pull request by wentwrong**
## Purpose
TestCafe hangs when click in an iframe redirects to a page on a different domain. It occurs due to the cross-origin iframe's driver not able to read the pending actions from the `ContextStorage` of its parent and because of that the driver doesn't send the "ready" driver status and TestCafe hangs.

## Approach
In the cross-domain iframe we should check that the parent doesn't have pending actions as well. Because the iframe and its parent with different origins doesn't share a common `sessionStorage` (its used under the hood of `ContextStorage`), we should send the message to check if there're some pending actions in the parent's driver.

## References
Fixes #4232 

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [x] Make sure that existing tests do not fail

### CODE REVIEW

File: test/functional/fixtures/regression/gh-4232/testcafe-fixtures/index-test.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import { Selector } from 'testcafe';
+
+fixture `gh-4232`
+    .page `http://localhost:3000/fixtures/regression/gh-4232/pages/index.html`;
+
+test('Click on submit button in an iframe when the click redirecting to a page on a different domain', async t => {
+    const iframe = Selector('#same-domain-iframe');
```
Comment (wentwrong) [inline test/functional/fixtures/regression/gh-4232/testcafe-fixtures/index-test.js:7]:
```suggestion
    const iframe = Selector('#same-domain-iframe', { timeout: 10000 });
```

**Comment by miherlosev** [comment]
I will finish this PR.

**Review by AlexKamaev — APPROVED** [review]
