### PR TITLE
wait for Temp directory is initialized for video recording (closes #3508)

### LINKED ISSUE #3508: Temporary video files are created when running tests with a configuration file and video recording is enabled
### What is your Test Scenario?

Running tests with a config file and video recording enabled.
 
### What is the Current behavior?

Strange temporary video files are created during the test run and no videos are located in the specified folder; e.g.:

tmp-video-5tMTQML.mp4
tmp-video-kKMhFSu.mp4
tmp-video-L4S8VK3.mp4
tmp-video-W1PDY87.mp4
tmp-video-~MQugEC.mp4

### What is the Expected behavior?

No temporary files are created and videos are placed in the specified folder
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example): 
[repro.zip](https://github.com/DevExpress/testcafe/files/2915483/repro.zip)

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 test1.js
import { ClientFunction} from 'testcafe';

fixture `Get sale amount`
    .page('https://js.devexpress.com/');

    const getSaleAmount = ClientFunction(() => {
        const elements = document.querySelector('.dx-datagrid-rowsview').querySelectorAll('td:nth-child(3),td:nth-child(7)');
        const array = [];

        for (let i = 0; i <= elements.length - 2; i+=2) {
            const customerName  = elements[i+1].textContent;
            const saleAmount = elements[i].textContent;

            if (customerName && saleAmount)
                array.push(`Customer ${customerName}: ${saleAmount}`);
        }

        return array;
    });

test('My test', async t => {
    console.log(await getSaleAmount());
});

test2.js
import { Selector} from 'testcafe';

fixture('fixture')
    .page('file:///Temp/!TestCafe/test.html');
	
	
test('Verify states', async t => {
	const elementStyle = await Selector('#targetElement').style;
	await t.expect( elementStyle.color ).eql( "rgb(0, 128, 0)", "the color must be green!");
});

test.html
<div id="targetElement" style="color:green"></div>
```
</details>

<details>
<summary>Your complete test report:</summary>

```
c:\Temp\!TestCafe>testcafe
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 72.0.3626 / Windows 10.0.0
 - Firefox 65.0.0 / Windows 10.0.0

 Get sale amount
[ 'Customer Renewable Supplies: $6,370',
  'Customer Apollo Inc: $4,530',
  'Customer Johnson & Assoc: $1,110',
  'Customer Global Services: $6,600',
  'Customer Health Plus Inc: $2,830',
  'Customer Gemini Stores: $6,770',
  'Customer Discovery Systems: $1,460' ]
[ 'Customer Renewable Supplies: $6,370',
  'Customer Apollo Inc: $4,530',
  'Customer Johnson & Assoc: $1,110',
  'Customer Global Services: $6,600',
  'Customer Health Plus Inc: $2,830',
  'Customer Gemini Stores: $6,770',
  'Customer Discovery Systems: $1,460' ]
 √ My test

 fixture
 √ Verify states


 2 passed (59s)
```
</details>

<details>
<summary>config file:</summary>

```
{
    "browsers": ["chrome", "firefox:headless"],
    "src": ["test1.js", "test2.js"],
    "screenshotPath": "./screens",
    "screenshotPathPattern": "${DATE}_${TIME}/test-${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png",
    "takeScreenshotsOnFails": true,
    "videoPath": "reports/screen-captures",
    "videoOptions": {
        "singleFile": false,
        "failedOnly": true,
        "pathPattern": "${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.mp4"
    },
    "videoEncodingOptions": {
        "r": 20,
        "aspect": "4:3"
    },
    "stopOnFirstFail": false,
    "skipJsErrors": true,
    "skipUncaughtErrors": true,
    "concurrency": 5,
    "selectorTimeout": 3000,
    "assertionTimeout": 1000,
    "pageLoadTimeout": 1000,
    "speed": 1,
}
```
</details>

### Steps to Reproduce:

1. Extract the repro.zip archive
3. Run testcafe command
 
### Your Environment details:
 
* testcafe version:                    1.1.0-rc.1 
* node.js version:                     10.15
* command-line arguments:   testcafe
* browser name and version:  chrome Version 72.0.3626.109 (Official Build) (64-bit)
* platform and version:           Windows 10
* other:                                   none

### PR DESCRIPTION
**Pull request by AlexKamaev**

### CODE REVIEW

File: src/video-recorder/index.js [hunk 1]
```diff
@@ -58,7 +58,10 @@ export default class VideoRecorder {
     }
 
     _assignEventHandlers (browserJob) {
-        browserJob.once('start', this._createSafeListener(this._onBrowserJobStart));
+        browserJob.once('start', this._createSafeListener(() => {
```
Comment (AndreyBelym) [inline src/video-recorder/index.js]: Please add the `async` modifier and add `await this.tempDirectoryInitializedPromise` OR return `this.tempDirectoryInitializedPromise` from the handler.

**Comment by AlexKamaev** [comment]
ping @LavrovArtem
