### PR TITLE
Fix cross-domain iframe focus in Safari

### LINKED ISSUE #4793: Text not entered in to Stripe iFrame with Safari
### What is your Test Scenario?

 I'm trying to run our test code on multiple browsers, specifically entering in CreditCard details on our payment pages.

### What is the Current behavior?

It looks like text isn't being properly entered in to the Stripe payment iframes, on Safari. The same steps are successful in Chrome, Firefox and Edge.

The main concern here is that TestCafe continues on, believing it has actually entered text in to these iframes.
 
### What is the Expected behavior?

 Text should be entered in to Stripe iFrames, regardless of browser. OR, at the least, if TestCafe is unable to locate/interact with the iFrame... it should fail at that point instead of continuing on.

### What is your web application and your TestCafe test code?

<details>
<summary>Your website URL (or attach your complete example): </summary>

You can target our live site, since the issue relates to being unable to enter data in the payment forms:
https://www.change.org/
</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
import { t, Selector } from 'testcafe';

fixture('Join Membership with credit card').page('https://www.change.org/');

test('Guest user clicks contribute directly', async () => {
  await t
    .navigateTo('s/member')
    .expect(Selector('[data-testid="member_landing_page_inline_contribute_button"]').visible)
    .ok();

  await t
    .click(Selector('[data-testid="member_landing_page_inline_contribute_button"]'), { speed: 0.3 })
    .expect(Selector('[data-testid="member_payment_form"]').visible)
    .ok();

  await t
    .click(Selector('[data-testid="payment-option-button-creditCard'))
    .expect(Selector('.iframe-form-element').visible)
    .ok();

  const emailAddressInput = Selector('[data-testid="input_email"]').filterVisible();
  const confirmationEmailInput = Selector('[data-testid="input_confirmation_email"]').filterVisible();
  const firstNameInput = Selector('[data-testid="input_first_name"]');
  const lastNameInput = Selector('[data-testid="input_last_name"]');

  await t
    .typeText(emailAddressInput, 'email@email.com')
    .typeText(confirmationEmailInput, 'email@email.com')
    .typeText(firstNameInput, 'Your')
    .typeText(lastNameInput, 'Name');

  await t
    .switchToIframe(Selector('[data-testid="credit-card-number"] iframe'))
    .typeText(Selector('input[name="cardnumber"]'), '1234123412341234', { replace: true })
    .expect(Selector('input[name="cardnumber"]').value)
    .eql('1234 1234 1234 1234')
    .switchToMainWindow();
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
N/A
```
</details>

<details>
<summary>Your complete test report:</summary>

```
Guest user clicks contribute directly

   1) AssertionError: expected '' to deeply equal '1234 1234 1234 1234'

      Browser: Safari 13.0.5 / macOS 10.15.3

         31 |
         32 |  await t
         33 |    .switchToIframe(Selector('[data-testid="credit-card-number"] iframe'))
         34 |    .typeText(Selector('input[name="cardnumber"]'), '1234123412341234', { replace: true
      })
         35 |    .expect(Selector('input[name="cardnumber"]').value)
       > 36 |    .eql('1234 1234 1234 1234')
         37 |    .switchToMainWindow();
         38 |});
         39 |

         at <anonymous>
      (/Users/rcooper/work/github.com/change/regression-qaa/tests/users/demo.js:36:6)



 1/1 failed (23s)
```
</details>

<details>
<summary>Screenshots:</summary>

```
N/A
```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:  1.8.2                 
* node.js version: 12.14.1                   
* command-line arguments: testcafe safari 
* browser name and version: Safari 13.0.5 
* platform and version: macOS 10.15.3

### PR DESCRIPTION
**Pull request by Ogurecher**
## Purpose
[Safari 13](https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes) does not allow focusing elements inside of cross-domain iframes before the iframe itself is focused.

## Approach
We can focus the iframe before trying to focus the inner element. This should not have side-effects as we focus the element afterwards anyway.

We can't focus the iframe from inside of its context so we need to send a message to the parent context, so that we can focus the iframe there,  and wait for the response.

Possible considerations:
 - Make this logic Safari-exclusive as other browsers work without it

## References
Closes #4793

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [x] Make sure that existing tests do not fail

### CODE REVIEW

File: src/client/automation/utils/utils.js [hunk 1]
```diff
@@ -38,7 +53,13 @@ function setCaretPosition (element, caretPos) {
 }
 
 export function focusAndSetSelection (element, simulateFocus, caretPos) {
-    return new Promise(resolve => {
+    return new Promise(async resolve => {
+        // NOTE: Safari 13 blocks attempts to focus elements inside a third-party iframe before the user interacts with it
+        // https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes
+        // We can work around this restriction by focusing the <iframe> element beforehand
+        if (window.top !== window)
```
Comment (AlexKamaev) [inline src/client/automation/utils/utils.js:60]: Can we use `window.parent` instead of `window.top` here to check if we are in the iframe?

Comment (Ogurecher) [reply src/client/automation/utils/utils.js:60]: I think we can, but `window.top` is used throughout the project.
https://github.com/DevExpress/testcafe/blob/43678b62c2a33685fbdd73dd9c4024c3c9ace776/src/client/automation/playback/scroll.js#L263
https://github.com/DevExpress/testcafe/blob/e7790ccad7a67b3962d7df16c117c88144faed04/src/client/automation/get-element.js#L85
Why is it better to use `window.parent`?

Comment (AlexKamaev) [reply src/client/automation/utils/utils.js:60]: In the next line we send a request to the window parent, but in the `if` condition we check the `window.top` property. I would prefer to have the same properties in the condition and in the request method. 
I understand that your case works correctly, so it's up to you.

Comment (Ogurecher) [reply src/client/automation/utils/utils.js:60]: Personally, I think that we should keep using `window.top !== window` to check if we're in iframe for the consistency purposes (so that it's the same throughout the project).

I can change it to
```js
const isInIframe = window.top !== window;
if (isInIframe)
...
```
if this change makes it look better.

Alternatively, I could add the `isInIframe` function to `./src/utils` and use it to replace all similar conditions.

Comment (AlexKamaev) [reply src/client/automation/utils/utils.js:60]: It's a minor recommendation, so you can use the approach you prefer. I like the idea to extract the `isInIframe` function.

File: src/client/automation/cursor.js [hunk 2]
```diff
@@ -1,8 +1,9 @@
 import testCafeCore from './deps/testcafe-core';
 import testCafeUI from './deps/testcafe-ui';
+import isWindowInIframe from '../../utils/is-window-in-iframe';
 
 const domUtils = testCafeCore.domUtils;
-const cursorUI = window.top === window ? testCafeUI.cursorUI : testCafeUI.iframeCursorUI;
+const cursorUI = !isWindowInIframe(window) ? testCafeUI.cursorUI : testCafeUI.iframeCursorUI;
```
Comment (miherlosev) [inline src/client/automation/cursor.js:6]: `isIframeWindow` is a better name.

**Review by miherlosev — CHANGES_REQUESTED** [review]

**Review by miherlosev — APPROVED** [review]

**Review by AlexKamaev — APPROVED** [review]
