### PR TITLE
Creation of actionElementNotIframeError error fixed (closes #731)

### LINKED ISSUE #731: Incorrect error appears if `github` module function promise rejects
Create a test that uses the [github](https://www.npmjs.com/package/github) module.
Wrap any function from the module that fails with a `Promise` and run it.
The report contains a strange error:
`The action element is expected to be an <iframe>.`

TestCafe version is `0.2.3-alpha`

*Example*
```js
import Github from 'github';

function createRef () {
    var github = new Github({
        version:  '3.0.0',
        protocol: 'https',
        host:     'api.github.com',
        timeout:  5000
    });

    github.authenticate({
        type:  'oauth',
        token: 'sometoken'
    });

    return new Promise((resolve, reject) => {
        github.gitdata.createReference({}, function (err, res) {
            if(err)
                reject(err);
            else
                resolve(res);
        });
    });
}

fixture `myFixture`;

test('myTest', async t => {
    await createRef();
});
```

*Report*
```
$ testcafe chrome D:/Temp/test1/test.js
 Running tests in:
 - Chrome 52.0.2743 / Windows 7 0.0.0

 myFixture
 × myTest

   1) The action element is expected to be an <iframe>.

      Browser: Chrome 52.0.2743 / Windows 7 0.0.0



 1/1 failed (0s)

```

The `createReference` function calling fails with the following error:
```
{ [Error: Empty value for parameter 'user': undefined]
  defaultMessage: 'Bad Request',
  message: 'Empty value for parameter \'user\': undefined',
  code: '400',
  status: 'Bad Request',
  headers: undefined }

```

### PR DESCRIPTION
**Pull request by helen-dikareva**
/cc @inikulin @AlexanderMoskovkin @VasilyStrelyaev

### CODE REVIEW

File: test/server/test-run-error-formatting-test.js [hunk 1]
```diff
@@ -103,7 +103,9 @@ function assertErrorMessage (file, err) {
 
     expect(actual).eql(expectedMsg);
 
-    //NOTE: remove tested messages from list
+    //NOTE: check that list of error types contains error
+    // with this type and remove tested messages from list
+    expect(untestedErrorTypes.indexOf(err.type) !== -1).to.be.ok;
```
Comment (inikulin) [inline test/server/test-run-error-formatting-test.js]: Why we need this check? Is there was some case that we need to check here?

Comment (helen-dikareva) [inline test/server/test-run-error-formatting-test.js]: we get "strange error" because we forgot include type `'actionElementNotIframeError'` in `type.js` https://github.com/DevExpress/testcafe/pull/735/files#diff-9496e797b89e8d22aebbb62b66c64b4aR37

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by inikulin** [comment]
lgtm then

**Comment by helen-dikareva** [comment]
@testcafe-build-bot \retest

**Comment by AlexanderMoskovkin** [comment]
lgtm

File: test/server/test-run-error-formatting-test.js [hunk 2]
```diff
@@ -103,7 +103,9 @@ function assertErrorMessage (file, err) {
 
     expect(actual).eql(expectedMsg);
 
-    //NOTE: remove tested messages from list
+    //NOTE: check that list of error types contains error
+    // with this type and remove tested messages from list
```
Comment (VasilyStrelyaev) [inline test/server/test-run-error-formatting-test.js]: of this type
```
    // NOTE: check that the list of error types contains an error
    // of this type and remove tested messages from the list
```

**Comment by VasilyStrelyaev** [comment]
\r-

**Comment by helen-dikareva** [comment]
FPR

**Comment by helen-dikareva** [comment]
if all's ok, please merge @VasilyStrelyaev

**Comment by VasilyStrelyaev** [comment]
lgtm
