### PR TITLE
Handle errors inside the request hook methods (close #3786)

### LINKED ISSUE #3786: TestCafe huns if the overriden method of the RequestHook raises an error
### What is your Test Scenario?
**edit:** When I added URL Filter to Hook, it's works - so case is only without it.

I'm trying to add custom HTTP header **without any URL filter** to few fixtures or tests.
 
### What is the Current behavior?
The whole fixture couldn't load and hang on TestCafe splash screen with `CONNECTED` information. When I removed `.requestHooks(hook);` from `fixture` or `test` chain, it's work as expected.

When we'll check network info during loading, TestCafe is still sending requests to browser heartbeat (`Request URL: http://192.168.1.183:52055/browser/heartbeat/7bPNpzU`) and get `200 OK` with response but without `url` property value:

```
{  
   "code":"ok",
   "url":""
}
```
 
### What is the Expected behavior?
Fixture or test with `.requestHooks(hook);` method should load and execute properly.
 
### What is your web application and your TestCafe test code?
I'm using your example test and example HTTP request hook to easily allow to reproduce it.
 
Your website URL (or attach your complete example): http://devexpress.github.io/testcafe/example

<details>
<summary>Your complete test code (or attach your test files):</summary>

```js
import { Selector, RequestHook } from 'testcafe';

class MyHeaderHook extends RequestHook {
  constructor() { // btw. TestCafe crew, you could remove constructor from your docs here, it's useless when you're not passing requestFilterRules or responseEventConfigureOpts
    // No URL filtering applied to this hook
    // so it will be used for all requests.
    super();
  }

  onRequest(requestEvent) {
    requestEvent.requestOptions.headers['MyHeader'] = 'MyHeader value';
  }
}

const myHeaderHook = new MyHeaderHook();

fixture`Getting Started`
  .page`http://devexpress.github.io/testcafe/example`
  .requestHooks(myHeaderHook);

test('My first test', async (t) => {
  await t
    .typeText('#developer-name', 'John Smith')
    .click('#submit-button')

    // Use the assertion to check if the actual header text is equal to the expected one
    .expect(Selector('#article-header').innerText).eql('Thank you, John Smith!');
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```
$ ./node_modules/.bin/testcafe scenarios/hook-test.js
The "src" option from the configuration file will be ignored.
 Running tests in:
 - Chrome 74.0.3729 / Mac OS X 10.14.4

 Getting Started
^CStopping TestCafe...
```
I forced exit due to few minutes without any result.
</details>

<details>
<summary>Screenshots:</summary>

Screenshot 2019-05-13 at 11 26 24 AM

</details>

<details>
<summary>Config file:</summary>

```json
{
  "browsers": [ "chrome" ],
  "src": "scenarios",
  "reporter": [
    {
      "name": "spec"
    }
  ],
  "screenshotPath": "screenshots",
  "takeScreenshotsOnFails": true,
  "screenshotPathPattern": "${DATE}_${TIME}/${TEST}/${USERAGENT}/${FILE_INDEX}.png"
}
```
</details>

### Steps to Reproduce:

1. Copy whole fixture with hook class
2. Copy config file to `.testcaferc.json`
3. Run TestCafe via `$ ./node_modules/.bin/testcafe`
4. Check that TestCafe couldn't fixture/test page
 
### Your Environment details:
 
* testcafe version: `1.1.4`
* node.js version: `v10.14.2`
* command-line arguments: -
* browser name and version: `Chrome 74.0.3729`
* platform and version: `Mac OS X 10.14.4`
* other: -

### PR DESCRIPTION
**Pull request by miherlosev**
@AndreyBelym @AlexKamaev @LavrovArtem 

First - this PR, next - https://github.com/DevExpress/testcafe-hammerhead/pull/2036

@VasilyStrelyaev check please messages in the error templates

### CODE REVIEW

File: src/errors/test-run/templates.js [hunk 1]
```diff
@@ -283,5 +283,15 @@ export default {
 
     [TEST_RUN_ERRORS.assertionUnawaitedPromiseError]: err => markup(err, `
         Attempted to run assertions on a Promise object. Did you forget to await it? If not, pass "{ allowUnawaitedPromise: true }" to the assertion options.
+    `),
+
+    [TEST_RUN_ERRORS.requestHookNotImplementedError]: err => markup(err, `
+        You should implement the "${err.methodName}" method of the "${err.hookClassName}" class.
```
Comment (VasilyStrelyaev) [inline src/errors/test-run/templates.js]:
```
        You should implement the "${err.methodName}" method in the "${err.hookClassName}" class.
```

File: src/errors/test-run/templates.js [hunk 2]
```diff
@@ -283,5 +283,15 @@ export default {
...
+    `),
+
+    [TEST_RUN_ERRORS.requestHookUnhandledError]: err => markup(err, `
+        An unhandled error occurred inside the "${err.methodName}" method of the "${err.hookClassName}" class:
```
Comment (VasilyStrelyaev) [inline src/errors/test-run/templates.js]:
```
        An unhandled error occurred in the "${err.methodName}" method of the "${err.hookClassName}" class:
```

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@AndreyBelym @AlexKamaev @LavrovArtem you can review it. I will resolve conflict in the `package.json` file when I update the `testcafe-hammerhead` dependency.

File: src/test-run/index.js [hunk 3]
```diff
@@ -1,4 +1,4 @@
-import { pull as remove } from 'lodash';
+import { pull, remove, chain } from 'lodash';
```
Comment (AlexKamaev) [inline src/test-run/index.js]: I don't really like `pull`, because here we definitely have two versions of `remove`, but since its `lodash` naming let it be so

File: src/test-run/index.js [hunk 4]
```diff
@@ -160,10 +167,22 @@ export default class TestRun extends AsyncEventEmitter {
...
                 onResponse:          hook.onResponse.bind(hook)
-            });
+            }, err => this._onRequestHookMethodError(err, hook));
         });
     }
 
+    _onRequestHookMethodError (event, hook) {
+        let err = event.error;
+
+        if (err instanceof RequestHookNotImplementedMethodError === false) {
```
Comment (AlexKamaev) [inline src/test-run/index.js]: Just proposal, maybe this way is more clear. 
```JS
const isRequestHookNotImplementedMethodError = err instanceof RequestHookNotImplementedMethodError

if (!isRequestHookNotImplementedMethodError ) {
...
}
```

Comment (miherlosev) [reply src/test-run/index.js]: Ok. I will fix it.

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@testcafe-build-bot retest

**Comment by miherlosev** [comment]
@AndreyBelym @LavrovArtem FPR
