### PR TITLE
Preventing real actions has been implemented in client driver (closes #549)

### LINKED ISSUE #549: Prevent real actions during test execution
We should prevent any actions from keyboard and mouse during tests execution to avoid unexpected results.

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @inikulin, @AlexanderMoskovkin, @helen-dikareva

### CODE REVIEW

**Comment by inikulin** [comment]
The thing that really pissed off in previous versions: can we allow openning dev tools via shortcuts - 
<kbd>F12</kbd> for Windows, <kbd>Cmd</kbd>+<kbd>Option</kbd>+<kbd>I</kbd> for Chrome and Safari on MacOS and <kbd>Cmd</kbd>+<kbd>Option</kbd>+<kbd>K</kbd> for Firefox on MacOS?

**Comment by AlexanderMoskovkin** [comment]
Sure, we can add some allowed keys/combinations

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

File: src/client/core/prevent-real-events.js [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+    if (buttonF12pressed || hotkeyShortcut || isKeypressEvent)
+        stopEventPropagation();
+}
+
+export default function preventRealEvents () {
+    listeners.initElementListening(window, PREVENTED_EVENTS);
+    listeners.addFirstInternalHandler(window, PREVENTED_EVENTS, preventRealEventHandler);
+
+    // NOTE: We should place this internal handler at first to allow devTools hotkey combinations.
+    listeners.addFirstInternalHandler(window, KEY_EVENTS, hotkeyHandler);
```
Comment (AlexanderMoskovkin) [inline src/client/core/prevent-real-events.js]: We need no an additional handler. We can make it easier. Just add to the `preventRealEventHandler` something like the following:
```js
if(/^key/.test(e.type) && checkDevToolsShortcut()) {
    stopEventPropagation();
    return;
}
```

File: src/client/core/prevent-real-events.js [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+
+    // NOTE: To enable hotkeys we should allow specified keyboard events to pass the capture phase.
+    // Most browsers listen for keydown and keyup events, meanwhile Firefox and Safari will not process
+    // the hotkey combination until the keypress event will be raised (this event will be raised, if we
+    // called stopEventPropagation() for our specific keydown and keyup events before).
+
+    var buttonF12pressed = e.keyCode === F12_KEY_CODE;
+    var hotkeyShortcut   = (e.type === 'keydown' || e.type === 'keyup') &&
+                           DEVTOOLS_HOTKEY_KEYCODES.indexOf(e.keyCode) > -1 &&
+                           ((e.shiftKey && e.ctrlKey) || e.altKey);
```
Comment (AlexanderMoskovkin) [inline src/client/core/prevent-real-events.js]: add more specified condition: `browserUtils.isMacPlatform && e.altKey`

File: src/client/core/prevent-real-events.js [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+    var isKeypressEvent  = e.type === 'keypress' && (browserUtils.isFirefox || browserUtils.isSafari);
```
Comment (AlexanderMoskovkin) [inline src/client/core/prevent-real-events.js]: I suppose we need no this differentiation, use this logic for `keydown, keyup, keypress` event in all browsers

File: src/client/core/prevent-real-events.js [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+
+
+function hotkeyHandler (e, dispatched, preventEvent, cancelHandlers, stopEventPropagation) {
+    if (dispatched)
+        return;
+
+    // NOTE: To enable hotkeys we should allow specified keyboard events to pass the capture phase.
+    // Most browsers listen for keydown and keyup events, meanwhile Firefox and Safari will not process
+    // the hotkey combination until the keypress event will be raised (this event will be raised, if we
+    // called stopEventPropagation() for our specific keydown and keyup events before).
```
Comment (AlexanderMoskovkin) [inline src/client/core/prevent-real-events.js]: after this all we can simplify this comment. I suppose we can write just:
```js
Allow pressing hotkeys that opens devtools
(<list of hotkeys>)
```

**Comment by AlexanderMoskovkin** [comment]
lgtm

File: src/client/core/prevent-real-events.js (hunk 3 above)
Comment (georgiy-abbasov) [inline src/client/core/prevent-real-events.js]: I should explain some of nuances about the `keypress` event. After keydown, in Safari this event has the same value of `keyCode` property as the value of key `charCode`. In other words:
```js
e.type === 'keypress' && browserUtils.isSafari && event.keyCode === event.charCode // true
```
And here e.keyCode is  in [231, 94, 8710, 730];

In Firefox there is another situation:
`keyCode` property is 0, and charCode is simular as the `keycode`, which was before in `keydown` event
```js
e.type === 'keypress' && browserUtils.isFirefox && !event.keyCode && event.charCode // true
```
e.charCode is in  [67, 73, 74, 75, 123]

Comment (AlexanderMoskovkin) [inline src/client/core/prevent-real-events.js]: Hm, I just saw it. In fact you don't prevent all of `keypress` event in firefox and safari? Even if it just `enter` key or any other?

Comment (AlexanderMoskovkin) [inline src/client/core/prevent-real-events.js]: Anyway, I think we should not prevent allow any `key` events if `shift`+`ctrl`  or `command` (on Mac) keys are pressed. Is there no difference, what it that `ctrl+shift+i` or `ctrl+shift+<anykey>`. This hotkeys are used for browser service things, I think we should allow they all

Comment (georgiy-abbasov) [inline src/client/core/prevent-real-events.js]: Yes, it is. Source page will not process this `keypress` anyway, but browser will. I forgot this when simplified conditions. I can use this 
`const KEYPRESS_CHARCODES = [231, 94, 8710, 730];`

Comment (georgiy-abbasov) [inline src/client/core/prevent-real-events.js]: >  I think we should not prevent any key events if shift+ctrl or command (on Mac) keys are pressed. 

I'm totally agree.

Comment (georgiy-abbasov) [inline src/client/core/prevent-real-events.js]: ping @inikulin

Comment (inikulin) [inline src/client/core/prevent-real-events.js]: OK

File: src/client/core/prevent-real-events.js (hunk 2 above)
Comment (helen-dikareva) [inline src/client/core/prevent-real-events.js]: we don't need in this brackets `(e.shiftKey && e.ctrlKey)`
so, please add new files to lint task in `Gulpfile`

Comment (inikulin) [inline src/client/core/prevent-real-events.js]: BTW, if we already have this mechanism in legacy API and it differ - why it's in core? Shouldn't we move it to driver?

**Comment by georgiy-abbasov** [comment]
@testcafe-build-bot \retest

**Comment by georgiy-abbasov** [comment]
FPR

File: src/client/core/prevent-real-events.js [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+    'MSPointerDown', 'MSPointerMove', 'MSPointerOver', 'MSPointerOut', 'MSPointerUp', 'pointerdown',
+    'pointermove', 'pointerover', 'pointerout', 'pointerup'
+];
+
+const F12_KEY_CODE = 123;
+
+
+function checkDevToolsShortcut (e) {
+    // NOTE: Browser tools opening by F12, CTRL+SHIFT+<SYMBOL KEY> on PC or by OPTION(ALT)+CMD+<SYMBOL KEY> on Mac.
+    return e.shiftKey && e.ctrlKey || e.altKey && e.isMacPlatform || e.keyCode === F12_KEY_CODE;
```
Comment (AlexanderMoskovkin) [inline src/client/core/prevent-real-events.js]: since we allow `ctrl+alt+<ANY KEY>` combination it's not only `DevToolsShortcut`, maybe it's `browserServiceShortcut` or `browserHotKey` or something else like this?

File: src/client/core/prevent-real-events.js [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+}
+
+// NOTE: when test is run we should block real events (from mouse, keyboard), because it may lead to
+// unexpected test result.
```
Comment (AlexanderMoskovkin) [inline src/client/core/prevent-real-events.js]: Please make this comment more beauty
```js
// NOTE: when test is run we should block real events (from mouse,
// keyboard), because it may lead to unexpected test result.
```

Comment (helen-dikareva) [inline src/client/core/prevent-real-events.js]: This and others

File: test/functional/fixtures/driver/testcafe-fixtures/prevent-real-action-test.js [hunk 7]
```diff
@@ -0,0 +1,11 @@
+// NOTE: to preserve callsites, add new tests AFTER the existing ones
```
Comment (AlexanderMoskovkin) [inline test/functional/fixtures/driver/testcafe-fixtures/prevent-real-action-test.js]: there is no need for this comment in this test since we have no a test that should be failed

**Comment by AlexanderMoskovkin** [comment]
/r- just minor style issues

@VasilyStrelyaev please check strings

File: src/client/core/prevent-real-events.js [hunk 8]
```diff
@@ -0,0 +1,71 @@
...
+    'touchstart', 'touchmove', 'touchend', 'keydown', 'keypress', 'input', 'keyup', 'change', 'focus', 'blur',
+    'MSPointerDown', 'MSPointerMove', 'MSPointerOver', 'MSPointerOut', 'MSPointerUp', 'pointerdown',
+    'pointermove', 'pointerover', 'pointerout', 'pointerup'
+];
+
+const F12_KEY_CODE = 123;
+
+
+function checkDevToolsShortcut (e) {
+    // NOTE: Browser tools opening by F12, CTRL+SHIFT+<SYMBOL KEY> on PC or by OPTION(ALT)+CMD+<SYMBOL KEY> on Mac.
```
Comment (VasilyStrelyaev) [inline src/client/core/prevent-real-events.js]:
```
// NOTE: Opening browser tools with F12, CTRL+SHIFT+<SYMBOL KEY> on PC or with OPTION(ALT)+CMD+<SYMBOL KEY> on Mac.
```

File: src/client/core/prevent-real-events.js (hunk 6 above)
Comment (VasilyStrelyaev) [inline src/client/core/prevent-real-events.js]:
```
// NOTE: when test is running, we should block real events (from mouse or keyboard), 
// because they may lead to unexpected test result.
``

File: src/client/core/prevent-real-events.js [hunk 9]
```diff
@@ -0,0 +1,71 @@
...
+    return e.shiftKey && e.ctrlKey || e.altKey && e.isMacPlatform || e.keyCode === F12_KEY_CODE;
+}
+
+// NOTE: when test is run we should block real events (from mouse, keyboard), because it may lead to
+// unexpected test result.
+function preventRealEventHandler (e, dispatched, preventDefault, cancelHandlers, stopEventPropagation) {
+    var target = e.target || e.srcElement;
+
+    // NOTE: this will allow to press hotkeys to open developer tools
```
Comment (VasilyStrelyaev) [inline src/client/core/prevent-real-events.js]:
```
    // NOTE: this will allow pressing hotkeys to open developer tools
```

File: src/client/core/prevent-real-events.js [hunk 10]
```diff
@@ -0,0 +1,71 @@
...
+    if (/^key/.test(e.type) && checkDevToolsShortcut(e)) {
+        stopEventPropagation();
+        return;
+    }
+
+    if (!dispatched && !isShadowUIElement(target)) {
+        //If an element loses focus because of becoming invisible, a blur event is raised. We must not prevent this blur event.
+        //In the IE an element loses focus only if css display property is set to 'none', other ways of making
+        // element invisible don't lead to blurring (in MSEdge focus/blur is sync)
```
Comment (VasilyStrelyaev) [inline src/client/core/prevent-real-events.js]:
```
        // If an element loses focus because of becoming invisible, a blur event is raised. We must not prevent this blur event.
        // In IE, an element loses focus only if the CSS 'display' property is set to 'none', other ways of making
        // an element invisible don't lead to blurring (in MSEdge, focus/blur are sync)
```

File: src/client/core/prevent-real-events.js [hunk 11]
```diff
@@ -0,0 +1,71 @@
...
+                }
+
+                if (isElementInvisible || invisibleParents.length) {
+                    //B254768 - reason of setTimeout method using
+                    window.setTimeout(() => {
+                        eventSimulator.blur(target);
+                    }, 0);
+                }
+            }
+            //NOTE: fix for jQuery bug. An exception raises when call .is(':visible') for window or document on page loading (e.ownerDocument is null)
```
Comment (VasilyStrelyaev) [inline src/client/core/prevent-real-events.js]:
```
            //NOTE: fix for a jQuery bug. An exception is raised when calling .is(':visible') for a window or document on page loading (when e.ownerDocument is null)
```

File: test/functional/fixtures/driver/test.js [hunk 12]
```diff
@@ -22,4 +22,8 @@ describe('TestRun - Driver protocol', function () {
                 errorInEachBrowserContains(errs, '> 13 |    await t.click(\'#btn\');', 0);
             });
     });
+
+    it('Driver should prevent real action', function () {
```
Comment (VasilyStrelyaev) [inline test/functional/fixtures/driver/test.js]:
```
    it('Driver should prevent a real action', function () {
```

**Comment by VasilyStrelyaev** [comment]
\r-

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by helen-dikareva** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm

File: src/client/core/prevent-real-events.js [hunk 13]
```diff
@@ -0,0 +1,74 @@
...
+
+
+function checkBrowserHotkey (e) {
+    // NOTE: Opening browser tools with F12, CTRL+SHIFT+<SYMBOL KEY>
+    // on PC or with OPTION(ALT)+CMD+<SYMBOL KEY> on Mac.
+    return e.shiftKey && e.ctrlKey || e.altKey && e.isMacPlatform || e.keyCode === F12_KEY_CODE;
+}
+
+// NOTE: when test is running, we should block real events (from mouse
+// or keyboard), because they may lead to unexpected test result.
```
Comment (VasilyStrelyaev) [inline src/client/core/prevent-real-events.js]: sorry, missed it!
thanks to @AlexanderMoskovkin for noticing this
```
// NOTE: when tests are running, we should block real events (from mouse
// or keyboard), because they may lead to unexpected test result.
```

**Comment by VasilyStrelyaev** [comment]
\r-

**Comment by AlexanderMoskovkin** [comment]
lgtm just correct the comment

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm
