### PR TITLE
Fix excessive await warning interaction with repeated logic

### LINKED ISSUE #5389: Snapshot property warnings work incorrectly with loops
### What is your Test Scenario?
Assert an unawaited snapshot property multiple times in a loop.
 
### What is the Current behavior?
The warning is raised as if the snapshot was awaited.

### What is the Expected behavior?
TestCafe should not raise warnings and the test should pass correctly.

### Your complete test code (or attach your test files):

 
```js
import { Selector } from 'testcafe';
fixture `Loop`;
test.only("looped assertion warning test", async t => {
    for (let i = 0; i < 2; i++) {
        await t
            .expect(Selector('body').innerText).ok();
    }
});
```

### Your complete test report:

```
Running tests in:
 - Chrome 84.0.4147.105 / Windows 10

 Loop
 √ looped assertion warning test


 1 passed (1s)

 Warnings (1):
 --
  You passed a DOM snapshot property to the assertion's 't.expect()' method. The property value is assigned when the snapshot is resolved and this value is no longer updated. To ensure that the assertion verifies an
  up-to-date value, pass the selector property without 'await'.

     1 |import { Selector } from 'testcafe';
     2 |fixture `Loop`;
     3 |test.only("looped assertion warning test", async t => {
     4 |    for (let i = 0; i < 2; i++) {
     5 |        await t
   > 6 |            .expect(Selector('body').innerText).ok();
     7 |    }
     8 |});

     at <anonymous> (D:\Work\tests\expectTest\loop-test.js:6:21)
     at <anonymous> (D:\Work\tests\expectTest\loop-test.js:3:1)
```

### Your Environment details:
 
* testcafe version:                   1.9.0-rc.1
* node.js version:                    v12.16.1
* command-line arguments:  npx testcafe chrome .\loop-test.js
* browser name and version: Chrome 84.0.4147.105
* platform and version:          Windows

### LINKED ISSUE #5449: Snapshot property warnings work incorrectly with helper functions
Using the example code from @Ogurecher I also get the warnings, despite them not being prefixed by `await`. 

I am honestly baffled how a super hacky method like checking line numbers ever got merged. Not least because autoformatters such as Prettier will force the expect and selector to be on the same line in most cases. Adding a warning of this kind is fine but not with this implementation. I have made a hacky fix by putting my selectors on different lines for now but I hope this is changed in a future release.

Regardless, for me personally it is failing even with selector and expect on the same line and I've forked @Ogurecher 's sample repo and made a reproducable sample: https://github.com/favna/warning-example
Simply run `npm run test` to run testcafe here

_Originally posted by @Favna in https://github.com/DevExpress/testcafe/pull/5250#issuecomment-678322252_

### PR DESCRIPTION
**Pull request by Ogurecher**
## Purpose
Excessive await warnings work incorrectly with repeated logic.

When the snapshot property promise is resolved, its callsite is saved to a callsite storage. We check this storage in the `.expect` assertion call. If the storage contains a callsite with the same `filename` and `lineNumber` as the `.expect`'s callsite, we delete it and raise a warning.

If the property was not awaited, the `.expect` would execute before the property promise's `.then` method. Thus, some callsites would remain in the storage after they were asserted (we delete them only in `.expect`). It works fine if we use our assertion only once, but causes the warnings to raise if we call `.expect` from the same line of code again.

## Approach
We need to make sure that the stored callsite is cleaned either after `.expect` or `.then` (whichever is called later).
This gives us the following flow:
 - In `.then`: delete the stored callsite if possible. If there is nothing to delete, add a callsite to the storage.
 - In `.expect`: delete the stored callsite if possible (and raise a warning). If there is nothing to delete, add a callsite to the storage.

This flow is not perfect though. There are some issues with it:
 - It breaks if there are more than 2 `.then` or `.expect` calls in a row. We need to differentiate beetween those callsite types.
 - We only raise one warning if there are multiple awaited properties in one assertion. We need to store multiple callsites per assertion.
 - If the property is awaited multiple times in a loop, we raise multiple warnings pointing to the same line of code. In my opinion, this is redundant as the user does not gain new information from the repeated warnings. (They only need to remove one `await`). We need to filter out the repeated warnings.

I've addressed the first issue by adding the `checked` property to the stored object. When `.expect` adds a callsite to the storage, its `checked` property is set to `true`. Same for `then`, but `checked` = `false` in that case. Now `.expect` deletes only the unasserted properties (added to the storage by `.then`) and `.then` deletes only the asserted properties (added to the storage by `.expect`).

I've addressed the second issue by storing additional `CallsiteRecord`s in the stored object. They are added in the `.then` method call if there is a stored callsite from the same line of code but the `checked` property is `false`. In `.expect` I add warnings for each of these `CallsiteRecord`s.

To address the third problem, I've added an extra `Map` for problematic callsites that we use to raise warnings. I've used the `string` representation of the callsite's `stackFrame` (basically, filename:lineNum:colNum) to filter out duplicate callsites. The warnings themselves are now thrown after the test run is finished. 

## References
Closes #5449
Closes #5389

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [x] Make sure that existing tests do not fail

### CODE REVIEW

File: src/api/test-controller/index.js [hunk 1]
```diff
@@ -389,15 +389,24 @@ export default class TestController {
         return this.testRun.executeAction(name, new GetBrowserConsoleMessagesCommand(), callsite);
     }
 
-    _checkForExcessiveAwaits (selectorCallsiteList, expectCallsite) {
-        for (const selectorCallsite of selectorCallsiteList) {
-            if (selectorCallsite.filename === expectCallsite.filename &&
-                selectorCallsite.lineNum === expectCallsite.lineNum) {
-                addWarning(this.warningLog, WARNING_MESSAGE.excessiveAwaitInAssertion, selectorCallsite);
+    // NOTE: Gets the callsite stackFrame string representation: 'filename:lineNum:colNum'
```
Comment (miherlosev) [inline src/api/test-controller/index.js:392]: It's better to use the JSDoc format for method description.

```js
/**
* Gets the callsite stackFrame string representation: 'filename:lineNum:colNum'
*/
```

File: src/api/test-controller/index.js [hunk 2]
```diff
@@ -389,15 +389,24 @@ export default class TestController {
...
+    _getCallsiteStackFrameString (callsite) {
+        return callsite.stackFrames[callsite.callsiteFrameIdx].toString();
+    }
 
-                selectorCallsiteList.delete(selectorCallsite);
-            }
+    _checkForExcessiveAwaits (snapshotPropertyCallsites, callsiteToCheck) {
```
Comment (miherlosev) [inline src/api/test-controller/index.js:397]: _checkForExcessiveAwaits (snapshotPropertyCallsites, checkCallsite) {

File: src/api/test-controller/index.js [hunk 3]
```diff
@@ -389,15 +389,24 @@ export default class TestController {
...
+        const key = `${callsiteToCheck.filename}:${callsiteToCheck.lineNum}`;
```
Comment (miherlosev) [inline src/api/test-controller/index.js:398]: `const callsiteId = ...`

File: src/api/test-controller/index.js [hunk 4]
```diff
@@ -389,15 +389,24 @@ export default class TestController {
...
+
+        // NOTE: If there are unasserted callsites, we should add all of them to awaitedSnapshotWarnings.
+        // The warnings themselves are raised after the test run in wrap-test-function
+        if (snapshotPropertyCallsites[key] && snapshotPropertyCallsites[key].asserted === false) {
```
Comment (miherlosev) [inline src/api/test-controller/index.js:402]: `if (snapshotPropertyCallsites[key] && !snapshotPropertyCallsites[key].checked)`

File: src/api/test-controller/index.js [hunk 5]
```diff
@@ -389,15 +389,24 @@ export default class TestController {
         return this.testRun.executeAction(name, new GetBrowserConsoleMessagesCommand(), callsite);
     }
 
-    _checkForExcessiveAwaits (selectorCallsiteList, expectCallsite) {
-        for (const selectorCallsite of selectorCallsiteList) {
-            if (selectorCallsite.filename === expectCallsite.filename &&
-                selectorCallsite.lineNum === expectCallsite.lineNum) {
-                addWarning(this.warningLog, WARNING_MESSAGE.excessiveAwaitInAssertion, selectorCallsite);
+    // NOTE: Gets the callsite stackFrame string representation: 'filename:lineNum:colNum'
+    _getCallsiteStackFrameString (callsite) {
```
Comment (miherlosev) [inline src/api/test-controller/index.js:393]: Add `utils/callsite.ts` file with two utility functions:
```js
  getCallsiteStackFrameString ()
  getCallsiteId () -> `${callsiteToCheck.filename}:${callsiteToCheck.lineNum}`
```

File: src/client-functions/selectors/add-api.js [hunk 6]
```diff
@@ -118,6 +118,24 @@ function createPrimitiveGetterWrapper (observedCallsites, callsite) {
...
 }
 
+function checkForExcessiveAwaits (snapshotPropertyCallsites, callsiteToCheck) {
+    const key = `${callsiteToCheck.filename}:${callsiteToCheck.lineNum}`;
+
+    let callsitesToAssert = [ callsiteToCheck ];
+
+    // NOTE: If the calliste already exists, but is not asserted, it means that there are
+    // multiple awaited callsites in one assertion. We raise a warning for each of them.
+    if (snapshotPropertyCallsites[key] && snapshotPropertyCallsites[key].asserted === false)
```
Comment (miherlosev) [inline src/client-functions/selectors/add-api.js:128]: Rewrite using the following structure
```js
if ()
else if ()
else
```

**Review by miherlosev — CHANGES_REQUESTED** [review]

File: src/api/test-controller/index.js (hunk 3 above)
Comment (Ogurecher) [reply src/api/test-controller/index.js:398]: I'm not sure if we should call it an ID since there can be callsites with the matching filename:lineNum pair

File: src/client-functions/selectors/add-api.js (hunk 6 above)
Comment (Ogurecher) [reply src/client-functions/selectors/add-api.js]: Adding another callsite  to the `callsitesToAssert`
`callsitesToAssert = snapshotPropertyCallsites[key].callsites.concat(callsitesToAssert);`

and setting `snapshotPropertyCallsites[key]` 
`snapshotPropertyCallsites[key] = { callsites: callsitesToAssert, checked: false };`

are not mutually exclusive - we still want to set `snapshotPropertyCallsites[key]`, even if we added a callsite to the list.

At the same time, setting `snapshotPropertyCallsites[key]` and deleting it are mutually exclusive - we don't want to do both.

I've rewrote these conditions as you suggested, but I had to use this line twice:
`snapshotPropertyCallsites[callsiteId] = { callsites: callsitesToAssert, checked: false };`

Comment (Ogurecher) [reply src/client-functions/selectors/add-api.js]: Actually, nevermind. I think, I can simplify it a little differently

File: src/api/test-controller/index.js (hunk 3 above)
Comment (miherlosev) [reply src/api/test-controller/index.js]: I agree with you about ID. If you can imagine a better name - you are welcome.

**Review by miherlosev — APPROVED** [review]

File: src/api/test-controller/index.js (hunk 3 above)
Comment (Ogurecher) [reply src/api/test-controller/index.js]: Would `callsiteLineId` (or just `lineId`) be better?

**Review by AlexKamaev — APPROVED** [review]
