### PR TITLE
Status bar grabbed focus problem fixed (closes #1200)

### LINKED ISSUE #1200: Click on `debugging panel` has an affect on the tested page
it's related to the new t.debug() action (#918)

When the tests is stopped on `debug()` and some element is focused on the page, click on the `resume test` button leads to active element changing but it should not. 

Test for check it:
```js
test('Dealing with text using keyboard', async t => {
    await t
        .typeText(page.nameInput, 'Peter Parker')           // Type name
        .click(page.nameInput, { caretPos: 5 })             // Move caret position
        .debug()
        .pressKey('backspace')                              // Erase a character
        .expect(page.nameInput.value).eql('Pete Parker');
});
```

### PR DESCRIPTION
**Pull request by helen-dikareva**
/cc @AlexanderMoskovkin @AndreyBelym

### CODE REVIEW

File: src/client/ui/status-bar/index.js [hunk 1]
```diff
@@ -350,27 +355,34 @@ export default class StatusBar {
...
+        this.nextActionButtonHandler = e => {
+            eventUtils.preventDefault(e);
+            this._resetState();
+            eventUtils.unbind(this.continueButton, eventName, this.continueButtonHandler);
+            eventUtils.unbind(this.nextActionButton, eventName, this.nextActionButtonHandler);
+            callback(true);
+        };
+
+        eventUtils.bind(this.continueButton, eventName, this.continueButtonHandler);
+        eventUtils.bind(this.nextActionButton, eventName, this.nextActionButtonHandler);
```
Comment (AlexanderMoskovkin) [inline src/client/ui/status-bar/index.js]: Hmm.. I can't understand, why have you replaced `Promise` with `callback` here?
And why do we need to add the continueButtonHandler to the field of the class? Why not a simple variables?

Comment (helen-dikareva) [inline src/client/ui/status-bar/index.js]: accident :)
