### PR TITLE
fix: error messages should have correct diffs

### LINKED ISSUE #5473: Incorrect diff for the expect.contains assertion
### What is your Test Scenario?
Use `expect.contains` to compare two string values.

### What is the Current behavior?
An incorrect diff shown (pay attention to the error message and the diff):
```
AssertionError: expected 'test' to include 'foo'

      + expected - actual

      -'test'
      +undefined
```
### What is the Expected behavior?
```
AssertionError: expected 'test' to include 'foo'

      + expected - actual

      -'foo'
      +'test'
``` 
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 fixture`1`.page`./index.html`

test(`1`, async t => {
    await t.expect('test').contains('foo');
});
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

Run the test
 
### Your Environment details:
 
* testcafe version:                   v1.9.1
* node.js version:                    v14.1.0
* command-line arguments:  `testcafe chrome test.js`
* browser name and version: Chrome 84
* platform and version:          Windows 10
* other:

### PR DESCRIPTION
**Pull request by wentwrong**
## Purpose
TestCafe shows incorrect diffs in the error messages that result from failed assertions.

## Approach
Chai includes the `showDiff` flag in the thrown `AssertionError` objects. Since we use the `chai` library for our built-in assertions, we can use this flag to decide whether the diff should be generated or not. 

- we can be sure that the diff is always correct; 
- user can tweak the `chai.config.showDiff` setting and omit the diffs: https://www.chaijs.com/guide/styles/
- we won't interfere with the Node.js built-in `assert` module output, which independently includes diffs in the error messages

## References
Closes #5473

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

### CODE REVIEW

**Review by miherlosev — APPROVED** [review]

**Comment by wentwrong** [comment]
The tests are green
- all tasks are green (except `travis.test-client-travis-mobile`) - https://github.com/DevExpress/testcafe/pull/6071#issuecomment-803995581
- the `travis.test-client-travis-mobile` task is green - https://travis-ci.com/github/testcafe-build-bot/testcafe/jobs/492801795

File: src/utils/diff/index.ts [hunk 1]
```diff
@@ -21,7 +21,7 @@ function unifiedDiff (actual: string, expected: string): string {
     ;
 }
 
-export function generate (actual: string, expected: string): string {
+export function generate (actual: unknown, expected: unknown): string {
```
Comment (AndreyBelym) [inline src/utils/diff/index.ts:24]: 👍

**Review by AndreyBelym — APPROVED** [review]
