### PR TITLE
Do not set breakpoints during switching to role (closes #1359)

### LINKED ISSUE #1359: Server crashes when I try to debug 'useRole' action
Test code

```javascript
import { Selector, Role } from 'testcafe';

const regularAccUser = Role('https://github.com/login', async t => {
    await t
        .typeText('#login_field', 'churkin')
        .typeText('#password', '****')
        .pressKey('enter');
});

fixture `My first test`
    .page `http://github.com/`;

test('test1', async t => {
    await t
        .debug()
        .useRole(regularAccUser)
        .expect(Selector('.avatar').getAttribute('alt')).eql('@churkin');
});
```

Error:
```
  1) - Error in Role initializer -
      TypeError: Cannot read property 'renderSync' of undefined

      Browser: Chrome 59.0.3049 / Windows 8.1 0.0.0

         85 |        this.debugLogging = false;
         86 |    },
         87 |    showBreakpoint: function showBreakpoint(testRunId,
      userAgent, callsite) {
         88 |        if (!this.streamsOverridden) this._overrideStreams();
         89 |
       > 90 |        var callsiteStr = callsite.renderSync({
         91 |            frameSize: 1,
         92 |            stackFilter: (0,
      _createStackFilter2.default)(Error.stackTraceLimit),
         93 |            stack: false
         94 |        });
         95 |
```

### PR DESCRIPTION
**Pull request by helen-dikareva**
/cc @inikulin @churkin

### CODE REVIEW

File: src/role/index.js [hunk 1]
```diff
@@ -36,12 +36,16 @@ class Role extends EventEmitter {
...
 
         try {
+            testRun.debugging = debugging;
             await this.initFn(testRun);
         }
         catch (err) {
             this.initErr = err;
         }
 
+        testRun.previousDebuggingState = testRun.debugging;
```
Comment (inikulin) [inline src/role/index.js]: No need for reassign here. Role switch is not reentrant

File: src/test-run/index.js [hunk 2]
```diff
@@ -84,7 +84,8 @@ export default class TestRun extends Session {
         this.fileDownloadingHandled               = false;
         this.resolveWaitForFileDownloadingPromise = null;
 
-        this.debugging = false;
+        this.debugging              = false;
+        this.previousDebuggingState = false;
```
Comment (inikulin) [inline src/test-run/index.js]: It would be nice to avoid class-level variable here. Let use local var and just pass it to `getSnapshotFromRole`

File: src/role/index.js (hunk 1 above)
Comment (helen-dikareva) [inline src/role/index.js]: We need, because during execution role's actions step-by-spep user can click on button `Resume test` so `testRun.debugging` flag should be reasigned

File: src/test-run/index.js (hunk 2 above)
Comment (helen-dikareva) [inline src/test-run/index.js]: It would be nice but we can't (see comment above)

**Comment by inikulin** [comment]
It's quite messy :/ What if we introduce `disableDebugBreakpoints` var which is checked when we decide if we need to add breakpoint command? In that case we can avoid this multiple reassignments

**Comment by inikulin** [comment]
Where are lint errors
